<?php

class Case_type_tagsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
         DB::table('case_type_tags')->truncate();

        $case_type_tags = array(
            ["case_id" => 1, "type" => "Theft"],
            ["case_id" => 2, "type" => "Rape"],
            ["case_id" => 2, "type" => "Grave threats"],
            ["case_id" => 3, "type" => "Uncategorized"],
            ["case_id" => 4, "type" => "Prostitution"],
            ["case_id" => 4, "type" => "Corruption of minor"],
            ["case_id" => 4, "type" => "Seduction"],
            ["case_id" => 5, "type" => "Murder"],
            ["case_id" => 5, "type" => "Direct assault"],
            ["case_id" => 6, "type" => "Homicide"],
            ["case_id" => 6, "type" => "Direct assault"],
            ["case_id" => 7, "type" => "Suicide"],
            ["case_id" => 8, "type" => "Murder"],
            ["case_id" => 8, "type" => "Serious physical injuries"],
            ["case_id" => 9, "type" => "Immortal doctrines, obscene publications and exhibitions"],
            ["case_id" => 9, "type" => "Parricide"],
            ["case_id" => 9, "type" => "Infanticide"],
            ["case_id" => 10, "type" => "Gambling and Betting"],
            ["case_id" => 10, "type" => "Illegal association"],
            ["case_id" => 10, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 11, "type" => "Murder"],
            ["case_id" => 11, "type" => "Direct Assault"],
            ["case_id" => 12, "type" => "Counterfeiting"],
            ["case_id" => 12, "type" => "Falsification"],
            ["case_id" => 13, "type" => "Abduction"],
            ["case_id" => 13, "type" => "Kidnapping"],
            ["case_id" => 13, "type" => "Slavery"],
            ["case_id" => 13, "type" => "Grave coercions"],
            ["case_id" => 13, "type" => "Corruption of minor"],
            ["case_id" => 14, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 14, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 14, "type" => "Light threats"],
            ["case_id" => 15, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 15, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 16, "type" => "Fraud"],
            ["case_id" => 16, "type" => "Falsification"],
            ["case_id" => 17, "type" => "Indirect assault"],
            ["case_id" => 17, "type" => "Murder"],
            ["case_id" => 18, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 18, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 18, "type" => "Light Threats"],
            ["case_id" => 18, "type" => "Physical Injuries"],
            ["case_id" => 19, "type" => "Rape"],
            ["case_id" => 19, "type" => "Bribery"],
            ["case_id" => 19, "type" => "Grave coercions"],
            ["case_id" => 19, "type" => "Light threats"],
            ["case_id" => 20, "type" => "Homicide"],
            ["case_id" => 20, "type" => "Indirect assault"],
            ["case_id" => 20, "type" => "Physical Injuries"],
            ["case_id" => 21, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 21, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 21, "type" => "Bribery"],
            ["case_id" => 22, "type" => "Murder"],
            ["case_id" => 23, "type" => "Indirect assault"],
            ["case_id" => 23, "type" => "Homicide"],
            ["case_id" => 23, "type" => "Drunk driving"],
            ["case_id" => 24, "type" => "Homicide"],
            ["case_id" => 24, "type" => "Robbery"],
            ["case_id" => 24, "type" => "Brigandage"],
            ["case_id" => 24, "type" => "Indirect assault"],
            ["case_id" => 24, "type" => "Physical Injuries"],
            ["case_id" => 24, "type" => "Abandonment of helpless persons"],
            ["case_id" => 24, "type" => "Grave threats"],
            ["case_id" => 25, "type" => "Suicide"],
            ["case_id" => 25, "type" => "Vandalism"],
            ["case_id" => 25, "type" => "Public disorder"],
            ["case_id" => 26, "type" => "Rape"],
            ["case_id" => 26, "type" => "Malicious mischief"],
            ["case_id" => 26, "type" => "Grave coercions"],
            ["case_id" => 26, "type" => "Grave threats"],
            ["case_id" => 27, "type" => "Prostitution"],
            ["case_id" => 27, "type" => "Seduction"],
            ["case_id" => 28, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 28, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 28, "type" => "Illegal assemblies"],
            ["case_id" => 29, "type" => "Rape"],
            ["case_id" => 29, "type" => "Malicious mischief"],
            ["case_id" => 29, "type" => "Grave coercions"],
            ["case_id" => 29, "type" => "Grave threats"],
            ["case_id" => 30, "type" => "Counterfeiting"],
            ["case_id" => 30, "type" => "Falsification"],
            ["case_id" => 30, "type" => "Piracy"],
            ["case_id" => 31, "type" => "Murder"],
            ["case_id" => 31, "type" => "Public disorder"],
            ["case_id" => 31, "type" => "Discharge of firearms"],
            ["case_id" => 32, "type" => "Fraud"],
            ["case_id" => 32, "type" => "Falsification"],
            ["case_id" => 33, "type" => "Falsification"],
            ["case_id" => 33, "type" => "Fraud"],
            ["case_id" => 34, "type" => "Falsification"],
            ["case_id" => 34, "type" => "Fraud"],
            ["case_id" => 35, "type" => "Fraud"],
            ["case_id" => 35, "type" => "Falsification"],
            ["case_id" => 35, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 35, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 36, "type" => "Fraud"],
            ["case_id" => 37, "type" => "Robbery"],
            ["case_id" => 37, "type" => "Brigandage"],
            ["case_id" => 37, "type" => "Public disorder"],
            ["case_id" => 37, "type" => "Discharge of firearms"],
            ["case_id" => 38, "type" => "Murder"],
            ["case_id" => 39, "type" => "Arson"],
            ["case_id" => 40, "type" => "Brigandage"],
            ["case_id" => 40, "type" => "Light threats"],
            ["case_id" => 40, "type" => "Grave coercions"],
            ["case_id" => 41, "type" => "Mutilation"],
            ["case_id" => 41, "type" => "Grave coercions"],
            ["case_id" => 41, "type" => "Seduction"],
            ["case_id" => 42, "type" => "Serious physical injuries"],
            ["case_id" => 42, "type" => "Abuses against chastity"],
            ["case_id" => 43, "type" => "Abduction"],
            ["case_id" => 43, "type" => "Kidnapping"],
            ["case_id" => 43, "type" => "Slavery"],
            ["case_id" => 44, "type" => "Rape"],
            ["case_id" => 44, "type" => "Malicious mischief"],
            ["case_id" => 44, "type" => "Grave coercions"],
            ["case_id" => 44, "type" => "Grave threats"],
            ["case_id" => 45, "type" => "Slavery"],
            ["case_id" => 45, "type" => "Exploitation of minors"],
            ["case_id" => 46, "type" => "Abandonment of helpless persons"],
            ["case_id" => 47, "type" => "Prostitution"],
            ["case_id" => 47, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 47, "type" => "Possession, preparation and use of prohibited drugs and maintenance of opium dens"],
            ["case_id" => 48, "type" => "Trespassing"],
            ["case_id" => 48, "type" => "Violation of domicile"],
            ["case_id" => 49, "type" => "Murder"],
            ["case_id" => 50, "type" => "Abuses against chastity"],
            ["case_id" => 50, "type" => "Corruption of minor"],
            ["case_id" => 50, "type" => "Malicious mischief"],
            ["case_id" => 51, "type" => "Slavery"],
            ["case_id" => 51, "type" => "Exploitation of minors"],
            ["case_id" => 52, "type" => "Brigandage"],
            ["case_id" => 52, "type" => "Discharge of firearms"],
            ["case_id" => 53, "type" => "Brigandage"],
            ["case_id" => 53, "type" => "Theft"],
            ["case_id" => 54, "type" => "Theft"],
            ["case_id" => 55, "type" => "Swindling"],
            ["case_id" => 56, "type" => "Arson"],
            ["case_id" => 57, "type" => "Rape"],
            ["case_id" => 57, "type" => "Malicious mischief"],
            ["case_id" => 57, "type" => "Grave coercions"],
            ["case_id" => 57, "type" => "Grave threats"],
            ["case_id" => 57, "type" => "Corruption of minor"],
            ["case_id" => 57, "type" => "Abuses against chastity"],
            ["case_id" => 58, "type" => "Rape"],
            ["case_id" => 58, "type" => "Malicious mischief"],
            ["case_id" => 58, "type" => "Grave coercions"],
            ["case_id" => 58, "type" => "Grave threats"],
            ["case_id" => 59, "type" => "Bribery"],
            ["case_id" => 60, "type" => "Abduction"],
            ["case_id" => 60, "type" => "Kidnapping"],
            ["case_id" => 60, "type" => "Slavery"],
            ["case_id" => 61, "type" => "Abortion"],
            ["case_id" => 62, "type" => "Murder"],
            ["case_id" => 62, "type" => "Infanticide"],
            ["case_id" => 63, "type" => "Rape"],
            ["case_id" => 63, "type" => "Abuses against chastity"],
            ["case_id" => 63, "type" => "Light threats"],
            ["case_id" => 64, "type" => "Theft"],
            ["case_id" => 65, "type" => "Murder"],
            ["case_id" => 65, "type" => "Parricide"],
            ["case_id" => 66, "type" => "Direct assault"],
            ["case_id" => 66, "type" => "Murder"],
            ["case_id" => 67, "type" => "Murder"],
            ["case_id" => 68, "type" => "Murder"],
            ["case_id" => 68, "type" => "Infanticide"],
            ["case_id" => 69, "type" => "Robbery"],
            ["case_id" => 69, "type" => "Grave threats"],
            ["case_id" => 69, "type" => "Discharge of firearms"],
            ["case_id" => 70, "type" => "Libel"],
            ["case_id" => 71, "type" => "Arson"],
            ["case_id" => 71, "type" => "Violation of domicile"],
            ["case_id" => 72, "type" => "Slander"],
            ["case_id" => 73, "type" => "Libel"],
            ["case_id" => 74, "type" => "Brigandage"],
            ["case_id" => 74, "type" => "Discharge of firearms"],
            ["case_id" => 74, "type" => "Robbery"],
            ["case_id" => 74, "type" => "Light threats"],
            ["case_id" => 75, "type" => "Rape"],
            ["case_id" => 75, "type" => "Malicious mischief"],
            ["case_id" => 75, "type" => "Grave coercions"],
            ["case_id" => 76, "type" => "Adultery"],
            ["case_id" => 76, "type" => "Abuses against chastity"],
            ["case_id" => 76, "type" => "Light threats"],
            ["case_id" => 77, "type" => "Murder"],
            ["case_id" => 77, "type" => "Possession of Dangerous Drugs For Sale"],
            ["case_id" => 78, "type" => "Counterfeiting"],
            ["case_id" => 78, "type" => "Falsification"],
            ["case_id" => 78, "type" => "Piracy"],
            ["case_id" => 79, "type" => "Counterfeiting"],
            ["case_id" => 79, "type" => "Falsification"],
            ["case_id" => 80, "type" => "Kidnapping"],
            ["case_id" => 80, "type" => "Slavery"],
            //EWPID

            ["case_id" => 81, "type" => "Forgery"],

            ["case_id" => 82, "type" => "Gambling"],
            ["case_id" => 82, "type" => "Kidnapping"],

            ["case_id" => 83, "type" => "Sexual Abuse"],

            ["case_id" => 84, "type" => "Grave Scandal"],
            ["case_id" => 84, "type" => "Rape"],

            ["case_id" => 85, "type" => "Public Disorder"],
            ["case_id" => 86, "type" => "Direct Assault"],
            ["case_id" => 87, "type" => "Forgery"],
            ["case_id" => 88, "type" => "Bribery"],
            ["case_id" => 89, "type" => "Prohibited transaction"],
            ["case_id" => 90, "type" => "Infidelity"], 


            //DID

            ["case_id" => 91, "type" => "Disobedience"],
            ["case_id" => 92, "type" => "Relevance of secret"],

            ["case_id" => 93, "type" => "Maltreatment of Prisoner"],
            ["case_id" => 93, "type" => "Sexual Abuse"],

            ["case_id" => 94, "type" => "Usurpation"],
            ["case_id" => 95, "type" => "Suicide"],
            ["case_id" => 96, "type" => "Abortion"],
            ["case_id" => 97, "type" => "Infanticide"],

            ["case_id" => 98, "type" => "Serious illegal detention"],
            ["case_id" => 98, "type" => "Plunder"],

            ["case_id" => 99, "type" => "Kidnapping"],
            ["case_id" => 100, "type" => "Slavery"], 



            //IPRD

            ["case_id" => 101, "type" => "Drunk driving"],

            ["case_id" => 102, "type" => "Possession of dangerous drugs"],
            ["case_id" => 102, "type" => "Suicide"],

            ["case_id" => 103, "type" => "Vandalism"],
            ["case_id" => 104, "type" => "Robbery"],
            ["case_id" => 105, "type" => "Treason"],
            ["case_id" => 106, "type" => "Espionage"],
            ["case_id" => 107, "type" => "Robbery"],

            ["case_id" => 108, "type" => "Rape"],
            ["case_id" => 108, "type" => "Sexual Abuse"],

            ["case_id" => 109, "type" => "Domestic Violence"],
            ["case_id" => 110, "type" => "Petty theft"], 

            //RAID

            ["case_id" => 111, "type" => "Arbitrary Detention"],
            ["case_id" => 112, "type" => "Expulsion"],
            ["case_id" => 113, "type" => "Violation of domicile"],
            ["case_id" => 114, "type" => "Prohibition, interruption, and dissolution of peaceful meetings"],

            ["case_id" => 115, "type" => "Rebellion"],
            ["case_id" => 115, "type" => "Disobedience"],

            ["case_id" => 116, "type" => "Disloyalty"],
            ["case_id" => 117, "type" => "Disturbance of proceedings"],
            ["case_id" => 118, "type" => "Illegal Assemblies"],

            ["case_id" => 119, "type" => "Direct Assault"],
            ["case_id" => 119, "type" => "Slavery"],

            ["case_id" => 120, "type" => "Direct Assault"], 

            //VAWCD

            ["case_id" => 121, "type" => "Public Disorder"],
            ["case_id" => 122, "type" => "Forgery"],

            ["case_id" => 123, "type" => "Falsification"],
            ["case_id" => 123, "type" => "Forgery"],

            ["case_id" => 124, "type" => "Fraud"],
            ["case_id" => 125, "type" => "Dereliction of duty"],
            ["case_id" => 126, "type" => "Bribery"],

            ["case_id" => 127, "type" => "Prohibited Transaction"],
            ["case_id" => 127, "type" => "Possession of dangerous drugs"],
            
            ["case_id" => 128, "type" => "Infidelity"],
            ["case_id" => 129, "type" => "Disobedience"],
            ["case_id" => 130, "type" => "Forgery"],  
            
        );

        // Uncomment the below to run the seeder
         DB::table('case_type_tags')->insert($case_type_tags);
    }

}
