<?php

class Client_addressesTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('client_addresses')->truncate();

        $client_addresses = array(
            ["client_id" => "1", "street" => "1234 Red", "city" => "Quezon", "postal_code" => "1200",
                "province" => "", "barangay" => "Barangay Nissan"],
            ["client_id" => "2", "street" => "1234 Green", "city" => "Manila", "postal_code" => "1201",
                "province" => "", "barangay" => "Barangay Toyota"],
            ["client_id" => "3", "street" => "1234 Blue", "city" => "Caloocan", "postal_code" => "1202",
                "province" => "", "barangay" => "Barangay Mitsubishi"],
            ["client_id" => "4", "street" => "1234 Yellow", "city" => "Pasay", "postal_code" => "1203",
                "province" => "", "barangay" => "Barangay Honda"],
            ["client_id" => "5", "street" => "1234 Purple", "city" => "Pateros", "postal_code" => "1204",
                "province" => "", "barangay" => "Barangay Ferrari"],
            ["client_id" => "6", "street" => "1234 Brown", "city" => "Antipolo", "postal_code" => "1205",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "7", "street" => "1234 White", "city" => "Pasig", "postal_code" => "1206",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "8", "street" => "1234 Black", "city" => "Taguig", "postal_code" => "1207",
                "province" => "", "barangay" => "Barangay Chevrolet"],
            ["client_id" => "9", "street" => "1234 Silver", "city" => "Cavite", "postal_code" => "1208",
                "province" => "", "barangay" => "Barangay Ford"],
            ["client_id" => "10", "street" => "1234 Gold", "city" => "Makati", "postal_code" => "1209",
                "province" => "", "barangay" => "Barangay Isuzu"],
            ["client_id" => "11", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "12", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "13", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "14", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "15", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "16", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "17", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "18", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "19", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "20", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "21", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "22", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "23", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "24", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "25", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "26", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "27", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "28", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "29", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "30", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "31", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "32", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "33", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "34", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "35", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "36", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "37", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "38", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "39", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "40", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "41", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "42", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "43", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "44", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "45", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "46", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "47", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "48", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "49", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "50", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "51", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "52", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "53", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "54", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "55", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "56", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "57", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "58", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "59", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "60", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "61", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "62", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "63", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "64", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "65", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "66", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "67", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "68", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "69", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "70", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "71", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "72", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "73", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "74", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "75", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "76", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "77", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "78", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "79", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "80", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "81", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "82", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "83", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "84", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "85", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "86", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "87", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "88", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "89", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "90", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "91", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "92", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "93", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "94", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "95", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "96", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "97", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "98", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "99", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "100", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "101", "street" => "1234 Red", "city" => "Quezon", "postal_code" => "1200",
                "province" => "", "barangay" => "Barangay Nissan"],
            ["client_id" => "102", "street" => "1234 Green", "city" => "Manila", "postal_code" => "1201",
                "province" => "", "barangay" => "Barangay Toyota"],
            ["client_id" => "103", "street" => "1234 Blue", "city" => "Caloocan", "postal_code" => "1202",
                "province" => "", "barangay" => "Barangay Mitsubishi"],
            ["client_id" => "104", "street" => "1234 Yellow", "city" => "Pasay", "postal_code" => "1203",
                "province" => "", "barangay" => "Barangay Honda"],
            ["client_id" => "105", "street" => "1234 Purple", "city" => "Pateros", "postal_code" => "1204",
                "province" => "", "barangay" => "Barangay Ferrari"],
            ["client_id" => "106", "street" => "1234 Brown", "city" => "Antipolo", "postal_code" => "1205",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "107", "street" => "1234 White", "city" => "Pasig", "postal_code" => "1206",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "108", "street" => "1234 Black", "city" => "Taguig", "postal_code" => "1207",
                "province" => "", "barangay" => "Barangay Chevrolet"],
            ["client_id" => "109", "street" => "1234 Silver", "city" => "Cavite", "postal_code" => "1208",
                "province" => "", "barangay" => "Barangay Ford"],
            ["client_id" => "110", "street" => "1234 Gold", "city" => "Makati", "postal_code" => "1209",
                "province" => "", "barangay" => "Barangay Isuzu"],
            ["client_id" => "111", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "112", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "113", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "114", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "115", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "116", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "117", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "118", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "119", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "120", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "121", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "122", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "123", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "124", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "125", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "126", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "127", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "128", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "129", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "130", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "131", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "132", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "133", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "134", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "135", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "136", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "137", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "138", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "139", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "140", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "141", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "142", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "143", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "144", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "145", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "146", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "147", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "148", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "149", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "150", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "151", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "152", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "153", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "154", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "155", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "156", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "157", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "158", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "159", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "160", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "161", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "162", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "163", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "164", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "165", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "166", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "167", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "168", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "169", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "170", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "171", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "172", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "173", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "174", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "175", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "176", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "177", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "178", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "179", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "180", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "181", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "182", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "183", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "184", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "185", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "186", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "187", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "188", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "189", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "190", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "191", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "192", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "193", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "194", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "195", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "196", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "197", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "198", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "199", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "200", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "201", "street" => "1234 Red", "city" => "Quezon", "postal_code" => "1200",
                "province" => "", "barangay" => "Barangay Nissan"],
            ["client_id" => "202", "street" => "1234 Green", "city" => "Manila", "postal_code" => "1201",
                "province" => "", "barangay" => "Barangay Toyota"],
            ["client_id" => "203", "street" => "1234 Blue", "city" => "Caloocan", "postal_code" => "1202",
                "province" => "", "barangay" => "Barangay Mitsubishi"],
            ["client_id" => "204", "street" => "1234 Yellow", "city" => "Pasay", "postal_code" => "1203",
                "province" => "", "barangay" => "Barangay Honda"],
            ["client_id" => "205", "street" => "1234 Purple", "city" => "Pateros", "postal_code" => "1204",
                "province" => "", "barangay" => "Barangay Ferrari"],
            ["client_id" => "206", "street" => "1234 Brown", "city" => "Antipolo", "postal_code" => "1205",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "207", "street" => "1234 White", "city" => "Pasig", "postal_code" => "1206",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "208", "street" => "1234 Black", "city" => "Taguig", "postal_code" => "1207",
                "province" => "", "barangay" => "Barangay Chevrolet"],
            ["client_id" => "209", "street" => "1234 Silver", "city" => "Cavite", "postal_code" => "1208",
                "province" => "", "barangay" => "Barangay Ford"],
            ["client_id" => "210", "street" => "1234 Gold", "city" => "Makati", "postal_code" => "1209",
                "province" => "", "barangay" => "Barangay Isuzu"],
            ["client_id" => "211", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "212", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "213", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "214", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "215", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "216", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "217", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "218", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "219", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "220", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "221", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "222", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "223", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "224", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "225", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "226", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "227", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "228", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "229", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "230", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "231", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "232", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "233", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "234", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "235", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "236", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "237", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "238", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "239", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "240", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "241", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "242", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "243", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "244", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "245", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "246", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "247", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "248", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "249", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "250", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "251", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "252", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "253", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "254", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "255", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "256", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "257", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "258", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "259", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "260", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "261", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "262", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "263", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "264", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "265", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "266", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "267", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "268", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "269", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "270", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "271", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "272", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "273", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "274", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "275", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "276", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "277", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "278", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "279", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "280", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "281", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "282", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "283", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "284", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "285", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "286", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "287", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "288", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "289", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "290", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "291", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "292", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "293", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "294", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "295", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "296", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "297", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "298", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "299", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "300", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "301", "street" => "1234 Red", "city" => "Quezon", "postal_code" => "1200",
                "province" => "", "barangay" => "Barangay Nissan"],
            ["client_id" => "302", "street" => "1234 Green", "city" => "Manila", "postal_code" => "1201",
                "province" => "", "barangay" => "Barangay Toyota"],
            ["client_id" => "303", "street" => "1234 Blue", "city" => "Caloocan", "postal_code" => "1202",
                "province" => "", "barangay" => "Barangay Mitsubishi"],
            ["client_id" => "304", "street" => "1234 Yellow", "city" => "Pasay", "postal_code" => "1203",
                "province" => "", "barangay" => "Barangay Honda"],
            ["client_id" => "305", "street" => "1234 Purple", "city" => "Pateros", "postal_code" => "1204",
                "province" => "", "barangay" => "Barangay Ferrari"],
            ["client_id" => "306", "street" => "1234 Brown", "city" => "Antipolo", "postal_code" => "1205",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "307", "street" => "1234 White", "city" => "Pasig", "postal_code" => "1206",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "308", "street" => "1234 Black", "city" => "Taguig", "postal_code" => "1207",
                "province" => "", "barangay" => "Barangay Chevrolet"],
            ["client_id" => "309", "street" => "1234 Silver", "city" => "Cavite", "postal_code" => "1208",
                "province" => "", "barangay" => "Barangay Ford"],
            ["client_id" => "310", "street" => "1234 Gold", "city" => "Makati", "postal_code" => "1209",
                "province" => "", "barangay" => "Barangay Isuzu"],
            ["client_id" => "311", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "312", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "313", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "314", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "315", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "316", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "317", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "318", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "319", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "320", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "321", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "322", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "323", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "324", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "325", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "326", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "327", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "328", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "329", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "330", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "331", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "332", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "333", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "334", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "335", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "336", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "337", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "338", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "339", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "340", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "341", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "342", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "343", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "344", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "345", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "346", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "347", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "348", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "349", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "350", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "351", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "352", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "353", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "354", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "355", "street" => "1234 Triangle", "city" => "Marikina", "postal_code" => "1214",
                "province" => "", "barangay" => "Barangay Camia"],
            ["client_id" => "356", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "357", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "358", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "359", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "360", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "361", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "362", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "363", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "364", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "365", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "366", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "367", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "368", "street" => "43 Sapphire", "city" => "Cebu", "postal_code" => "4104",
                "province" => "Cebu", "barangay" => "Barangay Masaya"],
            ["client_id" => "369", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "370", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "371", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "372", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "373", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "374", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            ["client_id" => "375", "street" => "111 Aquamarine", "city" => "Palawan", "postal_code" => "3340",
                "province" => "Palawan", "barangay" => "Barangay Gubat"],
            ["client_id" => "376", "street" => "125 Carlson", "city" => "Zamboanga", "postal_code" => "4403",
                "province" => "Zamboanga", "barangay" => "Barangay Mahacot"],
            ["client_id" => "377", "street" => "133 Gloria Diaz", "city" => "Agusan Del Sur", "postal_code" => "7712",
                "province" => "Agusan Del Sur", "barangay" => "Barangay San Pedro"],
            ["client_id" => "378", "street" => "145 Liwanag", "city" => "Agusan Del Norte", "postal_code" => "6676",
                "province" => "Agusan Del Norte", "barangay" => "Barangay Ilaw"],
            ["client_id" => "379", "street" => "155 Elephant", "city" => "Davao", "postal_code" => "9113",
                "province" => "Davao", "barangay" => "Barangay Durian"],
            ["client_id" => "380", "street" => "168 Bird", "city" => "Legazpi", "postal_code" => "5564",
                "province" => "Legazpi", "barangay" => "Barangay Bulkan"],
            ["client_id" => "381", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "382", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "383", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "384", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "385", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "386", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "387", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "388", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "389", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "390", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "391", "street" => "177 Dolphin", "city" => "Legazpi", "postal_code" => "5563",
                "province" => "Legazpi", "barangay" => "Barangay Mayon"],
            ["client_id" => "392", "street" => "1812 Dog", "city" => "Iloilo", "postal_code" => "4453",
                "province" => "Iloilo", "barangay" => "Barangay Katindig"],
            ["client_id" => "393", "street" => "3210 Koala", "city" => "Bacolod", "postal_code" => "6601",
                "province" => "Bacolod", "barangay" => "Barangay Magiting"],
            ["client_id" => "394", "street" => "4412 Monkey", "city" => "Marawi", "postal_code" => "7261",
                "province" => "Marawi", "barangay" => "Barangay Mabigat"],
            ["client_id" => "395", "street" => "5132 Lizard", "city" => "Magonoy", "postal_code" => "5612",
                "province" => "Magonoy", "barangay" => "Barangay Masinop"],
            ["client_id" => "396", "street" => "6123 Cat", "city" => "Koronadal", "postal_code" => "9412",
                "province" => "Koronadal", "barangay" => "Barangay Korona"],
            ["client_id" => "397", "street" => "7712 Bat", "city" => "Dipolog", "postal_code" => "8812",
                "province" => "Dipolog", "barangay" => "Barangay Valenzuela"],
            ["client_id" => "398", "street" => "8912 Snake", "city" => "Cotabato", "postal_code" => "6520",
                "province" => "Cotabato", "barangay" => "Barangay Rizal"],
            ["client_id" => "399", "street" => "9102 Turtle", "city" => "General Santos", "postal_code" => "8451",
                "province" => "General Santos", "barangay" => "Barangay Tunasan"],
            ["client_id" => "400", "street" => "1293 Pig", "city" => "Tagum", "postal_code" => "8912",
                "province" => "Tagum", "barangay" => "Barangay Makisig"],
            ["client_id" => "401", "street" => "1234 Red", "city" => "Quezon", "postal_code" => "1200",
                "province" => "", "barangay" => "Barangay Nissan"],
            ["client_id" => "402", "street" => "1234 Green", "city" => "Manila", "postal_code" => "1201",
                "province" => "", "barangay" => "Barangay Toyota"],
            ["client_id" => "403", "street" => "1234 Blue", "city" => "Caloocan", "postal_code" => "1202",
                "province" => "", "barangay" => "Barangay Mitsubishi"],
            ["client_id" => "404", "street" => "1234 Yellow", "city" => "Pasay", "postal_code" => "1203",
                "province" => "", "barangay" => "Barangay Honda"],
            ["client_id" => "405", "street" => "1234 Purple", "city" => "Pateros", "postal_code" => "1204",
                "province" => "", "barangay" => "Barangay Ferrari"],
            ["client_id" => "406", "street" => "1234 Brown", "city" => "Antipolo", "postal_code" => "1205",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "407", "street" => "1234 White", "city" => "Pasig", "postal_code" => "1206",
                "province" => "", "barangay" => "Barangay Porsche"],
            ["client_id" => "408", "street" => "1234 Black", "city" => "Taguig", "postal_code" => "1207",
                "province" => "", "barangay" => "Barangay Chevrolet"],
            ["client_id" => "409", "street" => "1234 Silver", "city" => "Cavite", "postal_code" => "1208",
                "province" => "", "barangay" => "Barangay Ford"],
            ["client_id" => "410", "street" => "1234 Gold", "city" => "Makati", "postal_code" => "1209",
                "province" => "", "barangay" => "Barangay Isuzu"],
            ["client_id" => "411", "street" => "1234 Fuchsia", "city" => "Las Piñas", "postal_code" => "1210",
                "province" => "", "barangay" => "Barangay Mini"],
            ["client_id" => "412", "street" => "1234 Crimson", "city" => "Paranaque", "postal_code" => "1211",
                "province" => "", "barangay" => "Barangay Hummer"],
            ["client_id" => "413", "street" => "1234 Square", "city" => "Malabon", "postal_code" => "1212",
                "province" => "", "barangay" => "Barangay Rosal"],
            ["client_id" => "414", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "415", "street" => "1234 Octagon", "city" => "Mandaluyong", "postal_code" => "1213",
                "province" => "", "barangay" => "Barangay Sampaguita"],
            ["client_id" => "416", "street" => "1234 Circle", "city" => "San Juan", "postal_code" => "1215",
                "province" => "", "barangay" => "Barangay Ilang-Ilang"],
            ["client_id" => "417", "street" => "1234 Rectangle", "city" => "Trece Martires", "postal_code" => "1216",
                "province" => "", "barangay" => "Barangay Gumamela"],
            ["client_id" => "418", "street" => "1234 Oval", "city" => "Muntinlupa", "postal_code" => "1217",
                "province" => "", "barangay" => "Barangay Santan"],
            ["client_id" => "419", "street" => "1234 Pentagon", "city" => "Navotas", "postal_code" => "1218",
                "province" => "", "barangay" => "Barangay Magnolia"],
            ["client_id" => "420", "street" => "1234 Diamond", "city" => "Valenzuela", "postal_code" => "1219",
                "province" => "", "barangay" => "Barangay Daisy"],
            ["client_id" => "421", "street" => "1234 Heart", "city" => "Batangas", "postal_code" => "1220",
                "province" => "", "barangay" => "Barangay Lily"],
            ["client_id" => "422", "street" => "1234 Hexagon", "city" => "Bacoor", "postal_code" => "1221",
                "province" => "", "barangay" => "Barangay Cosmos"],
            ["client_id" => "423", "street" => "1234 Hectagon", "city" => "Dasmariñas", "postal_code" => "1222",
                "province" => "", "barangay" => "Barangay Poinsettia"],
            ["client_id" => "424", "street" => "1234 Cube", "city" => "Imus", "postal_code" => "1223",
                "province" => "", "barangay" => "Barangay Gladiola"],
            ["client_id" => "425", "street" => "1234 Nonagon", "city" => "Tagaytay", "postal_code" => "1224",
                "province" => "", "barangay" => "Barangay Chrysanthemum"],
            ["client_id" => "426", "street" => "12 Diamond", "city" => "Masbate", "postal_code" => "3486",
                "province" => "Masbate", "barangay" => "Barangay Kaunlaran"],
            ["client_id" => "427", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "428", "street" => "20 Topaz", "city" => "Leyte", "postal_code" => "2103",
                "province" => "Leyte", "barangay" => "Barangay Isulong"],
            ["client_id" => "429", "street" => "54 Ruby", "city" => "Bohol", "postal_code" => "7089",
                "province" => "Bohol", "barangay" => "Barangay Sigasig"],
            ["client_id" => "430", "street" => "66 Pearl", "city" => "Romblon", "postal_code" => "3423",
                "province" => "Romblon", "barangay" => "Barangay Kumpleto"],
            ["client_id" => "431", "street" => "78 Jade", "city" => "Aklan", "postal_code" => "4312",
                "province" => "Aklan", "barangay" => "Barangay Boracay"],
            ["client_id" => "432", "street" => "82 Ivory", "city" => "Samar", "postal_code" => "4059",
                "province" => "Samar", "barangay" => "Barangay Maginhawa"],
            ["client_id" => "433", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "434", "street" => "99 Emerald", "city" => "Sorsogon", "postal_code" => "5502",
                "province" => "Sorsogon", "barangay" => "Barangay Ngiti"],
            ["client_id" => "435", "street" => "103 Amethyst", "city" => "Bulacan", "postal_code" => "1132",
                "province" => "Bulacan", "barangay" => "Barangay Malolos"],
            
        );

        // Uncomment the below to run the seeder
        DB::table('client_addresses')->insert($client_addresses);
    }

}
