<?php

class Complaint_type_tagsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('complaint_type_tags')->truncate();

        $complaint_type_tags = array(
            ["complaint_id" => 1, "type" => "Theft"],
            ["complaint_id" => 2, "type" => "Rape"],
            ["complaint_id" => 2, "type" => "Grave threats"],
            ["complaint_id" => 3, "type" => "Uncategorized"],
            ["complaint_id" => 4, "type" => "Prostitution"],
            ["complaint_id" => 5, "type" => "Murder"],
            ["complaint_id" => 6, "type" => "Homicide"],
            ["complaint_id" => 7, "type" => "Suicide"],
            ["complaint_id" => 8, "type" => "Murder"],
            ["complaint_id" => 8, "type" => "Serious physical injuries"],
            ["complaint_id" => 9, "type" => "Parricide"],
            ["complaint_id" => 9, "type" => "Infanticide"],
            ["complaint_id" => 10, "type" => "Gambling and Betting"],
            ["complaint_id" => 11, "type" => "Murder"],
            ["complaint_id" => 12, "type" => "Counterfeiting"],
            ["complaint_id" => 13, "type" => "Abduction"],
            ["complaint_id" => 14, "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 15, "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 16, "type" => "Fraud"],
            ["complaint_id" => 17, "type" => "Homicide"],
            ["complaint_id" => 18, "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 19, "type" => "Rape"],
            ["complaint_id" => 20, "type" => "Homicide"],
            ["complaint_id" => 21, "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 22, "type" => "Murder"],
            ["complaint_id" => 23, "type" => "Homicide"],
            ["complaint_id" => 24, "type" => "Homicide"],
            ["complaint_id" => 24, "type" => "Robbery"],
            ["complaint_id" => 25, "type" => "Suicide"],
            ["complaint_id" => 25, "type" => "Vandalism"],
            ["complaint_id" => 26, "type" => "Rape"],
            ["complaint_id" => 27, "type" => "Prostitution"],
            ["complaint_id" => 28, "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 29, "type" => "Rape"],
            ["complaint_id" => 30, "type" => "Counterfeiting"],
            ["complaint_id" => 31, "type" => "Murder"],
            ["complaint_id" => 32, "type" => "Fraud"],
            ["complaint_id" => 33, "type" => "Falsification"],
            ["complaint_id" => 34, "type" => "Fraud"],
            ["complaint_id" => 35, "type" => "Fraud"],
            ["complaint_id" => 35, "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 36, "type" => "Fraud"],
            ["complaint_id" => 37, "type" => "Robbery"],
            ["complaint_id" => 37, "type" => "Brigandage"],
            ["complaint_id" => 38, "type" => "Murder"],
            ["complaint_id" => 39, "type" => "Arson"],
            ["complaint_id" => 40, "type" => "Brigandage"],
            ["complaint_id" => 41, "type" => "Mutilation"],
            ["complaint_id" => 42, "type" => "Serious physical injuries"],
            ["complaint_id" => 43, "type" => "Abduction"],
            ["complaint_id" => 44, "type" => "Rape"],
            ["complaint_id" => 45, "type" => "Slavery"],
            ["complaint_id" => 46, "type" => "Abandonment of helpless persons"],
            ["complaint_id" => 47, "type" => "Prostitution"],
            ["complaint_id" => 48, "type" => "Trespassing"],
            ["complaint_id" => 49, "type" => "Murder"],
            ["complaint_id" => 50, "type" => "Abuses against chastity"],
            ["complaint_id" => 51, "type" => "Slavery"],
            ["complaint_id" => 52, "type" => "Brigandage"],
            ["complaint_id" => 53, "type" => "Brigandage"],
            ["complaint_id" => 54, "type" => "Theft"],
            ["complaint_id" => 55, "type" => "Swindling"],
            ["complaint_id" => 56, "type" => "Arson"],
            ["complaint_id" => 57, "type" => "Rape"],
            ["complaint_id" => 58, "type" => "Rape"],
            ["complaint_id" => 59, "type" => "Bribery"],
            ["complaint_id" => 60, "type" => "Abduction"],
            ["complaint_id" => 61, "type" => "Abortion"],
            ["complaint_id" => 62, "type" => "Murder"],
            ["complaint_id" => 63, "type" => "Rape"],
            ["complaint_id" => 64, "type" => "Theft"],
            ["complaint_id" => 65, "type" => "Murder"],
            ["complaint_id" => 66, "type" => "Murder"],
            ["complaint_id" => 67, "type" => "Murder"],
            ["complaint_id" => 68, "type" => "Murder"],
            ["complaint_id" => 69, "type" => "Robbery"],
            ["complaint_id" => 70, "type" => "Libel"],
            ["complaint_id" => 71, "type" => "Arson"],
            ["complaint_id" => 72, "type" => "Slander"],
            ["complaint_id" => 73, "type" => "Libel"],
            ["complaint_id" => 74, "type" => "Brigandage"],
            ["complaint_id" => 74, "type" => "Robbery"],
            ["complaint_id" => 75, "type" => "Rape"],
            ["complaint_id" => 76, "type" => "Adultery"],
            ["complaint_id" => 77, "type" => "Murder"],
            ["complaint_id" => 77, "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 78, "type" => "Counterfeiting"],
            ["complaint_id" => 79, "type" => "Counterfeiting"],
            ["complaint_id" => 80, "type" => "Kidnapping"],
            ["complaint_id" => 81, "type" => "Forgery"],
            ["complaint_id" => 82, "type" => "Gambling"],
            ["complaint_id" => 82, "type" => "Kidnapping"],
            ["complaint_id" => 83, "type" => "Sexual Abuse"],
            ["complaint_id" => 84, "type" => "Grave Scandal"],
            ["complaint_id" => 84, "type" => "Rape"],
            ["complaint_id" => 85, "type" => "Public Disorder"],
            ["complaint_id" => 86, "type" => "Direct Assault"],
            ["complaint_id" => 87, "type" => "Forgery"],
            ["complaint_id" => 88, "type" => "Bribery"],
            ["complaint_id" => 89, "type" => "Prohibited Transaction"],
            ["complaint_id" => 90, "type" => "Infidelity"],
            ["complaint_id" => 91, "type" => "Disobedience"],
            ["complaint_id" => 92, "type" => "Relevance of Secret"],
            ["complaint_id" => 93, "type" => "Maltreatment of Prisoner"],
            ["complaint_id" => 93, "type" => "Sexual Abuse"],
            ["complaint_id" => 94, "type" => "Usurpation"],
            ["complaint_id" => 95, "type" => "Suicide"],
            ["complaint_id" => 96, "type" => "Abortion"],
            ["complaint_id" => 97, "type" => "Infanticide"],
            ["complaint_id" => 98, "type" => "Serious Illegal Detention"],
            ["complaint_id" => 98, "type" => "Plunder"],
            ["complaint_id" => 99, "type" => "Kidnapping"],
            ["complaint_id" => 100, "type" => "Slavery"],
            ["complaint_id" => 101, "type" => "Drunk Driving"],
            ["complaint_id" => 102, "type" => "Possession of Dangerous Drugs"],
            ["complaint_id" => 102, "type" => "Suicide"],
            ["complaint_id" => 103, "type" => "Vandalism"],
            ["complaint_id" => 104, "type" => "Robbery"],
            ["complaint_id" => 105, "type" => "Treason"],
            ["complaint_id" => 106, "type" => "Espionage"],
            ["complaint_id" => 107, "type" => "Robbery"],
            ["complaint_id" => 108, "type" => "Rape"],
            ["complaint_id" => 108, "type" => "Sexual Abuse"],
            ["complaint_id" => 109, "type" => "Domestic Violence"],
            ["complaint_id" => 110, "type" => "Petty Theft"],
            ["complaint_id" => 111, "type" => "Arbitrary Detention"],
            ["complaint_id" => 112, "type" => "Expulsion"],
            ["complaint_id" => 113, "type" => "Violation of Domicile"],
            ["complaint_id" => 114, "type" => "Prohibition, interruption, and dissolution of peaceful meetings"],
            ["complaint_id" => 115, "type" => "Rebellion"],
            ["complaint_id" => 115, "type" => "Disobedience"],
            ["complaint_id" => 116, "type" => "Disloyalty"],
            ["complaint_id" => 117, "type" => "Disturbance of Proceedings"],
            ["complaint_id" => 118, "type" => "Illegal Assemblies"],
            ["complaint_id" => 119, "type" => "Direct Assault"],
            ["complaint_id" => 119, "type" => "Slavery"],
            ["complaint_id" => 120, "type" => "Direct Assault"],
            ["complaint_id" => 121, "type" => "Public Disorder"],
            ["complaint_id" => 122, "type" => "Forgery"],
            ["complaint_id" => 123, "type" => "Falsification"],
            ["complaint_id" => 123, "type" => "Forgery"],
            ["complaint_id" => 124, "type" => "Fraud"],
            ["complaint_id" => 125, "type" => "Dereliction of Duty"],
            ["complaint_id" => 126, "type" => "Bribery"],
            ["complaint_id" => 127, "type" => "Prohibited Transaction"],
            ["complaint_id" => 127, "type" => "Possession of Dangerous Drugs"],
            ["complaint_id" => 128, "type" => "Infidelity"],
            ["complaint_id" => 129, "type" => "Disobedience"],
            ["complaint_id" => 130, "type" => "Forgery"],
        );

        // Uncomment the below to run the seeder
        DB::table('complaint_type_tags')->insert($complaint_type_tags);
    }

}
