<?php

class ComplaintsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
         DB::table('complaints')->truncate();

        $complaints = array(
            
            //1
            ["date_commited" => "2014-02-10", "date_reported" => "2014-02-12", 
                "narration" => "Funds worth Php 100,000 which covers Marikina High School's miscellaneous fees and operating costs for the whole year have been stolen by a Canadian exchange student named Justin Bieber. Elizabeth Aguas, principal of the said school, keeps the funds in her vault. Bieber, who has been Aguas' personal student assistant, is suspected to be the robber and has not reported to school since the day of the incident. According to Aguas, she allowed him entry into her office and took hold of the keys to her vault. Bieber left his belongings inside the office that day and left her a note that he 'hates working for her'.", 
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The funds have been stolen, and the complainant is a concerned niece for her aunt Elizabeth.", 
                "img_signature" =>"1.jpg", "img_right_thumb" =>"1.jpg"],
            //2
            ["date_commited" => "2014-01-22", "date_reported" => "2014-02-10", 
                "narration" => "Maria Aguilar claims that Chris Brown forced her to perform oral sex on him and tried to insert his penis in her vagina on January 22, the night the group of businessman Cedric Lee allegedly came to her rescue. Brown denied this, saying he was set up by Aguilar for an extortion attempt allegedly led by Lee. The doctor said he was blindfolded, tied up and attacked by at least six men inside Aguilar’s condominium unit in Taguig.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The victim has been feeling uncomfortable from the day of the incident.", 
                "img_signature" =>"2.jpg", "img_right_thumb" =>"2.jpg"],
            //3
            ["date_commited" => "2014-02-10", "date_reported" => "2014-02-12", 
                "narration" => "Logan Alpay  and Natalie Domingo fought about cup noodles. Alpay happened to pass on a cafe asking the Domingo, lady vendor how much the noodles are and she said 'We are only selling breads here, sir.' Alpay continued saying bad words about the lady and he finally ordered a bulalo. Domingo said that they are only selling cup noodles, so she served the cup noodles. Alpay began complaining about the cup noodles because he said that he ordered a Bulalo which the shop doesn't serve. The fight grew big and another man tried to stop Alpay and they fought each other. Finally, the man got beat and began telling the man who beat him that he should leave him alone.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"3.jpg", "img_right_thumb" =>"3.jpg"],
            //4
            ["date_commited" => "2009-03-01", "date_reported" => "2009-03-09", 
                "narration" => "Waitresses Kris Aquino and Claire Baclayan have been charged with misdemeanor prostitution after Logan Alpay alleged they agreed to perform sexual acts in exchange for money. After receiving community complaints, Alpay visited the bar and approached them. It has been proven that an agreement was made to perform a sex act in exchange for money.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "Logan Alpay got bankrupt after testing his plan out and wanted the women to return his money.", 
                "img_signature" =>"4.jpg", "img_right_thumb" =>"4.jpg"],
            //5
            ["date_commited" => "2013-04-14", "date_reported" => "2013-04-18", 
                "narration" => "Engineer Penelope Balata was stabbed in the heart multiple times at 6am on April 14 by a garbage collector named Mike Jones in the area of Quezon City after an argument inside a Northwest apartment. Jones was charged with first degree murder in the death of Balata. The victim was found stabbed to death shortly before 7 p.m. April 15 inside an apartment in the 3600 block of Seven Mile Lane in Quezon. The complainant claims Jones stabbed Balata multiple times.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The complainant is Balata's cousin and she grieves for her family's loss.", 
                "img_signature" =>"5.jpg", "img_right_thumb" =>"5.jpg"],
            //6
            ["date_commited" => "2013-12-26", "date_reported" => "2013-01-02", 
                "narration" => "2 engineers and 1 principal were shot dead during a shootout in Surigao at around 9pm yesterday. Their bodies are seriously wounded with the principal’s head shattered and tattered limbs for the engineers. Suspects are believed to be two men from Cotabato City, who mistakenly left their firearms and name tags along the way.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"6.jpg", "img_right_thumb" =>"6.jpg"],
            //7
            ["date_commited" => "2013-01-02", "date_reported" => "2013-01-11", 
                "narration" => "Raymond Cadang, a college student from FEU allegedly leapt from the 25th floor of Red Condominum in U-belt at around 1:30am because of not being able to maintain his scholarship. Cadang has also been reported by his schoolmate to be failing in his classes because of financial problems. Therefore, he committed suicide.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The complainant is concerned about the victim and is also experiencing the terrible loss of her nephew.", 
                "img_signature" =>"7.jpg", "img_right_thumb" =>"7.jpg"],
            //8
            ["date_commited" => "2013-01-23", "date_reported" => "2013-01-29", 
                "narration" => "Assistant lecturer from De La Salle University found at Agno gate at 6am yesterday was reported to have been stabbed in the head multiple times by a Korean. Sources say she owed the Korean money and she refused to give in to his offers of intimacy. After smoking at the back of EGI around 2am yesterday, a student heard him say so and he also heard cries of a woman but he hurriedly went back to his condo.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "Justice for the DLSU professor.", 
                "img_signature" =>"8.jpg", "img_right_thumb" =>"8.jpg"],
            //9
            ["date_commited" => "2013-02-14", "date_reported" => "2013-02-27", 
                "narration" => "Upon eating two of her sons because of hunger and temptation, Kristina Gacutan suffered intense pain, shivering and epilepsy. She was found dead after her door has been busted open. Their neighbors reported to have seen the incident from her window and tried to stop Gacutan from doing so but she had already locked up her house and gave them threats. Gacutan was allegedly suffering from depression and anxiety disorder, which might have triggered the urge to eat her children.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The complainant is suffering from a post-traumatic attack and is scarred for the rest of her life.", 
                "img_signature" =>"9.jpg", "img_right_thumb" =>"9.jpg"],
            //10
            ["date_commited" => "2013-01-25", "date_reported" => "2013-02-03", 
                "narration" => "3 Americans have allegedly been participating in an illegal association involving gambling, betting and drugs in San Juan City. The course held no league activity for two weeks after the announcement. The gang has since started to play again under the condition they do not have entry fees designed to reward winners with a pot at the end of play. But, these have been going on for months now and the barangay captain is complaining about the noise and drugs wrappers found scattered around the community.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "Drug dealing is illegal and the complainant is a concerned citizen for their community.", 
                "img_signature" =>"10.jpg", "img_right_thumb" =>"10.jpg"],
            //11
            ["date_commited" => "2013-02-27", "date_reported" => "2013-03-03", 
                "narration" => "Bus conductor from Leyte plotted a plan against his friends during a trip to the farm where they were supposed to tend to some of their crops, according to one of the victims who survived. The suspect is reported to have brain damage, but they did not think he would do that. He told his bus driver friend to stop the bus because he needed to pee somewhere so he got off the bus, but the next thing they knew, they heard a loud explosion and things fell apart.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The bus conductor has to be stopped.", 
                "img_signature" =>"11.jpg", "img_right_thumb" =>"11.jpg"],
            //12
            ["date_commited" => "2013-01-02", "date_reported" => "2013-03-20", 
                "narration" => "2 businessmen and 1 house husband were found to be makers of custom coins who were found guilty of counterfeiting charges for minting and distributing a form of private money called the Liberty Dollar in XYZ company: Christopher Sese, Gong Wai See and Karlo Martinez. The trio claims that the money was a private voluntary currency for those conducting business outside the government's purview and was not meant to be used as legal tender.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"12.jpg", "img_right_thumb" =>"12.jpg"],
            //13
            ["date_commited" => "2013-01-05", "date_reported" => "2013-04-01", 
                "narration" => "Businessman from China abducted 5 children, 2 of which were American to slave them for his selfish purposes. He would pick up the kids from school pretending to buy them something nice and afterwards kidnaps them. A witness said he recognizes his face around because he frequents visiting this school when it is dismissal time.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"13.jpg", "img_right_thumb" =>"13.jpg"],
            //14
            ["date_commited" => "2013-03-10", "date_reported" => "2013-04-01", 
                "narration" => "2 drug dealers have been found to be dealing marijuana in Benguet on Thursday and have been disguising themselves as garbage collectors in order to hand out the drugs.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"14.jpg", "img_right_thumb" =>"14.jpg"],
            //15
            ["date_commited" => "2013-04-18", "date_reported" => "2013-04-20", 
                "narration" => "Top drug lord in possession of shabu has been spotted in a lab in Taguig getting high. The drug was everywhere from the tables to the floors and he laid there on center of the room laughing and holding a few of them while talking to himself.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"15.jpg", "img_right_thumb" =>"15.jpg"],
            //16
            ["date_commited" => "2013-01-10", "date_reported" => "2013-04-12", 
                "narration" => "Serendra developers were convicted of laundering thousands of dollars from a state grant for a job-training program in Serendra. The developers, which are close friends of the victim, took as much as $11,000 from checks worth more than $30,000,000 that were supposed to be for work related to the grant. About $20,000 was deposited back into accounts controlled by the victim.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"16.jpg", "img_right_thumb" =>"16.jpg"],
            //17
            ["date_commited" => "2013-04-30", "date_reported" => "2013-05-12", 
                "narration" => "A gym instructor was jogging at 4am in the morning when he was shot by a stray bullet, puncturing his head in the process. The suspect is believed to be a janitor named Miguel Camiguin in the gym that the instructor has been working at. He has been suspected of multiple attempts to kill Camiguin.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"17.jpg", "img_right_thumb" =>"17.jpg"],
            //18
            ["date_commited" => "2013-05-03", "date_reported" => "2013-05-20", 
                "narration" => "A known drug pusher has been found dead in Caloocan City after convincing 2 women to take drugs from him. The women, as a defense mechanism, attacked him which led to him bumping his head on a metal tube. The women gained a few scratches in the head and bruises on their limbs.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"18.jpg", "img_right_thumb" =>"18.jpg"],
            //19
            ["date_commited" => "2013-03-29", "date_reported" => "2013-04-10", 
                "narration" => "Rape victim advocates hope a guilty verdict in the case of a man charged with sexually assaulting eight women in the past. Pinay has been allegedly coerced by her boyfriend to have sex with her but she resisted. He instead held it against her and raped her, even threatening her. She knew of his sexual relations in the past, but only now did she take action about this matter when it happened to her.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"19.jpg", "img_right_thumb" =>"19.jpg"],
            //20
            ["date_commited" => "2013-05-01", "date_reported" => "2013-05-20", 
                "narration" => "In a shooting range arena in Manila, four friends have been enjoying a peaceful afternoon practicing when one of their friends accidentally fired the trigger at three of them. The accused, Veronica Co is a medical technologist who shot her co-medical technologists and a therapist unknowingly. She attempted to escape the area after doing so because she couldn’t believe what she did, broke down really bad, and did not know what to do.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"20.jpg", "img_right_thumb" =>"20.jpg"],
            //21
            ["date_commited" => "2013-07-02", "date_reported" => "2013-07-07", 
                "narration" => "Top druglord of Zamboanga, Sylvia Ang, has been released from jail and is probably starting to wreak havoc in the streets of Manila once again. Concerned citizens have been frightened about her return as her drug dealings always lead to murder.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"21.jpg", "img_right_thumb" =>"21.jpg"],
            //22
            ["date_commited" => "2013-01-15", "date_reported" => "2013-04-22", 
                "narration" => "Michael Gonzales, a paramedic, was stabbed by a woman named Mariz Tamboa while taking a leak on the roadside of Makati City. He was taking a break from is shift when Tamboa stabbed him from his behind. He died on arrival to the hospital. Tamboa has been found out to be related to him in the past, one of his ex-girlfriends.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"22.jpg", "img_right_thumb" =>"22.jpg"],
            //23
            ["date_commited" => "2013-06-28", "date_reported" => "2013-07-12", 
                "narration" => "Drunk driver Monica Velasco shot a bypasser jogging on the roadside for unknown reasons. The victim is identified to be a student named Celine Bacaycay, who was believed to be working out in the wee hours of the morning, around 5:30am.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"23.jpg", "img_right_thumb" =>"23.jpg"],
            //24
            ["date_commited" => "2013-09-24", "date_reported" => "2013-09-22", 
                "narration" => "5 robbers threatened the staff of Security Bank in Alabang, stuffed a four-figure sum of money into an orange Tesco bag and were then driven away in the a taxi cab which they had arrived. They were all wearing a black beanie hat, a dark waist-length jacket and brown trousers.  Two tellers of the said bank, Isabel Balana and Scott Balisacan, were shot when the robbers entered. The suspects are identified to be Paulo Arcilla, Samson Sanqui, Christian Tiangco, Gabriel Lantin and Leonardo Liamzon, 4 of which are unemployed and one, a nurse.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"24.jpg", "img_right_thumb" =>"24.jpg"],
            //25
            ["date_commited" => "2013-08-10", "date_reported" => "2013-08-12", 
                "narration" => "Jack Baloaloa, an architect, committed suicide after being reported to have vandalized in Pasay City. Colleagues say his floor plans failed, so that must have caused him to commit the act. He was on the verge of getting fired from work as well.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"25.jpg", "img_right_thumb" =>"25.jpg"],
            //26
            ["date_commited" => "2013-09-07", "date_reported" => "2013-09-09", 
                "narration" => "Richmond Collins, an American accountant, came up to Clarissa Mae Caganap and asked how she was doing, came across all nice and concerned about her. They talked for an hour or so, and then he offered to give her a lift home. Caganap was still messed up in the head about her ex-boyfriend leaving so she said yes. They started in the right direction, but then Collins took a wrong turn and forced her into his boarding house in Manila – he raped her in his room, and it was disgusting according to her. She kept pushing him and telling him to leave her alone but he wouldn’t. Then Collins drove her home. She couldn’t believe it, as if nothing had happened. She was numb and got into her flat and just cried. It was really late when the incident happened, around 3:30am already.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"26.jpg", "img_right_thumb" =>"26.jpg"],
            //27
            ["date_commited" => "2013-10-20", "date_reported" => "2013-10-22", 
                "narration" => "Professors Tyrone Tecson, Eun Hyuk Park and Bert Lee from De La Salle University have been reported to be prostitutes giving their service to clients in pubs at Pedro Gil. Two accountants, Claudine Calalang and Marcella Diwa and one student, Jackie Calalo were able to identify them as one of them is a DLSU student. All three were victimized by seduction by the three professors.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"27.jpg", "img_right_thumb" =>"27.jpg"],
            //28
            ["date_commited" => "2013-10-20", "date_reported" => "2013-10-28", 
                "narration" => "2 Korean students named Sungyeol Choi and Myungsoo Choi were caught to have been dealing drugs to high school students illegally at one of their hideout sites in Quezon City. The Chois are twins and have been known to be drug pushers in Korea.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"28.jpg", "img_right_thumb" =>"28.jpg"],
            //29
            ["date_commited" => "2013-10-12", "date_reported" => "2013-11-12", 
                "narration" => "Shania Dolap, niece of Gary Michael Waters has been raped by her own uncle on her birthday. Waters was on vacation and visited the family. During her party in their home, Waters forced himself on the girl and she has had nightmares ever since. Her family took action and kicked Waters out of their home for good upon knowing of the incident.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"29.jpg", "img_right_thumb" =>"29.jpg"],
            //30
            ["date_commited" => "2013-11-01", "date_reported" => "2013-11-20", 
                "narration" => "African-American businessmen, Johnson Smith and Simon Davis have been providing shops fake cellular phones and mobile phone equipment. The contents include Fujitsu-branded phone chargers and other accessories through to the newest smartphones from Samsung, Sony and Microsoft. Many are suspected of being fake and are subjected to detailed examination by representatives of the brands who have joined the raid. Danica Dahlia Gonong, a student, has been one of the owners of the shops and has been victimized for the first time by these businessmen.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"30.jpg", "img_right_thumb" =>"30.jpg"],
            //31
            ["date_commited" => "2012-12-18", "date_reported" => "2012-12-28", 
                "narration" => "Gino Haparam, a DLSU student, was shot dead while running away from gunmen outside EGI apartment in Manila. One of the gunmen and considered as a suspect is Sean William Parker, an American butcher. The shooting occurred at about 2:40am when he just returned from drinking in Sherwood place.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"31.jpg", "img_right_thumb" =>"31.jpg"],
            //32
            ["date_commited" => "2013-06-08", "date_reported" => "2013-07-01", 
                "narration" => "Butcher, Mark Anthony Collins and Fireman, Jacob Reed have been indicted on fraud charges for allegedly failing to disclose to a research company owned by Jasper Ilog where they applied for overlapping grants totaling $1.2 million from two different federal agencies.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"32.jpg", "img_right_thumb" =>"32.jpg"],
            //33
            ["date_commited" => "2013-12-03", "date_reported" => "2013-01-10", 
                "narration" => "American fireman named Matthew Morgan has been accused of using a phony contractor's license and fraudulent use of funds. Sources say he took people's money, but didn't complete the work. He was originally sentenced in 2008 on similar charges in the US, but they say he continued the same scheme after his release from jail.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"33.jpg", "img_right_thumb" =>"33.jpg"],
            //34
            ["date_commited" => "2012-01-10", "date_reported" => "2012-02-01", 
                "narration" => "American manager, Liam Morgan from Maryland is to be sentenced in court to 12 years in prison for defrauding Filipino businessman Duane Kalilo by telling him and his subordinates to stop paying their mortgages.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"34.jpg", "img_right_thumb" =>"34.jpg"],
            //35
            ["date_commited" => "2014-02-10", "date_reported" => "2014-03-02", 
                "narration" => "An alleged attempt to use fraudulent gift cards of Jackson Kelly in a supermarket led to a bizarre escapade of drug dealing and counterfeiting more gift certificates from establishments such as Starbucks. Kelly victimized a businessman named Duke Labao and was able to acquire his credit cards.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"35.jpg", "img_right_thumb" =>"35.jpg"],
            //36
            ["date_commited" => "2014-01-20", "date_reported" => "2014-01-25", 
                "narration" => "Ed Lico said that he’s the victim of a multi-billion dollar fraud at the hands of an American businessman named Ryan Dylan Wood known as Giraffe when his company bought it last year and lied about its finances. Lico said executives at Autonomy Corporation PLC, Wood’s company, willfully boosted the company's figures through various accounting tricks, which convinced him to pay $9.7 billion for the company.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The victim has been threatened and is trying to cope with the trauma.", 
                "img_signature" =>"36.jpg", "img_right_thumb" =>"36.jpg"],
            //37
            ["date_commited" => "2014-03-09", "date_reported" => "2014-03-17", 
                "narration" => "2 masked men armed with guns walked through an open ceiling vent at RCBC in Quezon City after threatening Enrique Macalino, a welder working on the renovation of the office after work hours at around 10pm. The men allegedly went straight to the cash box and made off with an undisclosed amount of money. They have been identified later on as Ryan Hayes, an Australian taxi driver, and Joseph Sullivan, a translator, reported to be using their foreign identities every now and then as inquirers for the bank, thus they might have found their way in.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"37.jpg", "img_right_thumb" =>"37.jpg"],
            //38
            ["date_commited" => "2013-05-18", "date_reported" => "2013-05-26", 
                "narration" => "Landon Jordan, an Australian politician has been charged with multiple counts in the road rage shooting death of a female nurse named Kris Magbuhat. Jordan followed her into a gated apartment complex which is reported to be Magbuhat’s policeman uncle’s where he shot her to death.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"38.jpg", "img_right_thumb" =>"38.jpg"],
            //39
            ["date_commited" => "2013-01-15", "date_reported" => "2013-01-27", 
                "narration" => "Jack Marshall, an Australian politician has been reported to set an elementary school teacher’s house on fire. The elementary school teacher who is Ailee Jane Magtanggol suffered third degree burns which later resulted to her death.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"39.jpg", "img_right_thumb" =>"39.jpg"],
            //40
            ["date_commited" => "2013-07-10", "date_reported" => "2013-07-13", 
                "narration" => "Connor Charles Hunter, an Australian pilot, has been accused of robbing an IT professional named Michael James Maramba in a supermarket in Sta. Mesa. Customers buying were forced to the ground in Hunter’s attempt to get to Maramba. Hunter got away after the incident and Maramba says he owed him some money.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"40.jpg", "img_right_thumb" =>"40.jpg"],
            //41
            ["date_commited" => "2013-04-04", "date_reported" => "2013-04-18", 
                "narration" => "Clarice Ona, a student from San Beda had her clitoris was removed and had no idea what was about to happen to her. The alleged suspect is a Chinese Newsreader named Lay Zhang. Ona claims that they got into his car, thinking they’d do a run through of the school newspaper. They started driving and ended up in a bush instead, she said. Zhang came at her with a knife, one of those knives that hasn't seen water or anything good for a while. He led her to a room and the next thing she knew he was pinning her down. Ona didn't know what was planned but then Zhang took hold of her clitoris and started cutting it inch by inch while holding her down.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"41.jpg", "img_right_thumb" =>"41.jpg"],
            //42
            ["date_commited" => "2014-12-28", "date_reported" => "2013-01-02", 
                "narration" => "Hannah Wu, a housewife was battered by his husband Yi Wu, better known as Kris. After being stabbed and chopped more than 10 times about the body, Hannah says she is prepared to leave her husband of 14 years and hopes that he is jailed for his actions. Hannah was allegedly attacked by the man on after yet another domestic brawl. When this newspaper visited her in hospital yesterday her hair was visibly still blood soaked. She hugged her elderly mother who had also come to visit her. Her face bore a long chop wound and even though it was surgically closed, blood was still oozing from the wound. Her face was swollen fat and her eyes were blood shot, clear signs of the beating she received.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"42.jpg", "img_right_thumb" =>"42.jpg"],
            //43
            ["date_commited" => "2013-01-02", "date_reported" => "2013-01-11", 
                "narration" => "Ming Chiu, a Chinese plumber has been charged of kidnapping and enslaving a 10-year-old boy named Salvador Felipe. According to Felipe, he was left with his legs and arms tied for three days (after the criminal incidents) until he managed to untie himself.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"43.jpg", "img_right_thumb" =>"43.jpg"],
            //44
            ["date_commited" => "2013-01-20", "date_reported" => "2013-01-29", 
                "narration" => "Ming Chiu, a Chinese plumber has been charged of raping Jana Hogay, a business student. Hogay was consulting Chiu for her thesis about the economy when he started to do things to help her get comfortable. Then one time he just started to have sex with her without her consent, said Hogay. She cried out for him to stop but he kept going and she felt ashamed that she didn’t feel comfortable about sex. She also felt angry that he didn’t stop when she asked him to.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"44.jpg", "img_right_thumb" =>"44.jpg"],
            //45
            ["date_commited" => "2012-01-29", "date_reported" => "2012-02-03", 
                "narration" => "Jasper Hans Chua was one of the kids abducted by Chinese photographer Bing Ng. Ng would make him pose for him during photo shoots and sometimes made him his personal assistant. Chua slept on the floor and woke up at 5 each morning to clean the house, fetch water and wash dishes. He says he was beaten daily with electrical cords. Chua was allowed no contact with her family. Once, he says, he tried to run away but was caught and beaten. At school, he often cried, and he had scars on his arms and legs from beatings.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"45.jpg", "img_right_thumb" =>"45.jpg"],
            //46
            ["date_commited" => "2013-02-10", "date_reported" => "2013-02-27", 
                "narration" => "Paul Palabay, a librarian was suffering from an attack in near Pasig river when the not so good Samaritan Chuan Tsui, a Chinese newsreader, abandoned him to die. A witness has identified Tsui to have been linked to Palabay as he copyreads some articles in Palabay’s library.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"46.jpg", "img_right_thumb" =>"46.jpg"],
            //47
            ["date_commited" => "2013-02-27", "date_reported" => "2013-03-03", 
                "narration" => "Japanese prostitute named Takahashi Minami, better known as Takamina (her stage name) was seen in possession of drugs such as coke and cocaine, offering it to her customers when she works in the wee hours in the morning at Diamond Bar in Pedro Gil.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"47.jpg", "img_right_thumb" =>"47.jpg"],
            //48
            ["date_commited" => "2013-03-10", "date_reported" => "2013-03-20", 
                "narration" => "Atsuko Maeda, ex-singer of the Japanese group AKB48, allegedly trespassed a private property in Quezon City owned by Angelica Panay, a librarian in FEU. Maeda did not steal anything, claiming that she needed a ‘place to crash’ and she found the property suitable to her tastes.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"48.jpg", "img_right_thumb" =>"48.jpg"],
            //49
            ["date_commited" => "2013-03-30", "date_reported" => "2013-04-01", 
                "narration" => "Sakura Yamamoto, a Japan-based nurse injected an illegal drug to the dextrose of patient Ricardo Castro after speculations that the two called it quits in their relationship. Ricardo, a janitor of the hospital Yamamoto works in, broke off the relationship with Yamamoto a week before, and let her treat him during one of his panic attacks in hopes of reconciliation. Yamamoto was reported to be very depressed and angry, not being able to cope with their separation. Thus, she was accused of seeking revenge by injecting the drug into Castro’s system, which later on resulted to complications and death.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"49.jpg", "img_right_thumb" =>"49.jpg"],
            //50
            ["date_commited" => "2013-03-28", "date_reported" => "2013-04-01", 
                "narration" => "Chinese photographer Bing Ng has been reported to be found in a hotel after abusing a Filipino-American child named Jasmine Brown. Brown was sexually assaulted and kidnapped the night before. She was threatened that if she told anyone about it, Ng would kill her. Brown was lured with clothes and sweets on the way home from school, and was eventually kidnapped.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"50.jpg", "img_right_thumb" =>"50.jpg"],
            //51
            ["date_commited" => "2013-04-10", "date_reported" => "2013-04-20", 
                "narration" => "Chinese photographer Bing Ng has been reported to have been enslaving his son, Bo Ng at home. According to his son, he was not allowed to rest. If he did something wrong or it was not what he wanted, his father hit him with an electrical cord. If he wanted to sit down for a bit because he was so tired, he would scream at him. Bo was never allowed to leave the house, so he didn't realize that he was his son or even a human being, he said.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"51.jpg", "img_right_thumb" =>"51.jpg"],
            //52
            ["date_commited" => "2013-03-15", "date_reported" => "2013-04-12", 
                "narration" => "Three nurses namely: Marc Payawal, Kenneth Rafal and Charles Rafanan were attacked by three men who were identified to be part of the Batsi Gang (Samson Sanqui, Christian Tiangco and Gabriel Lantin) in SM Sta. Mesa when they were eating lunch at the food court at 1:30pm. The robbers fired shots but no one was hit and demanded the nurses in particular to get down and give their money. No other customers were attacked. The men knew they needed something from them and then got away with an undisclosed amount of money. They wore green camouflage fatigues, masks and matching caps.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"52.jpg", "img_right_thumb" =>"52.jpg"],
            //53
            ["date_commited" => "2013-05-10", "date_reported" => "2013-05-12", 
                "narration" => "The robbery of Rafael Lazo, a businessman took place in an unknown bank in Quezon City which happened at about 6:00 a.m. Lazo was there to check on a couple of files for his meeting later that day when a man suspected to be a part of Batsi Gang went inside the bank and demanded money from him. Money was taken, but Lazo is not disclosing the amount. There were no customers inside the bank at the time and no injuries were reported as it was early in the morning. The robbers left the area in a taxi.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"53.jpg", "img_right_thumb" =>"53.jpg"],
            //54
            ["date_commited" => "2013-05-19", "date_reported" => "2013-05-20", 
                "narration" => "A Vietnamese woman stole an antique jar from Richard Rabago, a businessman.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"54.jpg", "img_right_thumb" =>"54.jpg"],
            //55
            ["date_commited" => "2013-04-03", "date_reported" => "2013-04-10", 
                "narration" => "Jose Marie Viceral, more known as Vice Ganda was robbed of over 150 million yen after being swindled by a Japanese woman named Mayu Watanabe. A woman called him claiming to be working for a legitimate food manufacturing and distribution company, and she told him that her company had the opportunity to issue bonds from the Ministry of Agriculture at an annual interest rate of 15%. She even went as far as to send him an information packet explaining the loan opportunity. Having convinced Viceral of the legitimacy of her offer, for three months following the phone call, the conwoman visited his house over 14 times and in all, received over 150 million yen in payments from the Viceral.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"55.jpg", "img_right_thumb" =>"55.jpg"],
            //56
            ["date_commited" => "2013-05-12", "date_reported" => "2013-05-20", 
                "narration" => "Australian politician Jack Marshall has been suspected of arson attacks that destroyed parked cars, scorched buildings and rattled much of the nation's second-largest city over the weekend. The onslaught of intentionally set fires left residents on edge over the weekend in some of the most densely populated areas of the city. Even long-time firefighters struggled to recall an arson outbreak involving so many fires. The fires left behind a trail of smoldering debris. Police urged residents to check their cars for any signs of tampering and to take simple precautions such as locking vehicles, keeping garage and carport lights on at night and reporting suspicious activity.	",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"56.jpg", "img_right_thumb" =>"56.jpg"],
            //57
            ["date_commited" => "2013-08-01", "date_reported" => "2013-08-07", 
                "narration" => "Chris Brown, alleged rapist, impregnated Stephanie Germanotta, commonly known as Lady Gaga. According to Germanotta, when the time came to put the condom on, Brown said he didn’t want to – she said ‘well let’s not go there then, we can just keep doing what we were doing’. But he got angry and said that she couldn’t stop him. He forced himself on her anyway. Germanotta was so upset, as soon as he was finished she got dressed and went home straight away. After a couple of weeks, news broke out that Lady Gaga was pregnant.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"57.jpg", "img_right_thumb" =>"57.jpg"],
            //58
            ["date_commited" => "2013-07-30", "date_reported" => "2013-08-22", 
                "narration" => "Anne Curtis-Smith, actress, went to a party with Chris Brown, a friend she grew up with. They met some of his friends at the party and everything seemed to be going well. Smith had a couple of drinks but not that many. She didn’t remember much, but she remembered thinking ‘I feel really out of it’ when both of them were in the taxi on the way home. She woke up in a bed in an inn in Pasay City. She said she didn’t know how she got there, felt horrible and really scared and confused. Her head was thumping, and her body felt sticky. Her doctor said it’s best not to shower or anything, so he helped her get to the hospital where they did some tests and gave her the morning after pill, and antibiotics in case of infections. She had had sex and had been raped. She knew she didn’t want to or agree to it, but couldn’t remember a lot.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"58.jpg", "img_right_thumb" =>"58.jpg"],
            //59
            ["date_commited" => "2013-07-10", "date_reported" => "2013-07-12", 
                "narration" => "Eugenio Abunda, AKA Boy Abunda has been bribed to pay 10 million pesos in exchange for the release of a number of scoops in showbiz, as well as giving up his relationship with his partner. The suspect was identified to be Christian Tiangco, a member of Batsi Gang. Abunda, of course, did not agree to his offer.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"59.jpg", "img_right_thumb" =>"59.jpg"],
            //60
            ["date_commited" => "2013-09-15", "date_reported" => "2013-09-22", 
                "narration" => "Ming Li Chiu, alleged plumber and kidnapper, along with his unscrupulous men abduct kids and come into their homes when parents are away working at the tea gardens and lure young girls with new clothes and sweets. Before they know it, they are on a train to a big city at the mercy of these greedy men.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The complainant is a concerned citizen and wants to spare kids from these atrocities.", 
                "img_signature" =>"60.jpg", "img_right_thumb" =>"60.jpg"],
            //61
            ["date_commited" => "2013-06-25", "date_reported" => "2013-06-29", 
                "narration" => "OFW Sabel Sadural aborted her baby girl and used Twitter to tell the story of her abortion. In the tweets, she explains how the ‘pale, serious faces’ of three women on the flight made her suspect they were there for the same thing. After waking from the anaesthetic, she explains how she ‘cried from relief and sadness’. ‘There are so many of us who have had an abortion, but the shame and stigma has kept us silenced for too long,’ she tweeted.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"61.jpg", "img_right_thumb" =>"61.jpg"],
            //62
            ["date_commited" => "2013-06-15", "date_reported" => "2013-06-28", 
                "narration" => "Architect Anton Saley killed his son following cricket practice in their home. Andrew Saley, his son, was beaten, reportedly with a cricket bat to the head, soon after training with his junior team on Wednesday evening at the Sports Stadium in Makati City. Andrew suffered significant injuries and died at the scene. Reports said he was also stabbed, although this could not be confirmed. Police said they arrived to find the father, armed with a knife.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"62.jpg", "img_right_thumb" =>"62.jpg"],
            //63
            ["date_commited" => "2013-06-03", "date_reported" => "2013-06-04", 
                "narration" => "Japanese exchange student Yamato Akitsuki attempted and successfully raped his professor, Arlene Taclas after school hours at the parking lot of their school. Akitsuki has been fancying Taclas, according to other students and have been hitting on her since his entry in school.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"63.jpg", "img_right_thumb" =>"63.jpg"],
            //64
            ["date_commited" => "2013-02-10", "date_reported" => "2013-06-04", 
                "narration" => "Karla Talaba, a nurse in Makati Memorial Center has been suspected of having stolen a shipment of highly radioactive cobalt-60 released from co-nurse Yvonne Viray. Cobalt-60 emits strong gamma rays and poses a significant threat of radiation sickness and skin burns in the short term and causes cancer of the liver, kidneys and bones.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"64.jpg", "img_right_thumb" =>"64.jpg"],
            //65
            ["date_commited" => "2013-02-01", "date_reported" => "2013-02-04", 
                "narration" => "Justin Tomawis, a high school student, killed his father while he was driving him to school at 7am on February 1. The son has been tired of his father’s liabilities and wanted him to handle the problems himself when the father said Tomawis should stop schooling.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"65.jpg", "img_right_thumb" =>"65.jpg"],
            //66
            ["date_commited" => "2013-02-01", "date_reported" => "2013-02-04", 
                "narration" => "Welders Albert Agonoy and Carlo Agsalud got into an argument in the afternoon of February 1 when the former pushed the latter off the roof of the building they were working on. Agsalud suffered from severe blood loss and died accordingly.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"66.jpg", "img_right_thumb" =>"66.jpg"],
            //67
            ["date_commited" => "2012-12-28", "date_reported" => "2013-01-05", 
                "narration" => "Aldrich Cabello, boyfriend of Mica Reyes, has been suspected of killing his girlfriend in her car after their date for their 5th anniversary together three days after Christmas.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"67.jpg", "img_right_thumb" =>"67.jpg"],
            //68
            ["date_commited" => "2013-02-10", "date_reported" => "2013-02-28", 
                "narration" => "Julio Macaraeg, father of MJ Macaraeg has been reported of murdering his son in exchange for marijuana. The father has been summoned by drug lords to surrender his son in order to claim his ‘prize’. He loves his son dearly but drugs were also a part of his life, and that must have caused an effect in his brain to kill MJ.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"68.jpg", "img_right_thumb" =>"68.jpg"],
            //69
            ["date_commited" => "2013-06-01", "date_reported" => "2013-06-10", 
                "narration" => "Australian Sebastian Hastings suspected of twice targeting a bingo hall and robbing a particular person, Myla Monica Sumalin, a nursing student at CEU at gunpoint, according to the witness. In one of the robberies, Sumalin was struck several times in the head with a handgun in the parking lot of the Shoe Salon bingo hall.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "The victim has been in a coma for months now. The complainant sympathizes and decided to take action.", 
                "img_signature" =>"69.jpg", "img_right_thumb" =>"69.jpg"],
            //70
            ["date_commited" => "2013-01-21", "date_reported" => "2013-02-04", 
                "narration" => "Mass Communication student, Anthony Manalo spread false accusation about Jim Dwyer, a known newsreader, that he had condoned prostitution in publication houses around the country. Manalo had been spreading rumors about Dwyer’s prostitution cases and exposed them to the public using his radio shows in school.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"70.jpg", "img_right_thumb" =>"70.jpg"],
            //71
            ["date_commited" => "2009-05-28", "date_reported" => "2009-06-10", 
                "narration" => "After having an affair with an Asian woman, politician Jack Marshall (commonly known as Jack The Black) set an abandoned building on fire at around 2am in the Makati City. Sources say his affair with the woman did not turn out well, thus his arson case.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"71.jpg", "img_right_thumb" =>"71.jpg"],
            //72
            ["date_commited" => "2013-01-10", "date_reported" => "2013-02-03", 
                "narration" => "For over six years, Philips Agumbay has hounded figures of the state legal and political establishment on his blog, Legal Schnauzer, a hothouse of furious but often fuzzily sourced allegations of deep corruption and wide-ranging conspiracy. Some of these allegations he has tested in court, having sued his neighbor, his neighbor’s lawyer and now his former employer, Allan Cardona among others. Mostly, he has lost.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "Mr. Agumbay is no stranger to defamation suits, as one might surmise from reading his blog.", 
                "img_signature" =>"72.jpg", "img_right_thumb" =>"72.jpg"],
            //73
            ["date_commited" => "2013-05-30", "date_reported" => "2013-06-03", 
                "narration" => "Landon Jordan, an Australian politician is being sued by Allan Cardona, a newsreader, for defamation and malicious prosecution after his acquittal on criminal charges in a maternity ward scuffle. Cardona said that Jordan damaged his reputation and led to his prosecution.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"73.jpg", "img_right_thumb" =>"73.jpg"],
            //74
            ["date_commited" => "2013-05-30", "date_reported" => "2013-06-03", 
                "narration" => "Paulo Arcilla and Samson Sanqui have been charged with trying to steal card numbers and PINs of customers at Citibank Alabang branch. The pair is charged with burglary and criminal possession of forgery device. They placed a skimming machine over the card reader on ATM machine after dark, stuck a couple of cameras above the keypads on the cash machines inside and waited to collect the numbers from unsuspecting customers. Patrick Yalung, a messenger, has been one of the victims of this act as he lost P70,000 worth of money in his account in one night.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"74.jpg", "img_right_thumb" =>"74.jpg"],
            //75
            ["date_commited" => "2013-05-29", "date_reported" => "2013-06-03", 
                "narration" => "American accountant Richmond Collins raped Korean-American student Krystal Jung inside a boarding house in Malate, Manila. According to Jung, she was raped by a stranger late at night while delivering a letter to an ex-boyfriend. She had little recollection of the actual rape, but it was confirmed during an exam at a local hospital. Bits and pieces of the experience still linger. She told him to leave and then he kissed her and shoved his hand in between her legs. Jung tried to yell, but he was kissing her so hard she couldn't. She tried to fight him, but it just happened so quick, and her struggling did little. After it was over he said he would call her, and then he got up and left. She just sat there on the bed and couldn't even cry.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"75.jpg", "img_right_thumb" =>"75.jpg"],
            //76
            ["date_commited" => "2013-09-02", "date_reported" => "2013-09-10", 
                "narration" => "Doctor Lance Kurtis Alipio has allegedly cheated on his wife and raped his niece, Aliyah Arroyo in his house when Arroyo came over to interview his uncle for a project. Arroyo said the first time his uncle touched her inappropriately, she was mortified. His hand was under her chest and the other between her legs. She could feel the warmth of his hand on her privates through the fabric of her underwear. She remembered her face going bright red with embarrassment and had tears in her eyes. She couldn’t resist as he continued his ministrations until Alipio’s wife saw them in bed together.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"76.jpg", "img_right_thumb" =>"76.jpg"],
            //77
            ["date_commited" => "2010-12-21", "date_reported" => "2010-12-31", 
                "narration" => "Sungyeol Choi, a Korean student has dealt drugs to a high school student named Gio Balaba. When Balaba did not want to buy drugs from him anymore, Choi was reported to have killed him by hitting him on the head and on other parts of the body.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"77.jpg", "img_right_thumb" =>"77.jpg"],
            //78
            ["date_commited" => "2010-10-24", "date_reported" => "2010-12-04", 
                "narration" => " A witness reported that cases where products belonging to popular Indian brands like Natraj Pencil, Boroplus antiseptic cream, Raymond, Onida etc., and more importantly iPhone 5S units are being copied and sold in Greenhills. African-Americans have been speculated to be suspects of this counterfeiting.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"78.jpg", "img_right_thumb" =>"78.jpg"],
            //79
            ["date_commited" => "2010-03-10", "date_reported" => "2010-11-11", 
                "narration" => "Gong Wai See, China man from Korea has been suspected of printing $1.1 million in fake $50 bills, after months of detective work and use of confidential informer in bank payments; See, who apparently manipulated scanners and printers to create money, appears to be part of one of larger counterfeit rings in the South.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"79.jpg", "img_right_thumb" =>"79.jpg"],
            //80
            ["date_commited" => "2009-11-01", "date_reported" => "2009-11-21", 
                "narration" => "Chinese businessman Xiong Chua kidnapped Anne Balangay, a 7-year old student from St. Scholastica College and allegedly enslaved her. Balangay’s parents who were in their garage at the time said a man in a pickup truck pulled up next to their daughter and asked for directions. She turned to walk away but he called her over and when she took a couple of steps closer, he lunged out of the vehicle, grabbed the girl with his left hand and threw her into the truck like a rag doll, they say. The couple gave the truck's license number, while other witnesses gave chase on foot and one tried to follow in a car but lost the truck.",
                "agency_reported" =>"", "agency_report_details" =>"", "agency_report_status" =>"", "court_action_details" =>"", 
                "considerations" => "", 
                "img_signature" =>"80.jpg", "img_right_thumb" =>"80.jpg"],
            
            //EWPID
            ["date_commited" => "2008-10-09", "date_reported" => "2008-11-30", "narration" => "The nature of crime which is Forgery  was committed by the subject last October 9,2008.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "A signature was forged by the subject", "img_signature" => "81.jpg", "img_right_thumb" => "81.jpg"],
            ["date_commited" => "2008-10-10", "date_reported" => "2008-11-01", "narration" => "The nature of crime which is Gambling  was committed by the subject last October 10,2008.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Gambling were reported on a certain place", "img_signature" => "82.jpg", "img_right_thumb" => "82.jpg"],
            ["date_commited" => "2008-10-11", "date_reported" => "2008-11-02", "narration" => "The nature of crime which is Sexual Abuse  was committed by the subject last October 11,2008.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The victim was sexually abused by the subject", "img_signature" => "83.jpg", "img_right_thumb" => "83.jpg"],
            ["date_commited" => "2010-10-12", "date_reported" => "2010-11-03", "narration" => "The nature of crime which is Grave Scandal  was committed by the subject last October 12,2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Highly untolerable act done by the subject", "img_signature" => "84.jpg", "img_right_thumb" => "84.jpg"],
            ["date_commited" => "2010-10-13", "date_reported" => "2010-11-04", "narration" => "The nature of crime which is  Public Disorder was committed by the subject last October 13,2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Act of disrespect was showned in public by the subject", "img_signature" => "85.jpg", "img_right_thumb" => "85.jpg"],
            ["date_commited" => "2011-10-14", "date_reported" => "2011-11-05", "narration" => "The nature of crime which is Direct Assault  was committed by the subject last October 14,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject punched the victim in the face", "img_signature" => "86.jpg", "img_right_thumb" => "86.jpg"],
            ["date_commited" => "2011-10-15", "date_reported" => "2011-11-06", "narration" => "The nature of crime which is Forgery  was committed by the subject last October 15,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The signature of the president was forged by the subject", "img_signature" => "87.jpg", "img_right_thumb" => "87.jpg"],
            ["date_commited" => "2011-10-17", "date_reported" => "2011-11-07", "narration" => "The nature of crime which is Bribery  was committed by the subject last October 17,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject offers alot of money for the victim to do something he do not want to do", "img_signature" => "88.jpg", "img_right_thumb" => "88.jpg"],
            ["date_commited" => "2011-10-18", "date_reported" => "2011-11-08", "narration" => "The nature of crime which is Prohibited transaction  was committed by the subject last October 18,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "A drug transaction were done in a public place by the subject", "img_signature" => "89.jpg", "img_right_thumb" => "89.jpg"],
            ["date_commited" => "2013-10-19", "date_reported" => "2013-11-09", "narration" => "The nature of crime which is Infidelity  was committed by the subject last October 19,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Trust issue that leads to a war", "img_signature" => "90.jpg", "img_right_thumb" => "90.jpg"],
            //DID
            ["date_commited" => "2011-12-02", "date_reported" => "2011-12-10", "narration" => "The nature of crime which is Disobedience  was committed by the subject last December 2, 2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject did not obey the president as the president enters the room", "img_signature" => "91.jpg", "img_right_thumb" => "91.jpg"],
            ["date_commited" => "2011-12-04", "date_reported" => "2011-12-11", "narration" => "The nature of crime which is Relevance of Secret  was committed by the subject last December 4, 2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject revealed a top secret of the victim", "img_signature" => "92.jpg", "img_right_thumb" => "92.jpg"],
            ["date_commited" => "2012-12-05", "date_reported" => "2012-12-12", "narration" => "The nature of crime which is  Maltreatment of Prisoner was committed by the subject last December 5, 2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject punched the victim prisoner in the face", "img_signature" => "93.jpg", "img_right_thumb" => "93.jpg"],
            ["date_commited" => "2012-12-07", "date_reported" => "2012-12-13", "narration" => "The nature of crime which is Usurpation  was committed by the subject last December 7,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject did not let the victim to enter a public place", "img_signature" => "94.jpg", "img_right_thumb" => "94.jpg"],
            ["date_commited" => "2012-12-09", "date_reported" => "2012-12-14", "narration" => "The nature of crime which is Suicide  was committed by the subject last December 9,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The victim jumped in the 21st floor of the building", "img_signature" => "95.jpg", "img_right_thumb" => "95.jpg"],
            ["date_commited" => "2012-12-10", "date_reported" => "2012-12-15", "narration" => "The nature of crime which is Abortion  was committed by the subject last December 10,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Aborted child was found in the garbage can", "img_signature" => "96.jpg", "img_right_thumb" => "96.jpg"],
            ["date_commited" => "2013-12-11", "date_reported" => "2013-12-16", "narration" => "The nature of crime which is Infanticide  was committed by the subject last December 11,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject maltreated the new infant", "img_signature" => "97.jpg", "img_right_thumb" => "97.jpg"],
            ["date_commited" => "2013-12-13", "date_reported" => "2013-12-17", "narration" => "The nature of crime which is  Serious Illegal Detention was committed by the subject last December 13,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject killed many people", "img_signature" => "98.jpg", "img_right_thumb" => "98.jpg"],
            ["date_commited" => "2013-12-15", "date_reported" => "2013-12-18", "narration" => "The nature of crime which is Kidnapping  was committed by the subject last December 15,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "An infant was stolen by the subject", "img_signature" => "99.jpg", "img_right_thumb" => "99.jpg"],
            ["date_commited" => "2013-12-16", "date_reported" => "2013-12-19", "narration" => "The nature of crime which is Slavery  was committed by the subject last December 16,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject do not give rights to the victim", "img_signature" => "100.jpg", "img_right_thumb" => "100.jpg"],
            //IPRD
            ["date_commited" => "2009-04-25", "date_reported" => "2009-05-01", "narration" => "The nature of crime which is Drunk Driving  was committed by the subject last April 26,2009 .", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The car of the victim was hit by the car of the subject", "img_signature" => "101.jpg", "img_right_thumb" => "101.jpg"],
            ["date_commited" => "2009-05-01", "date_reported" => "2009-05-02", "narration" => "The nature of crime which is Possession of Dangerous Drugs  was committed by the subject last May 1, 2009.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject was caught selling prohibited drugs to a minor", "img_signature" => "102.jpg", "img_right_thumb" => "102.jpg"],
            ["date_commited" => "2010-05-02", "date_reported" => "2010-05-03", "narration" => "The nature of crime which is Vandalism was committed by the subject last May 2, 2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject was caught writing on a public wall", "img_signature" => "103.jpg", "img_right_thumb" => "103.jpg"],
            ["date_commited" => "2010-05-03", "date_reported" => "2010-05-05", "narration" => "The nature of crime which is Robbery was committed by the subject last May 3, 2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject stole the bag of the victim", "img_signature" => "104.jpg", "img_right_thumb" => "104.jpg"],
            ["date_commited" => "2011-05-07", "date_reported" => "2011-05-08", "narration" => "The nature of crime which is Treason  was committed by the subject last May 7,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject betrayed his own country", "img_signature" => "105.jpg", "img_right_thumb" => "105.jpg"],
            ["date_commited" => "2012-05-09", "date_reported" => "2012-05-10", "narration" => "The nature of crime which is Espionage  was committed by the subject last May 9,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject revealed a military secret of action in order to obtain a top criminal", "img_signature" => "106.jpg", "img_right_thumb" => "106.jpg"],
            ["date_commited" => "2012-05-08", "date_reported" => "2012-05-10", "narration" => "The nature of crime which is Robbery  was committed by the subject last May 8, 2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The car of the victim was stolen 10 days ago", "img_signature" => "107.jpg", "img_right_thumb" => "107.jpg"],
            ["date_commited" => "2012-05-15", "date_reported" => "2012-05-18", "narration" => "The nature of crime which is Rape  was committed by the subject last May 15,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The victim was in really traumatized due to the act done by the subject", "img_signature" => "108.jpg", "img_right_thumb" => "108.jpg"],
            ["date_commited" => "2012-05-16", "date_reported" => "2012-05-18", "narration" => "The nature of crime which is Domestic Violence  was committed by the subject last May 16, 2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Abusive act done by the subject to the victim", "img_signature" => "109.jpg", "img_right_thumb" => "109.jpg"],
            ["date_commited" => "2012-05-17", "date_reported" => "2012-05-18", "narration" => "The nature of crime which is Petty Theft was committed by the subject last May 17,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "The subject gets money in the wallet of the victim without permission", "img_signature" => "110.jpg", "img_right_thumb" => "110.jpg"],
            //RAID
            ["date_commited" => "2010-01-27", "date_reported" => "2010-01-30", "narration" => "The nature of crime which is Arbitrary Detention  was committed by the subject last January 27, 2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible arbitrary detention case against the suspect", "img_signature" => "111.jpg", "img_right_thumb" => "111.jpg"],
            ["date_commited" => "2010-02-01", "date_reported" => "2010-02-02", "narration" => "The nature of crime which is Expulsion  was committed by the subject last February 1,2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible explusion case against the suspect", "img_signature" => "112.jpg", "img_right_thumb" => "112.jpg"],
            ["date_commited" => "2010-02-01", "date_reported" => "2010-02-02", "narration" => "The nature of crime which is Violation of Domicile  was committed by the subject last February 1,2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible violation of domicile case against the suspect", "img_signature" => "113.jpg", "img_right_thumb" => "113.jpg"],
            ["date_commited" => "2011-02-08", "date_reported" => "2011-02-10", "narration" => "The nature of crime which is Prohibition, interruption, and dissolution of peaceful meetings  was committed by the subject last February 8,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Prohibition, interruption, and dissolution of peaceful meetings case against the suspect", "img_signature" => "114.jpg", "img_right_thumb" => "114.jpg"],
            ["date_commited" => "2011-02-09", "date_reported" => "2011-02-10", "narration" => "The nature of crime which is Rebellion  was committed by the subject last February 9,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Rebellion case against the suspect", "img_signature" => "115.jpg", "img_right_thumb" => "115.jpg"],
            ["date_commited" => "2011-02-15", "date_reported" => "2011-02-16", "narration" => "The nature of crime which is Disloyalty  was committed by the subject last February 15,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible disloyalty case against the suspect", "img_signature" => "116.jpg", "img_right_thumb" => "116.jpg"],
            ["date_commited" => "2013-02-18", "date_reported" => "2013-02-19", "narration" => "The nature of crime which is  Disturbance of Proceedings was committed by the subject last February 18,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible disturbance of proceedings case against the suspect", "img_signature" => "117.jpg", "img_right_thumb" => "117.jpg"],
            ["date_commited" => "2013-02-20", "date_reported" => "2013-02-22", "narration" => "The nature of crime which is Illegal Assemblies  was committed by the subject last February 20,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Illegal assemblies case against the suspect", "img_signature" => "118.jpg", "img_right_thumb" => "118.jpg"],
            ["date_commited" => "2013-02-21", "date_reported" => "2013-02-27", "narration" => "The nature of crime which is Direct Assault   was committed by the subject last February 21, 2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Direct Assault case against the suspect", "img_signature" => "119.jpg", "img_right_thumb" => "119.jpg"],
            ["date_commited" => "2014-02-25", "date_reported" => "2014-02-27", "narration" => "The nature of crime which is Direct Assault  was committed by the subject last February 25,2014.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Direct Assault case against the suspect", "img_signature" => "120.jpg", "img_right_thumb" => "120.jpg"],
            //VAWCD
            ["date_commited" => "2009-09-26", "date_reported" => "2009-09-30", "narration" => "The nature of crime which is Public Disorder  was committed by the subject last September 26,2009.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Public disorder case against the suspect", "img_signature" => "121.jpg", "img_right_thumb" => "121.jpg"],
            ["date_commited" => "2009-09-28", "date_reported" => "2009-10-01", "narration" => "The nature of crime which is Forgery  was committed by the subject last September 28,2009.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Forgery case against the suspect", "img_signature" => "122.jpg", "img_right_thumb" => "122.jpg"],
            ["date_commited" => "2010-10-01", "date_reported" => "2010-10-02", "narration" => "The nature of crime which is Falsification  was committed by the subject last October 1,2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Falsification case against the suspect", "img_signature" => "123.jpg", "img_right_thumb" => "123.jpg"],
            ["date_commited" => "2010-10-05", "date_reported" => "2010-10-06", "narration" => "The nature of crime which is Fraud  was committed by the subject last October 5,2010.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Fraud case against the suspect", "img_signature" => "124.jpg", "img_right_thumb" => "124.jpg"],
            ["date_commited" => "2011-10-09", "date_reported" => "2011-10-10", "narration" => "The nature of crime which is Dereliction  was committed by the subject last October 9,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Dereliction case against the suspect", "img_signature" => "125.jpg", "img_right_thumb" => "125.jpg"],
            ["date_commited" => "2011-10-10", "date_reported" => "2011-10-12", "narration" => "The nature of crime which is Bribery  was committed by the subject last October 10,2011.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Bribery case against the suspect", "img_signature" => "126.jpg", "img_right_thumb" => "126.jpg"],
            ["date_commited" => "2012-10-12", "date_reported" => "2012-10-15", "narration" => "The nature of crime which is Prohibited transaction  was committed by the subject last October 12,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Prohibited transaction case against the suspect", "img_signature" => "127.jpg", "img_right_thumb" => "127.jpg"],
            ["date_commited" => "2012-10-16", "date_reported" => "2012-10-20", "narration" => "The nature of crime which is Infidelity  was committed by the subject last October 16,2012.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Infidelity case against the suspect", "img_signature" => "128.jpg", "img_right_thumb" => "128.jpg"],
            ["date_commited" => "2012-10-18", "date_reported" => "2012-10-20", "narration" => "The nature of crime which is Disobedience  was committed by the subject last October 18,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Disobedience case against the suspect", "img_signature" => "129.jpg", "img_right_thumb" => "129.jpg"],
            ["date_commited" => "2013-10-26", "date_reported" => "2013-10-29", "narration" => "The nature of crime which is Forgery  was committed by the subject last October 26,2013.", "agency_reported" => "",
                "agency_report_details" => "", "agency_report_status" => "", "court_action_details" => "",
                "considerations" => "Possible Forgery case against the suspect", "img_signature" => "130.jpg", "img_right_thumb" => "130.jpg"],
            
        );

        // Uncomment the below to run the seeder
         DB::table('complaints')->insert($complaints);
    }

}
