<?php

class Evidence_objectsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('evidence_objects')->truncate();

        $evidence_objects = array(
            //1
            ["user_id" => 10930216, "owner" => "Mike Jones", "case_id" => 5, "details" => "Parrying dagger with the victim's blood", "length" => "12 in.", "width" => "2 in.",
                "height" => "12 in.", "date_received" => "2014-05-01"],
            ["user_id" => 10930216, "owner" => "JJ Santos", "case_id" => 6, "details" => "Mendoza C-1934 machine gun", "length" => "10 in.", "width" => "3 in.",
                "height" => "4 in.", "date_received" => "2013-02-22"],
            ["user_id" => 10930216, "owner" => "Larry Torres", "case_id" => 6, "details" => "Mendoza C-1934 machine gun", "length" => "10 in.", "width" => "3 in.",
                "height" => "4 in.", "date_received" => "2013-02-22"],
            ["user_id" => 10930216, "owner" => "Larry Torres", "case_id" => 6, "details" => "Mauser Cartridge (full)", "length" => "7 mm.", "width" => "57 mm.",
                "height" => "3 in.", "date_received" => "2013-02-22"],
            ["user_id" => 10930216, "owner" => "JJ Santos", "case_id" => 6, "details" => "Mauser Cartridge (almost empty)", "length" => "7 mm.", "width" => "57 mm.",
                "height" => "3 in.", "date_received" => "2013-02-22"],
            ["user_id" => 10930216, "owner" => "JJ Santos", "case_id" => 6, "details" => "5 Mendoza C-1934 bullets", "length" => "10 mm.", "width" => "60 mm.",
                "height" => "1 in.", "date_received" => "2013-02-22"],
            ["user_id" => 10930216, "owner" => "Larry Torres", "case_id" => 6, "details" => "10 Mendoza C-1934 bullets", "length" => "10 mm.", "width" => "60 mm.",
                "height" => "1 in.", "date_received" => "2013-02-22"],
            ["user_id" => 10930216, "owner" => "Gong Wai", "case_id" => 8, "details" => "Knightly dagger", "length" => "5 in.", "width" => "2 in.",
                "height" => "6 in.", "date_received" => "2013-03-09"],
            ["user_id" => 10930216, "owner" => "Kristina Gacutan", "case_id" => 9, "details" => "Bloody balisong", "length" => "30 in.", "width" => "4 in.",
                "height" => "4 in.", "date_received" => "2013-03-09"],
            ["user_id" => 10930216, "owner" => "Lebron Anthony, Terrence Williams, Shawn Kristy", "case_id" => 10, "details" => "2 packets of ecstacy", "length" => "", "width" => "",
                "height" => "", "date_received" => "2013-02-25"],
            //11
            ["user_id" => 10930216, "owner" => "Lebron Anthony, Terrence Williams, Shawn Kristy", "case_id" => 10, "details" => "3 packets of cocaine", "length" => "", "width" => "",
                "height" => "4 in.", "date_received" => "2013-02-25"],
            ["user_id" => 10930216, "owner" => "Maynard Plumlee", "case_id" => 15, "details" => "Shabu samples from Taguig lab", "length" => "", "width" => "",
                "height" => "18 in.", "date_received" => "2013-05-30"],
            ["user_id" => 10930216, "owner" => "Victorio Ricardo", "case_id" => 17, "details" => "Astra A-80 bullet", "length" => "8 mm.", "width" => "10 mm.",
                "height" => "1 in.", "date_received" => "2013-06-19"],
            ["user_id" => 10930216, "owner" => "Veronica Co", "case_id" => 20, "details" => "Beretta 21 Bobcat pistol", "length" => "5 in.", "width" => "2 in.",
                "height" => "4 in.", "date_received" => "2013-08-12"],
            ["user_id" => 10930216, "owner" => "Veronica Co", "case_id" => 20, "details" => "7 Beretta 21 Bobcat bullets", "length" => "8 mm.", "width" => "10 mm.",
                "height" => "1 in.", "date_received" => "2013-08-12"],
            ["user_id" => 10930216, "owner" => "Mariz Tamboa", "case_id" => 22, "details" => "Hunting dagger with the victim's blood", "length" => "10 in.", "width" => "2 in.",
                "height" => "8 in.", "date_received" => "2013-09-11"],
            ["user_id" => 10930216, "owner" => "Monica Velasco", "case_id" => 23, "details" => "Caracal pistol", "length" => "5 in.", "width" => "4 in.",
                "height" => "7 in.", "date_received" => "2013-09-22"],
            ["user_id" => 10930216, "owner" => "Paulo Arcilla", "case_id" => 24, "details" => "2 AK-47 bullets", "length" => "2 in.", "width" => "2 in.",
                "height" => "4 in.", "date_received" => "2013-10-12"],
            ["user_id" => 10930216, "owner" => "Samson Sanqui", "case_id" => 24, "details" => "1 AMD-65 bullet", "length" => "2 in.", "width" => "2 in.",
                "height" => "4 in.", "date_received" => "2013-10-13"],
            ["user_id" => 10930216, "owner" => "Sungyeol Choi, Myungsoo Choi", "case_id" => 28, "details" => "1 packet of heroin", "length" => "", "width" => "",
                "height" => "", "date_received" => "2013-12-01"],
            //21
            ["user_id" => 10930216, "owner" => "Sean William Parker", "case_id" => 31, "details" => "Carbon 15 Type 21 bullet", "length" => "8 mm.", "width" => "10 mm.",
                "height" => "1 in.", "date_received" => "2013-01-04"],
            ["user_id" => 10930216, "owner" => "Jackson Kelly", "case_id" => 35, "details" => "15 fake gift certificates from Starbucks", "length" => "", "width" => "",
                "height" => "", "date_received" => "2013-03-06"],
            ["user_id" => 10930216, "owner" => "Landon Jordan", "case_id" => 38, "details" => "Glock 17 pistol", "length" => "6 in.", "width" => "4 in.",
                "height" => "4 in.", "date_received" => "2013-05-30"],
            ["user_id" => 10930216, "owner" => "Minami Takahashi", "case_id" => 47, "details" => "2 packets of coke", "length" => "", "width" => "",
                "height" => "", "date_received" => "2013-04-02"],
            ["user_id" => 10930216, "owner" => "Minami Takahashi", "case_id" => 47, "details" => "3 packets of cocaine", "length" => "", "width" => "",
                "height" => "", "date_received" => "2013-04-02"],
            ["user_id" => 10930216, "owner" => "Marc Payawal", "case_id" => 52, "details" => "16 Nikonov bullets", "length" => "12 mm.", "width" => "7 mm.",
                "height" => "2 in.", "date_received" => "2013-06-12"],
            ["user_id" => 10930216, "owner" => "Anton Saley", "case_id" => 62, "details" => "Cricket bat with Andrew Saley's blood", "length" => "30 in.", "width" => "5 in.",
                "height" => "5 in.", "date_received" => "2013-10-13"],
            ["user_id" => 10930216, "owner" => "Justin Tomawis", "case_id" => 65, "details" => "Glock 17 bullet", "length" => "6 mm.", "width" => "10 mm.",
                "height" => "1 in.", "date_received" => "2013-06-24"],
            ["user_id" => 10930216, "owner" => "Aldrich Cabello", "case_id" => 67, "details" => "Empty cartridge of Parabellum pistol", "length" => "9 mm.", "width" => "19 mm.",
                "height" => "2 in.", "date_received" => "2013-07-29"],
            ["user_id" => 10930216, "owner" => "Julio Macaraeg", "case_id" => 68, "details" => "Beretta Cheetah bullet", "length" => "10 mm.", "width" => "3 mm.",
                "height" => "1 in.", "date_received" => "2013-07-30"],
            //31
            ["user_id" => 10930216, "owner" => "Julio Macaraeg", "case_id" => 68, "details" => "Beretta Cheetah pistol", "length" => "6 in.", "width" => "4 in.",
                "height" => "5 in.", "date_received" => "2013-07-30"],
            ["user_id" => 10930216, "owner" => "Julio Macaraeg", "case_id" => 68, "details" => "1 packet of marijuana", "length" => "", "width" => "",
                "height" => "", "date_received" => "2013-07-31"],
            ["user_id" => 10930216, "owner" => "Jack Marshall", "case_id" => 71, "details" => "Montblanc lighter", "length" => "3 in.", "width" => "1 in.",
                "height" => "3 in.", "date_received" => "2009-07-30"],
            ["user_id" => 10930216, "owner" => "Sungyeol Choi", "case_id" => 77, "details" => "Assorted pill capsules", "length" => "", "width" => "",
                "height" => "", "date_received" => "2010-01-15"],
            ["user_id" => 10930216, "owner" => "Rita Castillo", "case_id" => 78, "details" => "60 iPhone 5S imitation units", "length" => "5 in.", "width" => "3 in.",
                "height" => "0.30 in.", "date_received" => "2011-01-10"],
            //36 KIER
            ["user_id" => 10930216, "owner" => "Bea Puzon", "case_id" => 81, "details" => "Ballpen used in the Forgery case", "length" => "7 in.", "width" => "0.5 in.",
                "height" => "7 in.", "date_received" => "2008-11-30"],
            ["user_id" => 10930216, "owner" => "Bernice Bassig", "case_id" => 82, "details" => "Gambling dice", "length" => "2 in.", "width" => "1 in.",
                "height" => "2 in.", "date_received" => "2008-11-10"],
            ["user_id" => 10930216, "owner" => "Bernice Bassig", "case_id" => 82, "details" => "Gambling cards", "length" => "5 in.", "width" => "0.2 in.",
                "height" => "5 in.", "date_received" => "2008-11-10"],
            ["user_id" => 10930216, "owner" => "ABC Motel", "case_id" => 83, "details" => "Bedsheet found at the crimescene", "length" => "100 in.", "width" => "80 in.",
                "height" => "100 in.", "date_received" => "2008-11-05"],
            ["user_id" => 10930216, "owner" => "Government Property", "case_id" => 85, "details" => "Broken object resulting to public disorder of the subject", "length" => "50 in.", "width" => "40 in.",
                "height" => "50 in.", "date_received" => "2010-11-04"],
            ["user_id" => 10930216, "owner" => "Elayssa Ferias", "case_id" => 87, "details" => "Ballpen used in the Forgery case", "length" => "7 in.", "width" => "0.5 in.",
                "height" => "7 in.", "date_received" => "2011-11-06"],
            ["user_id" => 10930216, "owner" => "Pamela Mendiola", "case_id" => 88, "details" => "Money used in the case was obtained", "length" => "5 in.", "width" => "1 in.",
                "height" => "5 in.", "date_received" => "2011-11-07"],
            ["user_id" => 10930216, "owner" => "James Martinez", "case_id" => 95, "details" => "Maong pants of James Martinez who commit suicide", "length" => " in.", "width" => " in.",
                "height" => " in.", "date_received" => "2012-11-16"],
            ["user_id" => 10930216, "owner" => "James Martinez", "case_id" => 95, "details" => "Polo shirt of James Martinez who commit suicide", "length" => " in.", "width" => " in.",
                "height" => " in.", "date_received" => "2012-11-16"],
            ["user_id" => 10930216, "owner" => "Joanthan Ochoa", "case_id" => 101, "details" => "The car of the Jonathan Ochoa was obtained by the investigator", "length" => "300 in.", "width" => "250 in.",
                "height" => "300 in.", "date_received" => "2009-05-06"],
            //46
            ["user_id" => 10930216, "owner" => "Ernesto Villamin", "case_id" => 102, "details" => "Drug paraphernalia found", "length" => "35 in.", "width" => "22 in.",
                "height" => "35 in.", "date_received" => "2009-05-04"],
            ["user_id" => 10930216, "owner" => "Ernesto Villamin", "case_id" => 102, "details" => "Shabu found on the bag of Ernesto Villamin", "length" => "1 in.", "width" => "1 in.",
                "height" => "1 in.", "date_received" => "2009-05-02"],
            ["user_id" => 10930216, "owner" => "Armando Villena", "case_id" => 103, "details" => "The spray paint used by Armando Villena was obtained by the investigator", "length" => "10 in.", "width" => "3 in.",
                "height" => "10 in.", "date_received" => "2009-05-03"],
            ["user_id" => 10930216, "owner" => "Mauro Lumba", "case_id" => 104, "details" => "The bag of the victim was founded as the house of Carlo Sta. Cruz", "length" => "24 in.", "width" => "12 in.",
                "height" => "24 in.", "date_received" => "2009-05-10"],
            ["user_id" => 10930216, "owner" => "Jason Delaroca", "case_id" => 107, "details" => "The car of the victim was founded at the basement parking", "length" => "600 in.", "width" => "400 in.",
                "height" => "600 in.", "date_received" => "2012-05-28"],
            ["user_id" => 10930216, "owner" => "Queenie Amulong", "case_id" => 108, "details" => "Underwear of the victim was obtained by the investigator", "length" => "12 in.", "width" => "9 in.",
                "height" => "12 in.", "date_received" => "2013-05-20"],
            ["user_id" => 10930216, "owner" => "Abo Acleb", "case_id" => 110, "details" => "Money involve in the case was obtained by the investigator", "length" => "10 in.", "width" => "1 in.",
                "height" => "10 in.", "date_received" => "2013-05-22"],
            ["user_id" => 10930216, "owner" => "Dave Bermillo", "case_id" => 118, "details" => "Tool used for assembling", "length" => "7 in.", "width" => "2 in.",
                "height" => "7 in.", "date_received" => "2013-02-30"],
            ["user_id" => 10930216, "owner" => "James Calleja", "case_id" => 119, "details" => "Shirt full of blood stain was obtained by the investigator", "length" => "20 in.", "width" => "12 in.",
                "height" => "20 in.", "date_received" => "2014-02-27"],
            ["user_id" => 10930216, "owner" => "James Calleja", "case_id" => 119, "details" => "Shorts full of blood stain was obtained by the investigator", "length" => "28 in.", "width" => "15 in.",
                "height" => "28 in.", "date_received" => "2014-02-27"],
            //56
            ["user_id" => 10930216, "owner" => "Angela Criselda", "case_id" => 120, "details" => "Gun used by Angela Criselda was obtained by the investigator", "length" => "11 in.", "width" => "3 in.",
                "height" => "11 in.", "date_received" => "2014-02-27"],
            //57
            ["user_id" => 10930216, "owner" => "Miley Cauricio", "case_id" => 122, "details" => "Ballpen used by Miley Cauricio was obtained by the investigator", "length" => "7 in.", "width" => "2 in.",
                "height" => "7 in.", "date_received" => "2009-10-04"],
            //58        
            ["user_id" => 10930216, "owner" => "Rosanna Fernando", "case_id" => 126, "details" => "Money used in the case was obtained by the investigator", "length" => "10 in.", "width" => "2 in.",
                "height" => "10 in.", "date_received" => "2011-10-13"],
            //59
            ["user_id" => 10930216, "owner" => "Lovely Bueno", "case_id" => 130, "details" => "Forgery device was founded at the house of the subject", "length" => "46 in.", "width" => "12 in.",
                "height" => "46 in.", "date_received" => "2013-10-31"],
            //60
            ["user_id" => 10930216, "owner" => "Gary Michael Waters", "case_id" => 29, "details" => "50 Samsung S4 imitation units", "length" => "5 in.", "width" => "2 in.",
                "height" => "0.35 in.", "date_received" => "2013-12-30"],
            //61
            ["user_id" => 10930216, "owner" => "Gary Michael Waters", "case_id" => 29, "details" => "23 Nokia Lumia 620 imitation units", "length" => "5 in.", "width" => "2.5in.",
                "height" => "0.45 in.", "date_received" => "2013-12-30"],
        );

        // Uncomment the below to run the seeder
        DB::table('evidence_objects')->insert($evidence_objects);
    }

}
