<?php

class TagsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('tags')->truncate();

        $tags = array(
            //**KASES**//
            ["reference_id" => 1, "table" => "kases", "tags" => "case, committed 2014-02-10, Theft, high school, vault, stolen funds"],
            ["reference_id" => 2, "table" => "kases", "tags" => "case, committed 2014-01-22, Rape, oral sex, extortion, Cedric Lee, blindfolded, tied up and attacked, Bonifacio Global City, condominium"],
            ["reference_id" => 3, "table" => "kases", "tags" => "case, committed 2014-02-10, Uncategorized, bulalo, cup noodles, beat up, Pedro Gil"],
            ["reference_id" => 4, "table" => "kases", "tags" => "case, committed 2009-03-01, Prostitution, Corruption of minor, seduction, waitress, sexual act, exchange for money, bar, community complaint, Malate"],
            ["reference_id" => 5, "table" => "kases", "tags" => "case, committed 2013-04-14, Murder, Direct Assault, stabbed in heart, argument, apartment, first degree murder, stabbed to death multiple times"],
            ["reference_id" => 6, "table" => "kases", "tags" => "case, committed 2013-12-26, Homicide, Direct Assault, shooting, head shattered, limbs tattered, Cotabato City, firearms, nametags"],
            ["reference_id" => 7, "table" => "kases", "tags" => "case, committed 2013-01-02, Suicide, college, Far Eastern University, condominium, scholarship, failing classes, financial problems"],
            ["reference_id" => 8, "table" => "kases", "tags" => "case, committed 2013-01-23, Murder, Serious physical injuries, De La Salle University, Agno gate, stabbed in the head multiple times, owed money, refusal, smoking, cries, condominium"],
            ["reference_id" => 9, "table" => "kases", "tags" => "case, committed 2013-02-14, Immortal doctrines, obscene publications and exhibitions, Parricide, Infanticide, cannibalism, eating, hunger, temptation, intense pain, shivering, epilepsy, threats, depression, anxiety disorder"],
            ["reference_id" => 10, "table" => "kases", "tags" => "case, committed 2013-01-25, Gambling and Betting, Illegal association, Possession, preparation and use of prohibited drugs and maintenance of opium dens, illegal association"],
            ["reference_id" => 11, "table" => "kases", "tags" => "case, committed 2013-02-27, Murder, Direct Assault, brain damage, explosion, atomic bomb, casualties"],
            ["reference_id" => 12, "table" => "kases", "tags" => "case, committed 2013-01-02, Counterfeiting, Falsification, custom coins, minting, private money, Liberty Dollar, XYZ Company, private voluntary currency, business"],
            ["reference_id" => 13, "table" => "kases", "tags" => "case, committed 2013-01-05, Abduction, Grave coercions, Kidnapping, Corruption of minor, Slavery, children, school"],
            ["reference_id" => 14, "table" => "kases", "tags" => "case, committed 2013-03-10, Possession, preparation and use of prohibited drugs and maintenance of opium dens, Possession of Dangerous Drugs For Sale, Light threats, drug dealers, marijuana, disguise, garbage collectors"],
            ["reference_id" => 15, "table" => "kases", "tags" => "case, committed 2013-04-18, Possession, preparation and use of prohibited drugs and maintenance of opium dens, Possession of Dangerous Drugs For Sale, drug lord, shabu, lab"],
            ["reference_id" => 16, "table" => "kases", "tags" => "case, committed 2013-01-10, Fraud, Falsification, Serendra, laundering, thousands of dollars, state grant, job-training program, checks"],
            ["reference_id" => 17, "table" => "kases", "tags" => "case, committed 2013-04-30, Indirect assault, Murder, jogging, stray bullet, punctured head, multiple attempts"],
            ["reference_id" => 18, "table" => "kases", "tags" => "case, committed 2013-05-03, Possession, preparation and use of prohibited drugs and maintenance of opium dens, Possession of Dangerous Drugs For Sale, Light Threats, Physical Injuries, drug pusher, defense mechanism, bumped head, metal tube, head scratches, limb bruises"],
            ["reference_id" => 19, "table" => "kases", "tags" => "case, committed 2013-03-29, Rape, Bribery, Grave coercions, Light threats, sexual assault, boyfriend, sexual relations"],
            ["reference_id" => 20, "table" => "kases", "tags" => "case, committed 2013-05-01, Homicide, Indirect assault, Physical Injuries, shooting range, accidental fire"],
            ["reference_id" => 21, "table" => "kases", "tags" => "case, committed 2013-07-02, Possession, preparation and use of prohibited drugs and maintenance of opium dens, Possession of Dangerous Drugs For Sale, Bribery, drug lord, Zamboanga, released from jail, drug dealer"],
            ["reference_id" => 22, "table" => "kases", "tags" => "case, committed 2013-01-15, Murder, stabbed, dead on arrival, ex-girlfriend, roadside, ambush"],
            ["reference_id" => 23, "table" => "kases", "tags" => "case, committed 2013-06-28, Indirect assault, Homicide, Drunk driving, jogging"],
            ["reference_id" => 24, "table" => "kases", "tags" => "case, committed 2013-09-24, Homicide, Robbery, Brigandage, Indirect assault, Physical Injuries, Abandonment of helpless persons, Grave threats, bank, Security Bank, Alabang, four-figure sum of money, orange Tesco bag, taxi cab, black beanie hat, dark waist-length jacket, brown trousers"],
            ["reference_id" => 25, "table" => "kases", "tags" => "case, committed 2013-08-10, Suicide, Vandalism, Public disorder, floor plans failed, getting fired"],
            ["reference_id" => 26, "table" => "kases", "tags" => "case, committed 2013-09-07, Rape, Malicious mischief, Grave coercions, Grave threats, boarding house, driving"],
            ["reference_id" => 27, "table" => "kases", "tags" => "case, committed 2013-10-20, Prostitution, Seduction, pub, Pedro Gil, De La Salle University"],
            ["reference_id" => 28, "table" => "kases", "tags" => "case, committed 2013-10-20, Possession of Dangerous Drugs For Sale, Possession, preparation and use of prohibited drugs and maintenance of opium dens, Illegal assemblies, drug dealing, high school, hideout, drug pusher, Korea"],
            ["reference_id" => 29, "table" => "kases", "tags" => "case, committed 2013-10-12, Rape, Malicious mischief, Grave coercions, Grave threats, uncle, birthday, party, family, nightmares"],
            ["reference_id" => 30, "table" => "kases", "tags" => "case, committed 2013-11-01, Counterfeiting, Falsification, Piracy, fake, cellular phones, mobile phone equipment, Fujitsu, phone chargers, accessories, smartphones, Samsung, Microsoft, Sony, raid, shop"],
            ["reference_id" => 31, "table" => "kases", "tags" => "case, committed 2012-12-18, Murder, Public disorder, Discharge of firearms, De La Salle University, shooting, running away, EGI, apartment, drinking, Sherwood place"],
            ["reference_id" => 32, "table" => "kases", "tags" => "case, committed 2013-06-08, Fraud, Falsification, investment, failure to disclose, overlapping grants, research company"],
            ["reference_id" => 33, "table" => "kases", "tags" => "case, committed 2013-12-03, Falsification, Fraud, funds, phony license, United States, release from jail, sentenced in court"],
            ["reference_id" => 34, "table" => "kases", "tags" => "case, committed 2012-01-10, Falsification, Fraud, sentenced in court, mortgages"],
            ["reference_id" => 35, "table" => "kases", "tags" => "case, committed 2014-02-10, Fraud, Falsification, Possession of Dangerous Drugs For Sale, Possession, preparation and use of prohibited drugs and maintenance of opium dens, gift cards, supermarket, Starbucks, credit cards"],
            ["reference_id" => 36, "table" => "kases", "tags" => "case, committed 2014-01-20, Fraud, lied about finances, executives, Autonomy Corporation PLC, accounting tricks"],
            ["reference_id" => 37, "table" => "kases", "tags" => "case, committed 2014-03-09, Robbery, Brigandage, Public disorder, Discharge of firearms, guns, open ceiling vent, RCBC, renovation, cash box, money, inquirers, bank"],
            ["reference_id" => 38, "table" => "kases", "tags" => "case, committed 2013-05-18, Murder, shooting, road range, apartment, shot to death, police officer"],
            ["reference_id" => 39, "table" => "kases", "tags" => "case, committed 2013-01-15, Arson, elementary school, fire, third degree burns"],
            ["reference_id" => 40, "table" => "kases", "tags" => "case, committed 2013-07-10, Brigandage, Light threats, Grave coercions, supermarket, Sta. Mesa, forced to the ground, owed money"],
            ["reference_id" => 41, "table" => "kases", "tags" => "case, committed 2013-04-04, Mutilation, Grave coercions, Seduction, clitoris, newspaper, driving, bush, knife, cut"],
            ["reference_id" => 42, "table" => "kases", "tags" => "case, committed 2014-12-28, Serious physical injuries, Abuses against chastity, battered, stabbed, chopped, domestic brawl, beating"],
            ["reference_id" => 43, "table" => "kases", "tags" => "case, committed 2013-01-02, Abduction, Kidnapping, Slavery, limbs tied"],
            ["reference_id" => 44, "table" => "kases", "tags" => "case, committed 2013-01-20, Rape, Malicious mischief, Grave coercions, Grave threats, economy, sex without consent, University of Santo Tomas"],
            ["reference_id" => 45, "table" => "kases", "tags" => "case, committed 2012-01-29, Slavery, Exploitation of minors, photo shoots, personal assistant, electrical cords, no contact with family, beating, limbs scarred"],
            ["reference_id" => 46, "table" => "kases", "tags" => "case, committed 2013-02-10, Abandonment of helpless persons, Pasig river, library, copyread, attack"],
            ["reference_id" => 47, "table" => "kases", "tags" => "case, committed 2013-02-27, Prostitution, Possession of Dangerous Drugs For Sale, Possession, preparation and use of prohibited drugs and maintenance of opium dens, coke, cocaine, Diamond Bar, Pedro Gil"],
            ["reference_id" => 48, "table" => "kases", "tags" => "case, committed 2013-03-10, Trespassing, Violation of domicile, private property, Far Eastern University"],
            ["reference_id" => 49, "table" => "kases", "tags" => "case, committed 2013-03-30, Murder, illegal drug injection, dextrose, relationship, panic attack, depression, anger, separation, revenge, complications"],
            ["reference_id" => 50, "table" => "kases", "tags" => "case, committed 2013-03-28, Abuses against chastity, Corruption of minor, Malicious mischief, hotel, child abuse, sexual assault"],
            ["reference_id" => 51, "table" => "kases", "tags" => "case, committed 2013-04-10, Slavery, Exploitation of minors, electrical cords, family"],
            ["reference_id" => 52, "table" => "kases", "tags" => "case, committed 2013-03-15, Brigandage, Discharge of firearms, Batsi Gang, Sta. Mesa, SM, shooting, money, green camouflage fatigues, masks, matching caps"],
            ["reference_id" => 53, "table" => "kases", "tags" => "case, committed 2013-05-10, Brigandage, Theft, bank, meeting, Batsi Gang, money, taxi cab"],
            ["reference_id" => 54, "table" => "kases", "tags" => "case, committed 2013-05-19, Theft, antique jar"],
            ["reference_id" => 55, "table" => "kases", "tags" => "case, committed 2013-04-03, Swindling, money, Japan, yen, food manufacturing and distribution company, Ministry of Agriculture, issued bonds, information packet, loan opportunity, phone call"],
            ["reference_id" => 56, "table" => "kases", "tags" => "case, committed 2013-05-12, Arson, parked cars, scorched buildings, fire, smoldering debris"],
            ["reference_id" => 57, "table" => "kases", "tags" => "case, committed 2013-08-01, Rape, Malicious mischief, Grave coercions, Grave threats, Corruption of minor, Abuses against chastity, pregnancy, condom"],
            ["reference_id" => 58, "table" => "kases", "tags" => "case, committed 2013-07-30, Rape, Malicious mischief, Grave coercions, Grave threats, party, drinks, taxi cab"],
            ["reference_id" => 59, "table" => "kases", "tags" => "case, committed 2013-07-10, Bribery, exchange for showbiz scoop, relationship, Batsi Gang"],
            ["reference_id" => 60, "table" => "kases", "tags" => "case, committed 2013-09-15, Abduction, Kidnapping, Slavery, luring children with clothes and sweets"],
            ["reference_id" => 61, "table" => "kases", "tags" => "case, committed 2013-06-25, Abortion, Twitter, social media"],
            ["reference_id" => 62, "table" => "kases", "tags" => "case, committed 2013-06-15, Murder, Infanticide, cricket practice, beating, cricket bat, head hit, Sports Stadium, knife, stabbed"],
            ["reference_id" => 63, "table" => "kases", "tags" => "case, committed 2013-06-03, Rape, Abuses against chastity, Light threats, parking lot, high school, exchange student"],
            ["reference_id" => 64, "table" => "kases", "tags" => "case, committed 2013-02-10, Theft, radioactive cobalt-60, Makati Memorial Center"],
            ["reference_id" => 65, "table" => "kases", "tags" => "case, committed 2013-02-01, Murder, Parricide, high school, driving, liabilities, financial problems, stop schooling"],
            ["reference_id" => 66, "table" => "kases", "tags" => "case, committed 2013-02-01, Direct assault, Murder, argument, roof, construction, severe blood loss, dead on arrival"],
            ["reference_id" => 67, "table" => "kases", "tags" => "case, committed 2012-12-28, Murder, boyfriend, girlfriend, relationship, anniversary, Christmas car"],
            ["reference_id" => 68, "table" => "kases", "tags" => "case, committed 2013-02-10, Murder, Infanticide, exchange for drugs, marijuana, drug lord, summon"],
            ["reference_id" => 69, "table" => "kases", "tags" => "case, committed 2013-06-01, Robbery, Grave threats, Discharge of firearms, bingo hall, Shoe Salon, strucked in the head several times, handgun, parking lot"],
            ["reference_id" => 70, "table" => "kases", "tags" => "case, committed 2013-01-21, Libel, Mass Communication, college, false accusation, condoned prostitution, publication houses, spreading rumors, radio shows"],
            ["reference_id" => 71, "table" => "kases", "tags" => "case, committed 2009-05-28, Arson, Violation of domicile, affair, abandoned building, fire"],
            ["reference_id" => 72, "table" => "kases", "tags" => "case, committed 2013-01-10, Slander, blog, social media, Legal Schnauzer, corruption, conspiracy, legal, political, first amendment questions"],
            ["reference_id" => 73, "table" => "kases", "tags" => "case, committed 2013-05-30, Libel, defamation, malicious prosecution, maternity ward scuffle, damaged reputation"],
            ["reference_id" => 74, "table" => "kases", "tags" => "case, committed 2013-05-30, Brigandage, Discharge of firearms, Robbery, Light threats, stealing, card numbers, PINs, Citibank, Alabang, bank, skimming machine, card reader, ATM, cameras, keypads, collected numbers, burglary, criminal possession of forgery device"],
            ["reference_id" => 75, "table" => "kases", "tags" => "case, committed 2013-05-29, Rape, Malicious mischief, Grave coercions, boarding house, Malate"],
            ["reference_id" => 76, "table" => "kases", "tags" => "case, committed 2013-09-02, Adultery, Abuses against chastity, Light threats, cheating, family, interview"],
            ["reference_id" => 77, "table" => "kases", "tags" => "case, committed 2010-12-21, Murder, Possession of Dangerous Drugs For Sale, high school, beating, head hit, limbs hit"],
            ["reference_id" => 78, "table" => "kases", "tags" => "case, committed 2010-10-24, Counterfeiting, Falsification, Piracy, Indian, Natraj Pencil, Boroplus antiseptic cream, Raymond, Onida, iPhone 5S, Greenhills"],
            ["reference_id" => 79, "table" => "kases", "tags" => "case, committed 2010-03-10, Counterfeiting, Falsification, fake bills, money, bank payments, manipulation of scanners and printers"],
            ["reference_id" => 80, "table" => "kases", "tags" => "case, committed 2009-11-01, Kidnapping, Slavery, elementary school, St. Scholastica College, pickup truck, license number, garage"],
            //EWPID
            ["reference_id" => 81, "table" => "kases",
                "tags" => "case, committed 2008-10-09, Forgery, Bea Puzon"],
            ["reference_id" => 82, "table" => "kases",
                "tags" => "case, committed 2008-10-10, Gambling, street, Bernice Bassig"],
            ["reference_id" => 83, "table" => "kases",
                "tags" => "case, committed 2008-10-11, Sexual Abuse, Natasha Ocampo"],
            ["reference_id" => 84, "table" => "kases",
                "tags" => "case, committed 2010-10-12, Grave Scandal, Katherine Pascual"],
            ["reference_id" => 85, "table" => "kases",
                "tags" => "case, committed 2010-10-13, Public Disorder, Timi Gatdula"],
            ["reference_id" => 86, "table" => "kases",
                "tags" => "case, committed 2011-10-14, Direct Assault, Mia Serra"],
            ["reference_id" => 87, "table" => "kases",
                "tags" => "case, committed 2011-10-15, Forgery, Elayssa Ferias"],
            ["reference_id" => 88, "table" => "kases",
                "tags" => "case, committed 2011-10-17, Bribery, Pamela Mendiola"],
            ["reference_id" => 89, "table" => "kases",
                "tags" => "case, committed 2011-10-18, Prohibited Transaction, Judith Pasay"],
            ["reference_id" => 90, "table" => "kases",
                "tags" => "case, committed 2013-10-19, Infidelity, Mikaella Makati"],
            //DID
            ["reference_id" => 91, "table" => "kases",
                "tags" => "case, committed 2011-12-02, Disobedience, Junelle Recto"],
            ["reference_id" => 92, "table" => "kases",
                "tags" => "case, committed 2011-12-04, Relevance of Secret, Jesebel Osmena"],
            ["reference_id" => 93, "table" => "kases",
                "tags" => "case, committed 2012-12-05, Maltreatment of Prisoner, SPO1, Michael Enriquez"],
            ["reference_id" => 94, "table" => "kases",
                "tags" => "case, committed 2012-12-07, Usurpation, Corazon Cojuangco"],
            ["reference_id" => 95, "table" => "kases",
                "tags" => "case, committed 2012-12-09, Suicide, James Martinez"],
            ["reference_id" => 96, "table" => "kases",
                "tags" => "case, committed 2012-12-10, Abortion, Lucila Criselda"],
            ["reference_id" => 97, "table" => "kases",
                "tags" => "case, committed 2013-12-11, Infanticide, Fernando Amorsolo"],
            ["reference_id" => 98, "table" => "kases",
                "tags" => "case, committed 2013-12-13, Serious Illegal Detention, Janet Lim Napoles"],
            ["reference_id" => 99, "table" => "kases",
                "tags" => "case, committed 2013-12-15, Kidnapping, Darwin Daroy"],
            ["reference_id" => 100, "table" => "kases",
                "tags" => "case, committed 2013-12-16, Slavery, Enrico Roco"],
            //IPRD
            ["reference_id" => 101, "table" => "kases",
                "tags" => "case, committed 2009-04-25, Drunk Driving, Jonathan Ochoa"],
            ["reference_id" => 102, "table" => "kases",
                "tags" => "case, committed 2009-05-01, Possession of Dangerous Drugs for Sale, Ernesto Villamin"],
            ["reference_id" => 103, "table" => "kases",
                "tags" => "case, committed 2010-05-02, Vandalism, Armando Villena"],
            ["reference_id" => 104, "table" => "kases",
                "tags" => "case, committed 2010-05-03, Robbery, Carlo Sta. Cruz, Patrick Hubalde"],
            ["reference_id" => 105, "table" => "kases",
                "tags" => "case, committed 2011-05-07, Treason, Algeirn Cupido"],
            ["reference_id" => 106, "table" => "kases",
                "tags" => "case, committed 2012-05-09, Espionage, Joey Gutierrez"],
            ["reference_id" => 107, "table" => "kases",
                "tags" => "case, committed 2012-05-08, Robbery, Andy Kanto"],
            ["reference_id" => 108, "table" => "kases",
                "tags" => "case, committed 2012-05-15, Rape, Kevin Macatangay"],
            ["reference_id" => 109, "table" => "kases",
                "tags" => "case, committed 2012-05-16, Domestic Violence, Juan Abadicio"],
            ["reference_id" => 110, "table" => "kases",
                "tags" => "case, committed 2012-05-17, Petty Theft, Abo Acleb"],
            //RAID
            ["reference_id" => 111, "table" => "kases",
                "tags" => "case, committed 2010-01-27, Arbitrary Detention, Carlito Alupido"],
            ["reference_id" => 112, "table" => "kases",
                "tags" => "case, committed 2010-02-01, Expulsion, Samuel Aglipay"],
            ["reference_id" => 113, "table" => "kases",
                "tags" => "case, committed 2010-02-01, Violation of Domicile, Ricardo Aglido"],
            ["reference_id" => 114, "table" => "kases",
                "tags" => "case, committed 2011-02-08, Prohibition, interruption, and dissolution of peaceful meeting, Benigno Afrilami"],
            ["reference_id" => 115, "table" => "kases",
                "tags" => "case, committed 2011-02-09,Rebellion, Daniel Bercasio"],
            ["reference_id" => 116, "table" => "kases",
                "tags" => "case, committed 2011-02-15, Disloyalty, Eclestio Borromeo"],
            ["reference_id" => 117, "table" => "kases",
                "tags" => "case, committed 2013-02-18, Disturbance of Proceedings, Mark Bermudez"],
            ["reference_id" => 118, "table" => "kases",
                "tags" => "case, committed 2013-02-20, Illegal Assemblies, Dave Bermillo"],
            ["reference_id" => 119, "table" => "kases",
                "tags" => "case, committed 2013-02-21, Direct Assault, Annete Cruz"],
            ["reference_id" => 120, "table" => "kases",
                "tags" => "case, committed 2014-02-25, Direct Assault, Angela Criselda"],
            //VAWCD
            ["reference_id" => 121, "table" => "kases",
                "tags" => "case, committed 2009-09-26, Public Disorder, Aubery Catindig"],
            ["reference_id" => 122, "table" => "kases",
                "tags" => "case, committed 2009-09-28, Forgery, Miley Cauricio"],
            ["reference_id" => 123, "table" => "kases",
                "tags" => "case, committed 2010-10-01, Falsification, Ashley Dagonoy"],
            ["reference_id" => 124, "table" => "kases",
                "tags" => "case, committed 2010-10-05, Fraud, Nicole Dalig"],
            ["reference_id" => 125, "table" => "kases",
                "tags" => "case, committed 2011-10-09, Dereliction of Duty, Trixie Duterte"],
            ["reference_id" => 126, "table" => "kases",
                "tags" => "case, committed 2011-10-10, Bribery, Rosanne Fernando"],
            ["reference_id" => 127, "table" => "kases",
                "tags" => "case, committed 2012-10-12, Prohibited Transaction, Rosanne Fuentes"],
            ["reference_id" => 128, "table" => "kases",
                "tags" => "case, committed 2012-10-16, Infidelity, Reggie Faminial"],
            ["reference_id" => 129, "table" => "kases",
                "tags" => "case, committed 2012-10-18, Disobedience, Lauren Marinias"],
            ["reference_id" => 130, "table" => "kases",
                "tags" => "case, committed 2013-10-26, Forgery, Lovely Bueno, Leslie Antonio"],
            //**OBSERVATIONS**//
            ["reference_id" => 1, "table" => "case_observations", "tags" => "observation, subject hates working, subject hates being an assistant to victim"],
            ["reference_id" => 2, "table" => "case_observations", "tags" => "observation, key, vault, keyhole, fingerprints"],
            ["reference_id" => 3, "table" => "case_observations", "tags" => "observation, subject right-handed"],
            ["reference_id" => 4, "table" => "case_observations", "tags" => "observation, funds, stolen"],
            ["reference_id" => 5, "table" => "case_observations", "tags" => "observation, subject bruised on face, bruises, physical blows"],
            ["reference_id" => 6, "table" => "case_observations", "tags" => "observation, medico-legal, fake"],
            ["reference_id" => 7, "table" => "case_observations", "tags" => "observation, victim chronic heart disease, heart problems"],
            ["reference_id" => 8, "table" => "case_observations", "tags" => "observation, Sweep, apartment, Quezon City"],
            ["reference_id" => 9, "table" => "case_observations", "tags" => "observation, fight, morning trash, victim angry, subject stabbed victim"],
            ["reference_id" => 10, "table" => "case_observations", "tags" => "observation, victims engineers shift finished, victims engineers meeting, subject attacked victims"],
            ["reference_id" => 11, "table" => "case_observations", "tags" => "observation, subject army tags, subject names engraved"],
            ["reference_id" => 12, "table" => "case_observations", "tags" => "observation, subject machine catridges left, subject weapons from army"],
            ["reference_id" => 13, "table" => "case_observations", "tags" => "observation, victim depression"],
            ["reference_id" => 14, "table" => "case_observations", "tags" => "observation, victim suicide note, parents, school problems"],
            ["reference_id" => 15, "table" => "case_observations", "tags" => "observation, victim thoughts no purpose in life"],
            ["reference_id" => 16, "table" => "case_observations", "tags" => "observation, suspect education student, victim lecturer of suspect"],
            ["reference_id" => 17, "table" => "case_observations", "tags" => "observation, subject affection"],
            ["reference_id" => 18, "table" => "case_observations", "tags" => "observation, balisong, subject stabbed children, victims sleeping"],
            ["reference_id" => 19, "table" => "case_observations", "tags" => "observation, subject not suffering from hunger, subject wanted to pay bills, financial problems"],
            ["reference_id" => 20, "table" => "case_observations", "tags" => "observation, financial problems, debts"],
            ["reference_id" => 21, "table" => "case_observations", "tags" => "observation, illegal association, foreign nationals membership"],
            ["reference_id" => 22, "table" => "case_observations", "tags" => "observation, subject hideout hospital, San Juan City, St. James Hospital"],
            ["reference_id" => 23, "table" => "case_observations", "tags" => "observation, coke, cocaine, marijuana, weed samples"],
            ["reference_id" => 24, "table" => "case_observations", "tags" => "observation, weed wrappers"],
            ["reference_id" => 25, "table" => "case_observations", "tags" => "observation, Liberty Dollar, private money, native Americans"],
            ["reference_id" => 26, "table" => "case_observations", "tags" => "observation, Chinese subjects masterminds, house husband involved in scam"],
            ["reference_id" => 27, "table" => "case_observations", "tags" => "observation, subject kidnapping, China"],
            ["reference_id" => 28, "table" => "case_observations", "tags" => "observation, elementary school, grade school, high school"],
            ["reference_id" => 29, "table" => "case_observations", "tags" => "observation, subject maniac, subject child adulterer"],
            ["reference_id" => 30, "table" => "case_observations", "tags" => "observation, subject drug dealer, drugs, politicians, actors"],
            ["reference_id" => 31, "table" => "case_observations", "tags" => "observation, subject drug source, Atlanta, Georgia"],
            ["reference_id" => 32, "table" => "case_observations", "tags" => "observation, subject holds grudge against victim"],
            ["reference_id" => 33, "table" => "case_observations", "tags" => "observation, subjects computer professor, subjects science professors"],
            ["reference_id" => 34, "table" => "case_observations", "tags" => "observation, subjects friends, subjects prostitutes before"],
            ["reference_id" => 35, "table" => "case_observations", "tags" => "observation, subjects drug dealers, teenagers, U-belt"],
            ["reference_id" => 36, "table" => "case_observations", "tags" => "observation, subject sex offender, temptation, family"],
            ["reference_id" => 37, "table" => "case_observations", "tags" => "observation, Samsung S4, Google Maps, motion sensors"],
            ["reference_id" => 38, "table" => "case_observations", "tags" => "observation, victim wasted, Sherwood Place"],
            ["reference_id" => 39, "table" => "case_observations", "tags" => "observation, gift certificates, no barcode"],
            ["reference_id" => 40, "table" => "case_observations", "tags" => "observation, receipt, cash transferral"],
            ["reference_id" => 41, "table" => "case_observations", "tags" => "observation, subject fingerprints, cash box, subject taxi driver"],
            ["reference_id" => 42, "table" => "case_observations", "tags" => "observation, cash withdrawal, cash deposits"],
            ["reference_id" => 43, "table" => "case_observations", "tags" => "observation, victim's uncle police officer, theft, murder"],
            ["reference_id" => 44, "table" => "case_observations", "tags" => "observation, victim alone during incident, family members out, fire started"],
            ["reference_id" => 45, "table" => "case_observations", "tags" => "observation, phone lines dead, victim sleeping"],
            ["reference_id" => 46, "table" => "case_observations", "tags" => "observation, subject abduction in China, identity change"],
            ["reference_id" => 47, "table" => "case_observations", "tags" => "observation, victim willing party"],
            ["reference_id" => 48, "table" => "case_observations", "tags" => "observation, subject kidnapping, selfish, targets orphaned children"],
            ["reference_id" => 49, "table" => "case_observations", "tags" => "observation, subject child maltreatment, beating, electrical cord, baseball bat, back, limbs"],
            ["reference_id" => 50, "table" => "case_observations", "tags" => "observation, subject send children to school, subject pays for children's meals"],
            ["reference_id" => 51, "table" => "case_observations", "tags" => "observation, coke, cocaine, distributed to other dealers"],
            ["reference_id" => 52, "table" => "case_observations", "tags" => "observation, free drugs, manipulation, prostitution, seduction"],
            ["reference_id" => 53, "table" => "case_observations", "tags" => "observation, victim subject in a relationship, anniversary, separation"],
            ["reference_id" => 54, "table" => "case_observations", "tags" => "observation, subject cheating, subject hook-up with drug pusher"],
            ["reference_id" => 55, "table" => "case_observations", "tags" => "observation, subject hotel check in, Senate International Hotel, Chinese frequent the hotel"],
            ["reference_id" => 56, "table" => "case_observations", "tags" => "observation, subject child maltreatment, punishment"],
            ["reference_id" => 57, "table" => "case_observations", "tags" => "observation, subject locks up victim, non-compliance, disobedience"],
            ["reference_id" => 58, "table" => "case_observations", "tags" => "observation, subjects organized crime group, Batsi Gang, random places, robbery"],
            ["reference_id" => 59, "table" => "case_observations", "tags" => "observation, matching outfits, subjects trademark, Batsi Gang"],
            ["reference_id" => 60, "table" => "case_observations", "tags" => "observation, subjects waiting inside taxi cab, taxi cab, Batsi Gang"],
            ["reference_id" => 61, "table" => "case_observations", "tags" => "observation, subject targets banks"],
            ["reference_id" => 62, "table" => "case_observations", "tags" => "observation, arson, subject target places are increasing in size, house, commmunity"],
            ["reference_id" => 63, "table" => "case_observations", "tags" => "observation, victim pregnant, pregnancy test positive"],
            ["reference_id" => 64, "table" => "case_observations", "tags" => "observation, victim laboratory tests positive, sexual intercourse, rape"],
            ["reference_id" => 65, "table" => "case_observations", "tags" => "observation, victim handcuff marks, wrists"],
            ["reference_id" => 66, "table" => "case_observations", "tags" => "observation, subject luring strategy, clothes, candies"],
            ["reference_id" => 67, "table" => "case_observations", "tags" => "observation, subject change of heart, feeling alteration"],
            ["reference_id" => 68, "table" => "case_observations", "tags" => "observation, victim left arm and right leg bruises, beating, hitting"],
            ["reference_id" => 69, "table" => "case_observations", "tags" => "observation, victim shot in head, victim blood all over driver's seat and passenger seat of car"],
            ["reference_id" => 70, "table" => "case_observations", "tags" => "observation, drug lord accomplice, drug lord part of Korean gang, Quezon City"],
            ["reference_id" => 71, "table" => "case_observations", "tags" => "observation, subject has marijuana in closet"],
            ["reference_id" => 72, "table" => "case_observations", "tags" => "observation, victim attending bingo nights, Shoe Salon, bingo hall"],
            ["reference_id" => 73, "table" => "case_observations", "tags" => "observation, victim subject in a relationship, subject revenge, murder"],
            ["reference_id" => 74, "table" => "case_observations", "tags" => "observation, subject started fire in kitchen, subject has a mistress"],
            ["reference_id" => 75, "table" => "case_observations", "tags" => "observation, subjects organized crime group, Batsi Gang, subjects obtain information and money by using devices, plotting devices in machines"],
            ["reference_id" => 76, "table" => "case_observations", "tags" => "observation, subjects building skimming machines, ATM machines"],
            ["reference_id" => 77, "table" => "case_observations", "tags" => "observation, subjects target location is a bank, bank"],
            ["reference_id" => 78, "table" => "case_observations", "tags" => "observation, manipulation, rape, boarding house"],
            ["reference_id" => 79, "table" => "case_observations", "tags" => "observation, subject porn addict"],
            ["reference_id" => 80, "table" => "case_observations", "tags" => "observation, victim revelation of subject drug dealing"],
            ["reference_id" => 81, "table" => "case_observations", "tags" => "observation, mass counterfeiting, Indian brands, iPhone 5S, missing chip from Apple"],
            ["reference_id" => 82, "table" => "case_observations", "tags" => "observation, fake bills, Ulysses Grant signatory was altered"],
            ["reference_id" => 83, "table" => "case_observations", "tags" => "observation, subject truck belongs to subject, subject truck used in procurement"],
            ["reference_id" => 84, "table" => "case_observations",
                "tags" => "ballpen, pilot, brand"],
            ["reference_id" => 85, "table" => "case_observations",
                "tags" => "happened, house"],
            ["reference_id" => 86, "table" => "case_observations",
                "tags" => "house, Davao City"],
            ["reference_id" => 87, "table" => "case_observations",
                "tags" => "dice, deck, card"],
            ["reference_id" => 88, "table" => "case_observations",
                "tags" => "Gambling, Ermita, Manila"],
            ["reference_id" => 89, "table" => "case_observations",
                "tags" => "bruises, body"],
            ["reference_id" => 90, "table" => "case_observations",
                "tags" => "underwear, torn, pieces"],
            ["reference_id" => 91, "table" => "case_observations",
                "tags" => "signage, broken"],
            ["reference_id" => 92, "table" => "case_observations",
                "tags" => " subject autism"],
            ["reference_id" => 93, "table" => "case_observations",
                "tags" => "suffer, subject broken nose"],
            ["reference_id" => 94, "table" => "case_observations",
                "tags" => " subject Black-eye,  subject right eye "],
            ["reference_id" => 95, "table" => "case_observations",
                "tags" => "drug, distributed, Marijuana"],
            ["reference_id" => 96, "table" => "case_observations",
                "tags" => "mistress, Mara Medios"],
            ["reference_id" => 97, "table" => "case_observations",
                "tags" => "subject, mute"],
            ["reference_id" => 98, "table" => "case_observations",
                "tags" => "revealed, secret, 4, persons"],
            ["reference_id" => 99, "table" => "case_observations",
                "tags" => "top, secret"],
            ["reference_id" => 100, "table" => "case_observations",
                "tags" => "knuckles, punch"],
            ["reference_id" => 101, "table" => "case_observations",
                "tags" => "punched, 10, times"],
            ["reference_id" => 102, "table" => "case_observations",
                "tags" => "bruises, right, thigh"],
            ["reference_id" => 103, "table" => "case_observations",
                "tags" => "random, guy, talks, jump, James Martinez"],
            ["reference_id" => 104, "table" => "case_observations",
                "tags" => "10, minutes, decide, jump, building"],
            ["reference_id" => 105, "table" => "case_observations",
                "tags" => "poison, kill, baby"],
            ["reference_id" => 106, "table" => "case_observations",
                "tags" => "total, 20, people, killed"],
            ["reference_id" => 107, "table" => "case_observations",
                "tags" => "rode, motorcycle, kidnapping, infant"],
            ["reference_id" => 108, "table" => "case_observations",
                "tags" => "car, Subaru, Forester"],
            ["reference_id" => 109, "table" => "case_observations",
                "tags" => "Shabu, drug"],
            ["reference_id" => 110, "table" => "case_observations",
                "tags" => "total, weight, 10, lbs."],
            ["reference_id" => 111, "table" => "case_observations",
                "tags" => "Fraternity, logo, drawn, wall"],
            ["reference_id" => 112, "table" => "case_observations",
                "tags" => "Luis Vuitton, brand, bag, stolen"],
            ["reference_id" => 113, "table" => "case_observations",
                "tags" => "not, really, spy"],
            ["reference_id" => 114, "table" => "case_observations",
                "tags" => "fake, spy"],
            ["reference_id" => 115, "table" => "case_observations",
                "tags" => "car, Honda Civic"],
            ["reference_id" => 116, "table" => "case_observations",
                "tags" => "incident, motel"],
            ["reference_id" => 117, "table" => "case_observations",
                "tags" => "supporting, evidence, given"],
            ["reference_id" => 118, "table" => "case_observations",
                "tags" => "3, people, expulsion"],
            ["reference_id" => 119, "table" => "case_observations",
                "tags" => "Ricardo, Aglido, convicted"],
            ["reference_id" => 120, "table" => "case_observations",
                "tags" => "Benigno Afrilami, drunk, entered, court, room"],
            ["reference_id" => 121, "table" => "case_observations",
                "tags" => "Daniel Bercasio, subject heart broken, factor"],
            ["reference_id" => 122, "table" => "case_observations",
                "tags" => "non-licensed, tool, assemble, pieces"],
            ["reference_id" => 123, "table" => "case_observations",
                "tags" => "pistol, assault"],
            ["reference_id" => 124, "table" => "case_observations",
                "tags" => "Aubrey Catindig, subject brain damage"],
            ["reference_id" => 125, "table" => "case_observations",
                "tags" => "red, ballpen, forge, signature"],
            ["reference_id" => 126, "table" => "case_observations",
                "tags" => "pending, Philippine National Police"],
            ["reference_id" => 127, "table" => "case_observations",
                "tags" => "victimized, same, place"],
            ["reference_id" => 128, "table" => "case_observations",
                "tags" => "1 Million, pesos, worth, bribing"],
            ["reference_id" => 129, "table" => "case_observations",
                "tags" => "need, money, wife, subject pregnant"],
            //**OBJECTS**//
            ["reference_id" => 1, "table" => "evidence_objects", "tags" => "object, owner Mike Jones, parrying dagger, dagger, blood"],
            ["reference_id" => 2, "table" => "evidence_objects", "tags" => "object, owner JJ Santos, Mendoza C-1934, machine gun"],
            ["reference_id" => 3, "table" => "evidence_objects", "tags" => "object, owner Larry Torres, Mendoza C-1934, machine gun"],
            ["reference_id" => 4, "table" => "evidence_objects", "tags" => "object, owner Larry Torres, Mendoza C-1934, cartridge, full"],
            ["reference_id" => 5, "table" => "evidence_objects", "tags" => "object, owner JJ Santos, Mendoza C-1934, cartridge, almost empty"],
            ["reference_id" => 6, "table" => "evidence_objects", "tags" => "object, owner JJ Santos, Mendoza C-1934, bullet"],
            ["reference_id" => 7, "table" => "evidence_objects", "tags" => "object, owner Larry Torres, Mendoza C-1934, bullet"],
            ["reference_id" => 8, "table" => "evidence_objects", "tags" => "object, owner Gong Wai, knightly dagger, dagger"],
            ["reference_id" => 9, "table" => "evidence_objects", "tags" => "object, owner Kristina Gacutan, balisong, blood"],
            ["reference_id" => 10, "table" => "evidence_objects", "tags" => "object, owner Lebron Anthony Terrence Williams Shawn Kristy, ecstacy, packet"],
            ["reference_id" => 11, "table" => "evidence_objects", "tags" => "object, owner Lebron Anthony Terrence Williams Shawn Kristy, cocaine, packet"],
            ["reference_id" => 12, "table" => "evidence_objects", "tags" => "object, owner Maynard Plumlee, shabu, samples, Taguig, lab"],
            ["reference_id" => 13, "table" => "evidence_objects", "tags" => "object, owner Victorio Ricardo, Astra A-80, bullet"],
            ["reference_id" => 14, "table" => "evidence_objects", "tags" => "object, owner Veronica Co, Beretta 21 Bobcat, pistol"],
            ["reference_id" => 15, "table" => "evidence_objects", "tags" => "object, owner Veronica Co, Beretta 21 Bobcat, bullet"],
            ["reference_id" => 16, "table" => "evidence_objects", "tags" => "object, owner Mariz Tamboa, hunting dagger, dagger, blood"],
            ["reference_id" => 17, "table" => "evidence_objects", "tags" => "object, owner Monica Velasco, Caracal, pistol"],
            ["reference_id" => 18, "table" => "evidence_objects", "tags" => "object, owner Paulo Arcilla, AK-47, bullet"],
            ["reference_id" => 19, "table" => "evidence_objects", "tags" => "object, owner Samson Sanqui, AMD-65, bullet"],
            ["reference_id" => 20, "table" => "evidence_objects", "tags" => "object, owner Sungyeol Choi Myungsoo Choi, packet, heroin"],
            ["reference_id" => 21, "table" => "evidence_objects", "tags" => "object, owner Sean William Parker, Carbon 15 Type 21, bullet"],
            ["reference_id" => 22, "table" => "evidence_objects", "tags" => "object, owner Jackson Kelly, fake, gift certificates, Starbucks"],
            ["reference_id" => 23, "table" => "evidence_objects", "tags" => "object, owner Landon Jordan, Glock 17, pistol"],
            ["reference_id" => 24, "table" => "evidence_objects", "tags" => "object, owner Minami Takahashi, coke, packet"],
            ["reference_id" => 25, "table" => "evidence_objects", "tags" => "object, owner Minami Takahashi, cocaine, packet"],
            ["reference_id" => 26, "table" => "evidence_objects", "tags" => "object, owner Marc Payawal, Nikonov, bullet"],
            ["reference_id" => 27, "table" => "evidence_objects", "tags" => "object, owner Anton Saley, cricket bat, blood"],
            ["reference_id" => 28, "table" => "evidence_objects", "tags" => "object, owner Justin Tomawis, Glock 17, bullet"],
            ["reference_id" => 29, "table" => "evidence_objects", "tags" => "object, owner Aldrich Cabello, cartridge, empty, Parabellum, pistol"],
            ["reference_id" => 30, "table" => "evidence_objects", "tags" => "object, owner Julio Macaraeg, Beretta Cheetah, bullet"],
            ["reference_id" => 31, "table" => "evidence_objects", "tags" => "object, owner Julio Macaraeg, Beretta Cheetah, pistol"],
            ["reference_id" => 32, "table" => "evidence_objects", "tags" => "object, owner Julio Macaraeg, marijuana, packet"],
            ["reference_id" => 33, "table" => "evidence_objects", "tags" => "object, owner Jack Marshall, Montblanc, lighter"],
            ["reference_id" => 34, "table" => "evidence_objects", "tags" => "object, owner Sungyeol Choi, pill, capsule"],
            ["reference_id" => 35, "table" => "evidence_objects", "tags" => "object, owner Rita Castillo, iPhone 5S, imitation, smartphone, cellular phone"],
            ["reference_id" => 60, "table" => "evidence_objects", "tags" => "object, owner Gary Michael Waters, Samsung S4, imitation, smartphone, cellular phone"],
            ["reference_id" => 61, "table" => "evidence_objects", "tags" => "object, owner Gary Michael Waters, Nokia Lumia 620, imitation, smartphone, cellular phone"],
            ["reference_id" => 36, "table" => "evidence_objects",
                "tags" => "object, ballpen, Forgery, 2008-11-30, owner Bea Puzon"],
            ["reference_id" => 37, "table" => "evidence_objects",
                "tags" => "object, Gambling, dice, cards, street, owner Bernice Bassig"],
            ["reference_id" => 38, "table" => "evidence_objects",
                "tags" => "object, Gambling, cards, street, owner Bernice Bassig"],
            ["reference_id" => 39, "table" => "evidence_objects",
                "tags" => "object, Bedsheet, 2008-11-05, Sexual Abuse, owner Natasha Ocampo"],
            ["reference_id" => 40, "table" => "evidence_objects",
                "tags" => "object, Broken, Public Disorder, owner Timi Gatdula"],
            ["reference_id" => 41, "table" => "evidence_objects",
                "tags" => "object, ballpen, Forgery, 2011-11-06, owner Elayssa Ferias"],
            ["reference_id" => 42, "table" => "evidence_objects",
                "tags" => "object, Money, 2011-11-07, owner Pamela Mendiola"],
            ["reference_id" => 43, "table" => "evidence_objects",
                "tags" => "object, Maong pants, suicide, owner James Martinez"],
            ["reference_id" => 44, "table" => "evidence_objects",
                "tags" => "object, suicide, owner James Martinez, Polo shirt"],
            ["reference_id" => 45, "table" => "evidence_objects",
                "tags" => "object, car, owner Jonathan Ochoa, Drunk Driving"],
            ["reference_id" => 46, "table" => "evidence_objects",
                "tags" => "object, paraphernalia, drug, 2009-05-02, owner Ernesto Villamin, Possession of Dangerous Drugs"],
            ["reference_id" => 47, "table" => "evidence_objects",
                "tags" => "object, Shabu, 2009-05-02, owner Ernesto Villamin, Possession of Dangerous Drugs"],
            ["reference_id" => 48, "table" => "evidence_objects",
                "tags" => "object, spray paint, owner Armando Villena, 2009-05-03, Vandalism"],
            ["reference_id" => 49, "table" => "evidence_objects",
                "tags" => "object, owner Carlo Sta. Cruz, house, 2009-05-10, Robbery, Patrick Hubalde"],
            ["reference_id" => 50, "table" => "evidence_objects",
                "tags" => "basement, parking, 2012-05-28, Robbery, owner Andy Kanto"],
            ["reference_id" => 51, "table" => "evidence_objects",
                "tags" => "object, underwear, 2013-05-20, Rape, owner Kevin Macatangay"],
            ["reference_id" => 52, "table" => "evidence_objects",
                "tags" => "object, money, 2013-05-22, Petty Theft, owner Abo Acleb"],
            ["reference_id" => 53, "table" => "evidence_objects",
                "tags" => "object, Tool, assembling, 2013-02-30, Illegal Assemblies, owner Dave Bermillo"],
            ["reference_id" => 54, "table" => "evidence_objects",
                "tags" => "object, Shirt, blood, stain, 2014-02-27, Direct Assault, owner Annete Cruz"],
            ["reference_id" => 55, "table" => "evidence_objects",
                "tags" => "object, Shorts, blood, stain, 2014-02-27, Direct Assault, Annete Cruz"],
            ["reference_id" => 56, "table" => "evidence_objects",
                "tags" => "object, gun, owner Angela Criselda, 2014-02-27, Direct Assault"],
            ["reference_id" => 57, "table" => "evidence_objects",
                "tags" => "object, ballpen, owner Miley Cauricio, 2009-10-04, Forgery"],
            ["reference_id" => 58, "table" => "evidence_objects",
                "tags" => "object, money, 2011-10-13, Bribery, owner Rosanna Fernando"],
            ["reference_id" => 59, "table" => "evidence_objects",
                "tags" => "object, Forgery, device, house, 2013-10-31, owner Lovely Bueno, owner Leslie Antonio"],
            //**RECORDINGS**//
            ["reference_id" => 1, "table" => "evidence_recordings", "tags" => "recording, owner Raymond Cadang, suicide message, financial problems"],
            ["reference_id" => 2, "table" => "evidence_recordings",
                "tags" => "recording, voice record, Sexual Abuse, owner Natasha Ocampo"],
            ["reference_id" => 3, "table" => "evidence_recordings",
                "tags" => "recording, voice record, Grave Scandal, owner Katherine Pascual"],
            ["reference_id" => 4, "table" => "evidence_recordings",
                "tags" => "recording, voice record, Direct Assault, owner Mia Serra"],
            ["reference_id" => 5, "table" => "evidence_recordings",
                "tags" => "recording, voice record, Prohibited Transaction, owner Judith Pasay"],
            ["reference_id" => 6, "table" => "evidence_recordings",
                "tags" => "recording, voice record, top secret, Relevance of Secret, owner Jesebel Osmena"],
            ["reference_id" => 7, "table" => "evidence_recordings",
                "tags" => "recording, voice record, owner Janet Lim Napoles, Serious Illegal Detention"],
            ["reference_id" => 8, "table" => "evidence_recordings",
                "tags" => "recording, voice record, phone call, owner Janet Lim Napoles, Serious Illegal Detention"],
            ["reference_id" => 9, "table" => "evidence_recordings",
                "tags" => "recording, voice record, owner Algeirn Cupido, Treason"],
            ["reference_id" => 10, "table" => "evidence_recordings",
                "tags" => "recording, voice record, owner Samuel Aglipay, Expulsion"],
            ["reference_id" => 11, "table" => "evidence_recordings",
                "tags" => "recording, voice record, owner Daniel Bercasio, girlfriend, Rebellion"],
            ["reference_id" => 12, "table" => "evidence_recordings",
                "tags" => "recording, voice record, owner Rosanne Fuentes, Prohibited Transaction"],
            ["reference_id" => 13, "table" => "evidence_recordings",
                "tags" => "recording, voice record, owner Lovely Bueno, owner Leslie Antonio, Forgery"],
            //**PICTURE**//
            ["reference_id" => 1, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-04-20, engineer, Penelope Balata, multiple, stabs, owner Matteeo Guidicelli"],
            ["reference_id" => 2, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-01-13, engineers, principal, dead, shootout, Surigao, owner Raven Bojos"],
            ["reference_id" => 3, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-01-23, Raymond Cadang, dead, body, jumped, 25th, floor, red, condominium, owner Domingo Arita"],
            ["reference_id" => 4, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-03-03, frozen, body, part, Kristina Gacutan, children, owner Rod Strunk"],
            ["reference_id" => 5, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-02-18, drug, wrappers, owner Recca Madoka"],
            ["reference_id" => 6, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-03-28, counterfeited, coins, owner Atom Araullo"],
            ["reference_id" => 7, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-08-29, drug, lord, Sylvia Ang, owner Efren Jaeger"],
            ["reference_id" => 8, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-10-09, plate, number, Monica Velasco, car, owner Rreuno Velasco"],
            ["reference_id" => 9, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-12-25, fake, cellular, phones, mobile, equipment, owner Biboy Ortiz"],
            ["reference_id" => 10, "table" => "evidence_pictures",
                "tags" => "picture, taken 2014-03-03, fake, gift, cards, owner Kier Legaspi"],
            ["reference_id" => 11, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-04-21, Clarice Ona, damaged, reproductive, organ, owner Jinggo Madamba"],
            ["reference_id" => 12, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-01-13, Hanna Wu, bruises, owner Kevin Durant"],
            ["reference_id" => 13, "table" => "evidence_pictures",
                "tags" => "picture, taken 2012-02-18, Jasper Hans Chua, owner Rick Fox"],
            ["reference_id" => 14, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-06-08, nurses, Marc Payawal, Kenneth Rafal, Charles Rafanan, owner Jayson Castro"],
            ["reference_id" => 15, "table" => "evidence_pictures",
                "tags" => "picture, taken 2012-01-01, stolen, antique, jar, owner Richard Rabago"],
            ["reference_id" => 16, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-09-19, $10M, bribe, owner Ogie Alcasid"],
            ["reference_id" => 17, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-09-30, Sabel Sadural, tweets, abortion, owner Bon Bernales"],
            ["reference_id" => 18, "table" => "evidence_pictures",
                "tags" => "picture, taken 2013-08-08, PIN, credit, card, number, written, paper, owner Ricardo Panganiban"],
            ["reference_id" => 19, "table" => "evidence_pictures",
                "tags" => "picture, taken 2009-12-21, illegal, drugs, owner Jomal Linao"],
            ["reference_id" => 20, "table" => "evidence_pictures",
                "tags" => "picture, taken 2008-10-20, compared, signatories, owner Ricardo Panganiban"],
            //**VIDEO**//
            ["reference_id" => 1, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-01-22, CCTV, footage, elevator, owner Aguilaris Condominium"],
            ["reference_id" => 2, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-02-01, CCTV, footage, agnom gate, owner DLSU"],
            ["reference_id" => 3, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-04-01, CCTV, footage, school, owner Don Bosco Makati"],
            ["reference_id" => 4, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-06-10, CCTV, footage, residents, owner John Doe"],
            ["reference_id" => 5, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-08-01, CCTV, footage, shooting, range, owner Manila Bullet"],
            ["reference_id" => 6, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-09-15, amateur, shooting, owner Jopat Cervantes"],
            ["reference_id" => 7, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-10-08, CCTV, footage, security, bank, owner Security Bank"],
            ["reference_id" => 8, "table" => "evidence_videos",
                "tags" => "video, recorded 2013-01-01, CCTV, footage, EGI, owner EGI Condominium"],
            ["reference_id" => 9, "table" => "evidence_videos",
                "tags" => "video, recorded 2014-03-16, CCTV, footage, RCBC, owner RCBC"],
            //**DOCUMENT**//
            ["reference_id" => 1, "table" => "evidence_document", "tags" => "received 2014-01-26, document, owner Matteo Guidicelli, subject Justin Bieber, theft, high school, Marikina"],
            ["reference_id" => 2, "table" => "evidence_document", "tags" => "received 2014-02-12, document, owner Jay Contreras, victim Maria Aguilar, rape, musician, subject Chris Brown"],
            ["reference_id" => 3, "table" => "evidence_document", "tags" => "received 2014-12-13, document, owner Jonathan Obrero, Public Scandal, subject Logan Alpay, drunk, bulalo, bakery"],
            ["reference_id" => 4, "table" => "evidence_document", "tags" => "received 2009-03-12, document, owner Willie So, Prostitution, subject Kris Aquino, subject Claire Baclayan, waitresses, misdemeanor prostitution"],
            ["reference_id" => 5, "table" => "evidence_document", "tags" => "received 2013-04-23, document, owner Uma Sumbingco, Murder, Mike Jones, engineer, garbage collector, stabbing"],
            ["reference_id" => 6, "table" => "evidence_document", "tags" => "received 2013-01-15, document, owner Raven Bojos, Shootout, engineers, principal, shooting, Surigao"],
            ["reference_id" => 7, "table" => "evidence_document", "tags" => "received 2013-01-26, document, owner Domingo Arita, Suicide, victim Raymond Cadang, Far Eastern University, condominium"],
            ["reference_id" => 8, "table" => "evidence_document", "tags" => "received 2013-02-07, document, owner Pierce Jonota, Murder, De La Salle University, Agno Gate, stabbing, victim stabbed in head"],
            ["reference_id" => 9, "table" => "evidence_document", "tags" => "received 2013-03-06, document, owner Rod Strunk, Cannibalism, subject Kristina Gacutan, mother ate children"],
            ["reference_id" => 10, "table" => "evidence_document", "tags" => "received 2013-02-20, document, owner Recca Madoka, Illegal Gambling, Americans, San Juan"],
            ["reference_id" => 11, "table" => "evidence_document", "tags" => "received 2013-02-20, document, owner Adolf Hitler, Terrorism, bus conductor, Leyte, atomic bomb, bus"],
            ["reference_id" => 12, "table" => "evidence_document", "tags" => "received 2013-04-01, document, owner Atom Araullo, Counterfeiting, subject Chistopher Sese, subject Gong Wai See, subject Karlo Martinez, businessmen, house husband, coins"],
            ["reference_id" => 13, "table" => "evidence_document", "tags" => "received 2013-04-10, document, owner Zee Ambrosio, Adbuction, businessman, China, children"],
            ["reference_id" => 14, "table" => "evidence_document", "tags" => "received 2013-05-03, document, owner Juni Silva, Illegal Drugs, drug dealers, marijuana, Benguet"],
            ["reference_id" => 15, "table" => "evidence_document", "tags" => "received 2013-05-23, document, owner Joey Ty, Illegal Drugs, drug lord, Zamboanga, Taguig"],
            ["reference_id" => 16, "table" => "evidence_document", "tags" => "received 2013-06-10, document, owner Wilhelm Hung, Money Laundering, Serendra, Serendra developers, laundering thousands of dollars, dollars"],
            ["reference_id" => 17, "table" => "evidence_document", "tags" => "received 2013-06-17, document, owner Jose Maria Villacorta, Stray Bullet, gym instructor, shot in head, jogging"],
            ["reference_id" => 18, "table" => "evidence_document", "tags" => "received 2013-07-08, document, owner Kali Kariman, Illegal Drugs, drug pusher, Caloocan"],
            ["reference_id" => 19, "table" => "evidence_document", "tags" => "received 2013-07-27, document, owner Jun Sabayton, Rape, boyfriend, girlfriend, force, sex"],
            ["reference_id" => 20, "table" => "evidence_document", "tags" => "received 2013-08-12, document, owner Mikasa Ackerman, Accidental Shooting, subject Veronica Co, accident, shooting, gun, shooting range"],
            ["reference_id" => 21, "table" => "evidence_document", "tags" => "received 2013-08-29, document, owner Eren Jaeger, Illegal Drugs, subject Sylvia Ang, drug lord, Zamboanga, released from jail"],
            ["reference_id" => 22, "table" => "evidence_document", "tags" => "received 2013-09-11, document, owner Habab Baluda, Inflicing Physical Injuries, subject Mariz Tamboa, paramedic, stabbing"],
            ["reference_id" => 23, "table" => "evidence_document", "tags" => "received 2013-09-22, document, owner Rreuno Velasco, Drunk Driving, subject Monica Velasco, DUI, alcohol, jogging, roadside"],
            ["reference_id" => 24, "table" => "evidence_document", "tags" => "received 2013-09-23, document, owner Martin Quinahan, Robbery, Security Bank, Alabang"],
            ["reference_id" => 25, "table" => "evidence_document", "tags" => "received 2013-10-23, document, owner Jim Paredes, Suicide, victim Jack Baloaloa, architect, Pasay"],
            ["reference_id" => 26, "table" => "evidence_document", "tags" => "received 2013-11-03, document, owner Georges St. Pierre, Rape, subject Richmond Collins, American, accountant, raped co-worker"],
            ["reference_id" => 27, "table" => "evidence_document", "tags" => "received 2013-11-23, document, owner Dim Dumaual, Prostitution, subject Tyrone Tecson, subject Eun Hyuk Park, subject Bert Lee, De La Salle University, professors, pubs, Pedro Gil"],
            ["reference_id" => 28, "table" => "evidence_document", "tags" => "received 2013-12-01, document, owner Herbert Bautista, Illegal Drug Dealing, subject Sungyeol Choi, subject Myungsoo Choi, Korean, students, Quezon"],
            ["reference_id" => 29, "table" => "evidence_document", "tags" => "received 2013-12-18, document, owner Matthew McDonald, Rape, subject Gary Michael Waters, uncle raped niece, niece birthday"],
            ["reference_id" => 30, "table" => "evidence_document", "tags" => "received 2013-12-28, document, owner Biboy Ortiz, Counterfeiting, subject Johnson Smith, subject Simon Davis, African-American, businessmen, fake, cellular phones, mobile phone equipment"],
            ["reference_id" => 31, "table" => "evidence_document", "tags" => "received 2013-01-02, document, owner Scott Brooks, Murder, victim Gino Haparam, De La Salle University, shooting, EGI, apartment, Manila"],
            ["reference_id" => 32, "table" => "evidence_document", "tags" => "received 2013-04-18, document, owner Gumba Sotto, Fraud, subject Mark Anthony Collins, subject Jacob Reed, butcher, fireman"],
            ["reference_id" => 33, "table" => "evidence_document", "tags" => "received 2014-01-13, document, owner Jobert Sucaldito, Fraud, subject Matthew Morgan, American, fireman, contractor's license, funds"],
            ["reference_id" => 34, "table" => "evidence_document", "tags" => "received 2014-02-04, document, owner Luke Walton, Fraud, subject Liam Morgan, American, manager, sentenced to court, defrauding Filipino businessman"],
            ["reference_id" => 35, "table" => "evidence_document", "tags" => "received 2014-03-05, document, owner Kier Legaspi, Fraud, subject Jackson Kelly, gift cards"],
            ["reference_id" => 36, "table" => "evidence_document", "tags" => "received 2014-01-28, document, owner Ramone Parica, Fraud, subject Ryan Dylan Wood, mastermind, multi-billion dollar fraud, dollars"],
            ["reference_id" => 37, "table" => "evidence_document", "tags" => "received 2014-03-18, document, owner Lanus Crassus, Robbery, masked men, RCBC, Quezon"],
            ["reference_id" => 38, "table" => "evidence_document", "tags" => "received 2013-05-29, document, owner Bill Laimbeer, Road Rage Shooting, subject Landon Jordan, Australian, politician, range shooting, multiple deaths"],
            ["reference_id" => 39, "table" => "evidence_document", "tags" => "received 2013-02-02, document, owner Jack Nicholson, Arson, subject Jack Marshall, Australian, Politician, elementary school, teacher, house, fire"],
            ["reference_id" => 40, "table" => "evidence_document", "tags" => "received 2013-07-13, document, owner Boom Gonzalez, Robbery, subject Connor Charles Hunter, Australian, pilot, robbing, IT professional, supermarket, Sta. Mesa"],
            ["reference_id" => 41, "table" => "evidence_document", "tags" => "received 2013-04-24, document, owner Jinggo Madamba, Female Mutilation, subject Lay Zhang, San Beda, student, victim Clarice Ona"],
            ["reference_id" => 42, "table" => "evidence_document", "tags" => "received 2013-01-16, document, owner Kevin Durant, Battered Wife, subject Yi Wu, battered wife, victim Hanna Wu"],
            ["reference_id" => 43, "table" => "evidence_document", "tags" => "received 2013-01-26, document, owner Serge Ibaka, Kidnapping, subject Ming Chiu, Chinese, plumber, slavery"],
            ["reference_id" => 44, "table" => "evidence_document", "tags" => "received 2013-02-07, document, owner Ming Yao, Rape, subject Ming Chiu, Chinese, plumber, business student"],
            ["reference_id" => 45, "table" => "evidence_document", "tags" => "received 2012-02-20, document, owner Rick Fox, Child Abduction, subject Bing Ng, victim Jasper Hans Chua"],
            ["reference_id" => 46, "table" => "evidence_document", "tags" => "received 2013-03-05, document, owner Derek Fisher, Abandonment of a Helpless Person, Chuan Tsui"],
            ["reference_id" => 47, "table" => "evidence_document", "tags" => "received 2013-03-30, document, owner Rob Thomas, Illegal Drug Possession, subject Minami Takahashi, hotel, Pedro Gil"],
            ["reference_id" => 48, "table" => "evidence_document", "tags" => "received 2013-03-20, document, owner Johnny Abarrientos, Trespassing, subject Atsuko Maeda, AKB48, provate property, Quezon"],
            ["reference_id" => 49, "table" => "evidence_document", "tags" => "received 2013-04-01, document, owner Michael Bibby, Medical Malpractice, subject Sakura Yamamoto, Japan, nurse, injection, illegal drug, patient"],
            ["reference_id" => 50, "table" => "evidence_document", "tags" => "received 2013-04-01, document, owner Simon Atkins, Child Abuse, subject Bing Ng, threatening, Filipino-American"],
            ["reference_id" => 51, "table" => "evidence_document", "tags" => "received 2013-05-22, document, owner Beau Belga, Slavery, subject Bing Ng, victim Bo Ng"],
            ["reference_id" => 52, "table" => "evidence_document", "tags" => "received 2013-06-12, document, owner Jayson Castro, Brigandage, subject Batsi Gang, SM, Sta. Mesa"],
            ["reference_id" => 53, "table" => "evidence_document", "tags" => "received 2013-06-17, document, owner Mark Caguioa, Brigandage, subject Batsi Gang, robbery, victim Rafael Lazo"],
            ["reference_id" => 54, "table" => "evidence_document", "tags" => "received 2013-05-23, document, owner June Mar Fajardo, Theft, Vietnamese, antique jar, victim Richard Rabago, businessman"],
            ["reference_id" => 55, "table" => "evidence_document", "tags" => "received 2013-07-28, document, owner Marko Moraga, Swindling, subject Watanabe Mayu, victim Vice Ganda, actor"],
            ["reference_id" => 56, "table" => "evidence_document", "tags" => "received 2013-08-11, document, owner Dick Joaquin, Arson, subject Jack Marshall, cars, buildings, public disturbance"],
            ["reference_id" => 57, "table" => "evidence_document", "tags" => "received 2013-08-30, document, owner Migo Elisan, Rape, subject Chris Brown, suspected father, victim Stephanie Germanotta"],
            ["reference_id" => 58, "table" => "evidence_document", "tags" => "received 2013-09-10, document, owner Mark Heussaff, Rape, subject Chris Brown, victim Anne Curtis-Smith, actress"],
            ["reference_id" => 59, "table" => "evidence_document", "tags" => "received 2013-09-21, document, owner Ogie Alcasid, Bribery, subject Christian Tiangco, victim Boy Abunda, showbiz"],
            ["reference_id" => 60, "table" => "evidence_document", "tags" => "received 2013-10-12, document, owner Rally Coronacion, Kidnapping, subject Ming Li Chiu, abduction, children, human trafficking"],
            ["reference_id" => 61, "table" => "evidence_document", "tags" => "received 2013-10-15, document, owner Bon Bernales, Abortion, subject Sabel Sadural, social media"],
            ["reference_id" => 62, "table" => "evidence_document", "tags" => "received 2013-10-12, document, owner Rajko Toriman, Infanticide, subject Anton Saley, killed son, cricket practice"],
            ["reference_id" => 63, "table" => "evidence_document", "tags" => "received 2013-06-04, document, owner Thomas Cruz, Rape, subject Yamato Akitsuki, Japanese, exchange student, raped professor"],
            ["reference_id" => 64, "table" => "evidence_document", "tags" => "received 2008-12-15, document, owner Ricardo Panganiban, Theft, subject Karla Talaba, Makati Memorial Center, cobalt-60"],
            ["reference_id" => 65, "table" => "evidence_document", "tags" => "received 2013-06-10, document, owner Michael Millanes, Parricide, subject Justin Tomawis, killed father, driving"],
            ["reference_id" => 66, "table" => "evidence_document", "tags" => "received 2013-06-10, document, owner Ernie Escayde, Murder, subject Albert Agonoy, welder, pushed off roof, argument"],
            ["reference_id" => 67, "table" => "evidence_document", "tags" => "received 2008-12-15, document, owner Ramil de Jesus, Murder, subject Aldrich Cabello, killed girlfriend, victim Mica Reyes, car"],
            ["reference_id" => 68, "table" => "evidence_document", "tags" => "received 2008-12-15, document, owner Jejomar Binay, Murder, subject Julio Macaraeg, killed son, victim MJ Macaraeg, exchange for drugs, marijuana"],
            ["reference_id" => 69, "table" => "evidence_document", "tags" => "received 2013-07-27, document, owner Juliano Panganiban, Robbery, subject Sebastian Hastings, bingo hall, physical injuries, Centro Escolar University, nursing, student"],
            ["reference_id" => 70, "table" => "evidence_document", "tags" => "received 2013-04-01, document, owner Lou Chua, Libel, subject Anthony Manalo, false accusation, victim Jim Dwyer"],
            ["reference_id" => 71, "table" => "evidence_document", "tags" => "received 2009-07-27, document, owner John Paul Fernandez, Adultery, subject Jack Marshall, affair, abandoned building, fire"],
            ["reference_id" => 72, "table" => "evidence_document", "tags" => "received 2013-04-01, document, owner Jomari Yllana, Slander, subject Allan Cardona, corruption"],
            ["reference_id" => 73, "table" => "evidence_document", "tags" => "received 2013-08-10, document, owner Ricardo Panganiban, Defamation, Malicious Prosecution, subject Landon Jordan, Australian, politician, maternity ward"],
            ["reference_id" => 74, "table" => "evidence_document", "tags" => "received 2013-08-10, document, owner Ricardo Panganiban, Robbery, subject Paulo Arcilla, subject Samson Sangui, card numbers"],
            ["reference_id" => 75, "table" => "evidence_document", "tags" => "received 2013-08-10, document, owner Ricardo Panganiban, Rape, subject Richmond Collins, American, Korean, student, victim Krystal Jung, boarding house, Malate"],
            ["reference_id" => 76, "table" => "evidence_document", "tags" => "received 2013-09-13, document, owner Enzo Ortiz, Adultery, subject Lance Kurtis Alipio, cheated on wife, raped niece"],
            ["reference_id" => 77, "table" => "evidence_document", "tags" => "received 2010-01-13, document, owner Jomal Linao, Murder, subject Sungyeol Choi, drug dealing, high school, student"],
            ["reference_id" => 78, "table" => "evidence_document", "tags" => "received 2010-12-30, document, owner Gus Abelgas, Counterfeiting, iPhone, Greenhills, shopping center"],
            ["reference_id" => 79, "table" => "evidence_document", "tags" => "received 2010-12-03, document, owner Noli De Castro, Counterfeiting, subject Gong Wai See, fake bills, dollars"],
            ["reference_id" => 80, "table" => "evidence_document", "tags" => "received 2009-12-23, document, owner Julius Babao, Kidnapping, subject Xiong Chua, Chinese, businessman"],
        );

        // Uncomment the below to run the seeder
        DB::table('tags')->insert($tags);
    }

}
