<?php

class Case_observationsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('case_observations')->truncate();

        $case_observations = array(
            //83 ALL JANINE
            ["case_id" => 1, "user_id" => 10930216, "observation" => "The subject hates working for the principal as an assistant."],
            ["case_id" => 1, "user_id" => 10930216, "observation" => "The subject left the key in the vault keyhole. His fingerprints were on the keys."],
            ["case_id" => 1, "user_id" => 10930216, "observation" => "The subject is right-handed."],
            ["case_id" => 1, "user_id" => 10930216, "observation" => "More than Php 100,000 of the funds was stolen."],
            ["case_id" => 2, "user_id" => 10930216, "observation" => "The subject is badly bruised in the face, suffering physical blows in the stomach as well."],
            ["case_id" => 2, "user_id" => 10930216, "observation" => "The medico-legal is a fake."],
            ["case_id" => 5, "user_id" => 10930216, "observation" => "The victim has a chronic heart disease."],
            ["case_id" => 5, "user_id" => 10930216, "observation" => "The apartment is identified to be the Sweep apartment in Quezon City."],
            ["case_id" => 5, "user_id" => 10930216, "observation" => "The subject and victim were fighting about the morning trash and which to recycle. The victim got angry and all of a sudden the subject stabbed her."],
            ["case_id" => 6, "user_id" => 10930216, "observation" => "The 2 engineers just finished their shift that night and they were meeting with up with the principal when they were attacked by the subjects."],
            //11
            ["case_id" => 6, "user_id" => 10930216, "observation" => "The tags left are believed to belong to the army and the subjects' names are engraved."],
            ["case_id" => 6, "user_id" => 10930216, "observation" => "Machine gun cartidges left belong to the alleged weapons used in the attack, also from the army."],
            ["case_id" => 7, "user_id" => 10930216, "observation" => "The victim has been depressed for months."],
            ["case_id" => 7, "user_id" => 10930216, "observation" => "The victim left a supposed suicide note to his parents, telling them about his problems in school."],
            ["case_id" => 7, "user_id" => 10930216, "observation" => "The victim thinks that he no longer has purpose in life which resulted to the gruesome suicide."],
            ["case_id" => 8, "user_id" => 10930216, "observation" => "The victim is an assistant lecturer for education students, and the subject is believed to have been her student."],
            ["case_id" => 8, "user_id" => 10930216, "observation" => "The subject did not want to give up on the victim in terms of showing signs of affection."],
            ["case_id" => 9, "user_id" => 10930216, "observation" => "The subject used her balisong for cutting her plants to stab her children while they were sleeping."],
            ["case_id" => 9, "user_id" => 10930216, "observation" => "The subject didn't eat her children because she was hungry, she wanted them out of her life so that she can pay the bills well."],
            ["case_id" => 9, "user_id" => 10930216, "observation" => "Their family has been suffering from financial debts in the past 2 years."],
            //21
            ["case_id" => 10, "user_id" => 10930216, "observation" => "The subjects have been uplholding their illegal association and extending membership to foreign nationals in the country."],
            ["case_id" => 10, "user_id" => 10930216, "observation" => "The subjects' hideout is an abandoned hospital in San Juan City, named St. James Hospital in the 1900s."],
            ["case_id" => 10, "user_id" => 10930216, "observation" => "Drugs involved include coke, cocaine, marijuana and a couple of samples of weed."],
            ["case_id" => 10, "user_id" => 10930216, "observation" => "Traces of weed wrappers have been identified to scatter in the community."],
            ["case_id" => 12, "user_id" => 10930216, "observation" => "Liberty Dollar is a private money used by the native Americans in the 1800s."],
            ["case_id" => 12, "user_id" => 10930216, "observation" => "The Chinese subjects are believed to have started the ordeal and the house husband was just involved recently in the scam."],
            ["case_id" => 13, "user_id" => 10930216, "observation" => "The subject is believed to have been kidnapping kids in China before."],
            ["case_id" => 13, "user_id" => 10930216, "observation" => "The subject frequents grade schools and high schools to look for his next target."],
            ["case_id" => 13, "user_id" => 10930216, "observation" => "Sources say he is a maniac and child adulterer in nature."],
            ["case_id" => 15, "user_id" => 10930217, "observation" => "The subject has dealt drugs to politicians and actors in the past."],
            //31
            ["case_id" => 15, "user_id" => 10930217, "observation" => "The subject gets the drugs from a source in Atlanta, Georgia."],
            ["case_id" => 23, "user_id" => 10930217, "observation" => "The subject has been targeting the victim as she holds a grudge against her."],
            ["case_id" => 27, "user_id" => 10930217, "observation" => "Tecson is a computer professor and Lee and Park are science professors in DLSU."],
            ["case_id" => 27, "user_id" => 10930217, "observation" => "The subjects are all believed to be friends. Tecson and Lee go way back when they started as prostitutes before being professors."],
            ["case_id" => 28, "user_id" => 10930217, "observation" => "The subjects have been dealing drugs to teenagers in U-belt area."],
            ["case_id" => 29, "user_id" => 10930217, "observation" => "Waters has been a sex offender in his hometown and was tempted when he visited his family in the Philippines."],
            ["case_id" => 30, "user_id" => 10930217, "observation" => "The Samsung S4 units all lack the Google Maps feature and do not respond to the motion sensors."],
            ["case_id" => 31, "user_id" => 10916644, "observation" => "The victim was badly wasted and came from Sherwood Place."],
            ["case_id" => 35, "user_id" => 10916644, "observation" => "The gift certificates acquired do not have a barcode."],
            ["case_id" => 36, "user_id" => 10916645, "observation" => "The receipt for cash transferral is dated 2 months before the transaction was made."],
            //41
            ["case_id" => 37, "user_id" => 10916645, "observation" => "The fingerprints found on the cash box appear to belong to the taxi driver who is a subject."],
            ["case_id" => 37, "user_id" => 10916645, "observation" => "Both subjects have been inquiring about cash withdrawal and deposits a month before the incident."],
            ["case_id" => 38, "user_id" => 10916645, "observation" => "The victim's uncle is part of a case investigation about theft and murder regarding the subject in the past."],
            ["case_id" => 39, "user_id" => 10916645, "observation" => "The victim was the only one inside the house at that time, and her family members were out when the fire started."],
            ["case_id" => 39, "user_id" => 10916645, "observation" => "The victim could not call for help as their phone lines were dead and she was sleeping."],
            ["case_id" => 43, "user_id" => 10916646, "observation" => "The subject has been adbucting kids back in China. He has been doing this without being caught for years now and has been changing his identity."],
            ["case_id" => 44, "user_id" => 10916646, "observation" => "The victim was a willing party at first."],
            ["case_id" => 45, "user_id" => 10916647, "observation" => "The subject has been kidnapping kids for his selfish purposes, he mostly targets children who are orphaned."],
            ["case_id" => 45, "user_id" => 10916647, "observation" => "The subject maltreats children either by beating them with electrical cords and or baseball bats, usually on their backside and or their limbs if they disobey."],
            ["case_id" => 45, "user_id" => 10916647, "observation" => "The subject still send the children to school and pays for their meals."],
            //51
            ["case_id" => 47, "user_id" => 10916647, "observation" => "Coke and cocaine are usually the drugs distributed to other dealers by the subject."],
            ["case_id" => 47, "user_id" => 10916647, "observation" => "The subject hands over the drug for free and lets her customers pay for it by manipulating them through prostitution and seduction."],
            ["case_id" => 49, "user_id" => 10916647, "observation" => "The victim has been with the subject for over 7 years already only to break it off on their anniversary due to unknown reasons."],
            ["case_id" => 49, "user_id" => 10916647, "observation" => "The subject has been speculated to have been cheating on the victim by hooking up with a drug pusher."],
            ["case_id" => 50, "user_id" => 10916647, "observation" => "The subject has been reported to check in Senate International Hotel, a hotel frequently visited by Asians especially the Chinese."],
            ["case_id" => 51, "user_id" => 10916648, "observation" => "It has been found out that the subject maltreats his own son alongside punishing him when his orders are not followed."],
            ["case_id" => 51, "user_id" => 10916648, "observation" => "The subject sometimes locks his son inside his room when he does comply to what his father wishes."],
            ["case_id" => 52, "user_id" => 10916648, "observation" => "The subjects are part of an organized crime group called Batsi Gang who rob people in random places."],
            ["case_id" => 52, "user_id" => 10916648, "observation" => "Matching outfits are usually their trademark when they commit crime."],
            ["case_id" => 53, "user_id" => 10916648, "observation" => "While one of the subjects snuck into the bank, the other members of the organized crime group Batsi Gang were waiting inside the cab."],
            //61
            ["case_id" => 52, "user_id" => 10916648, "observation" => "The subjects principally target banks. It is unknown if they deploy themselves in a fixed time where there are people or not."],
            ["case_id" => 56, "user_id" => 10916649, "observation" => "The subject has been charged of arson in the past, and his target places are getting larger. Last time, he only targeted a house, now he has targetted a whole community."],
            ["case_id" => 57, "user_id" => 10916649, "observation" => "The pregnancy test of the victim showed positive."],
            ["case_id" => 58, "user_id" => 10916649, "observation" => "The laboratory tests of the victim has shown signs that she had undergone sexual intercourse and has been indeed raped."],
            ["case_id" => 58, "user_id" => 10916649, "observation" => "The victim has handcuff marks on her wrists."],
            ["case_id" => 60, "user_id" => 10916649, "observation" => "The subject's strategy has been reported to be luring children into fancying material things such as clothes and candies he shows them."],
            ["case_id" => 62, "user_id" => 10916650, "observation" => "The subject has been reported to love his son very much, but abhorred him all of a sudden on the week of the incident."],
            ["case_id" => 63, "user_id" => 10916650, "observation" => "The victim has bruises on her left arm and right leg which are believed to be hit by the subject."],
            ["case_id" => 65, "user_id" => 10916650, "observation" => "The victim has been shot in the head and blood was all over the driver seat and passenger seat of the car."],
            ["case_id" => 68, "user_id" => 10916651, "observation" => "The drug lord is identified to be a part of a Korean gang in Quezon City."],
            //71
            ["case_id" => 68, "user_id" => 10916651, "observation" => "The subject has a stash of marijuana found in his closet, and he must have needed more of it, thus the assualt to his son."],
            ["case_id" => 69, "user_id" => 10916651, "observation" => "The victim has been attending bingo nights at Shoe Salon bingo hall every Fridays after her shift where she was targeted by the subject."],
            ["case_id" => 69, "user_id" => 10916651, "observation" => "The subject is speculated to have had a relationship with the victim in the past and sought revenge by murdering her."],
            ["case_id" => 71, "user_id" => 10916652, "observation" => "The subject has been said to have started the fire in the kitchen of his mistress after visiting her home."],
            ["case_id" => 74, "user_id" => 10916652, "observation" => "The subjects, as speculated to be part of the organized crime group Batsi Gang has now been experimenting on plotting devices on machines to obtain information about card holders as well as money from their accounts."],
            ["case_id" => 74, "user_id" => 10916652, "observation" => "The subjects have been reported to have been building their own skimming machines for various ATM machines nationwide. However, this is their first attempt for this year."],
            ["case_id" => 74, "user_id" => 10916652, "observation" => "The target location is still a bank, which relates to all of their past crimes."],
            ["case_id" => 75, "user_id" => 10916652, "observation" => "The subject has a habit of manipulating and raping women in boarding houses across the nation."],
            ["case_id" => 75, "user_id" => 10916652, "observation" => "The subject is most likely a porn addict."],
            ["case_id" => 77, "user_id" => 10916653, "observation" => "The victim was probably going to rat on the subject's drug dealing, that's why he was killed."],
            //81
            ["case_id" => 78, "user_id" => 10916653, "observation" => "The subjects have been mass counterfeiting Indian brands even in other countries. A iPhone 5S unit does not operate like an original iPhone 5S and it missing a chip uniquely obtained from Apple."],
            ["case_id" => 78, "user_id" => 10916653, "observation" => "The fake $50 bills' signatory of Ulysses Grant has been altered to make it look like his."],
            ["case_id" => 80, "user_id" => 10916653, "observation" => "Judging from the truck's plate number, it does indeed belong to the subject. The truck has been used for company operations such as procurement of goods."],
            //84 START KIER
            ["case_id" => 81, "user_id" => 10930204, "observation" => "The agent found out that the ballpen used was Pilot brand"],
            ["case_id" => 81, "user_id" => 10930204, "observation" => "The case happened in the house of the subject"],
            ["case_id" => 81, "user_id" => 10930204, "observation" => "The house of the subject is located at Davao City"],
            ["case_id" => 82, "user_id" => 10930204, "observation" => "There are 2 dice and 3 decks of card used"],
            ["case_id" => 82, "user_id" => 10930204, "observation" => "Gambling place is located at Eermita, Manila"],
            ["case_id" => 83, "user_id" => 10930204, "observation" => "There are alot of bruises found on the body of the victim"],
            ["case_id" => 83, "user_id" => 10930204, "observation" => "The underwear of the victim was torn into pieces"],
            ["case_id" => 84, "user_id" => 10930205, "observation" => "A signage was found broken at the crime scene"],
            ["case_id" => 85, "user_id" => 10930205, "observation" => "Timi Gatdula has autism"],
            ["case_id" => 86, "user_id" => 10930205, "observation" => "The victim suffer from a broken nose"],
            ["case_id" => 86, "user_id" => 10930205, "observation" => "Black-eye on the right eye of the victim was founded"],
            ["case_id" => 89, "user_id" => 10930206, "observation" => "The drug being distributed was Marijuana"],
            ["case_id" => 90, "user_id" => 10930206, "observation" => "The name of mistress is Mara Medios"],
            ["case_id" => 91, "user_id" => 10930201, "observation" => "The subject was found mute"],
            ["case_id" => 92, "user_id" => 10930201, "observation" => "The subject reavealed the secret to 4 persons"],
            ["case_id" => 92, "user_id" => 10930201, "observation" => "Top secret was revealed"],
            ["case_id" => 93, "user_id" => 10930201, "observation" => "The subject used knuckles to punch the victim"],
            ["case_id" => 93, "user_id" => 10930201, "observation" => "The subject punched the victim 10 times in the face"],
            ["case_id" => 93, "user_id" => 10930201, "observation" => "Bruises on the right thigh was found"],
            ["case_id" => 95, "user_id" => 10930202, "observation" => "A random guy talks to James Martinez and tell not to jump"],
            ["case_id" => 95, "user_id" => 10930202, "observation" => "It took 10 minutes for James Martinez to decide to jump in the building"],
            ["case_id" => 97, "user_id" => 10930202, "observation" => "Poison was being used to kill the baby"],
            ["case_id" => 98, "user_id" => 10930202, "observation" => "Total of 20 people was killed by the subject"],
            ["case_id" => 99, "user_id" => 10930203, "observation" => "The subject rode a motorcycle after kidnapping an infant"],
            ["case_id" => 101, "user_id" => 10930207, "observation" => "The car used by the subject was Subaru Forester"],
            ["case_id" => 102, "user_id" => 10930207, "observation" => "Shabu was the drug involved in the case"],
            ["case_id" => 102, "user_id" => 10930207, "observation" => "Total weight of Shabu was 10 lbs."],
            ["case_id" => 102, "user_id" => 10930207, "observation" => "The shabu was found inside a car"],
            ["case_id" => 103, "user_id" => 10930207, "observation" => "Fraternity logo was drawn in the wall"],
            ["case_id" => 104, "user_id" => 10930208, "observation" => "Luis Vuitton was the brand of the bag being stolen"],
            ["case_id" => 105, "user_id" => 10930208, "observation" => "The agent found out that the subject was not really a spy of his own country"],
            ["case_id" => 106, "user_id" => 10930208, "observation" => "The agent foun out that the subject is a fake spy"],
            ["case_id" => 107, "user_id" => 10930208, "observation" => "The car of the victim was a Honda Civic"],
            ["case_id" => 108, "user_id" => 10930208, "observation" => "The incident happened in a motel"],
            ["case_id" => 111, "user_id" => 10930210, "observation" => "No supporting evidence can be given by the victim"],
            ["case_id" => 112, "user_id" => 10930210, "observation" => "There are 3 people involved in the expulsion but the victim only complained"],
            ["case_id" => 113, "user_id" => 10930210, "observation" => "Ricardo Aglido was an ex convicted person"],
            ["case_id" => 114, "user_id" => 10930210, "observation" => "Benigno Afrilami was drunk when he entered the court room"],
            ["case_id" => 115, "user_id" => 10930211, "observation" => "Daniel Bercasio was heart broken, it is one of the factors why he commit rebellion"],
            ["case_id" => 118, "user_id" => 10930212, "observation" => "Non-licensed tool was used to assemble the pieces"],
            ["case_id" => 119, "user_id" => 10930212, "observation" => "The subject used a pistol in order to assault the victim"],
            ["case_id" => 121, "user_id" => 10930213, "observation" => "The agent found out that Aubrey Cantindig has a brain damage"],
            ["case_id" => 122, "user_id" => 10930213, "observation" => "A red ballpen was used to forge the signature"],
            ["case_id" => 123, "user_id" => 10930213, "observation" => "The subject has a pending case in the Philippine National Police"],
            ["case_id" => 124, "user_id" => 10930214, "observation" => "The subject victimized alot of people in the same place"],
            ["case_id" => 126, "user_id" => 10930214, "observation" => "1 Million pesos worth was used by the subject in bribing"],
            ["case_id" => 127, "user_id" => 10930214, "observation" => "The subject is in need of money because his wife was pregnant"],

//**********************************************************************************************************************************************************

            ["case_id" => 131, "user_id" => 10940445, "observation" => "Nine (9) eyewitnesses before, during and after the incident and were near the crime scene identified the suspects. Some of them saw DIMA SAMPULNA ride in the black motorcycle driven by JOSE SAMPULNA. Another eyewitness saw ROBERT ATO drove the Honda XRM where JIMMY ATO rode with him."],
            ["case_id" => 132, "user_id" => 10940447, "observation" => "The syndicate uses different nationalities to deliver or pick up the drugs to mislead authorities of their modus operandi. Earlier, an information was received by the NBI that a West African Drug Syndicate (WADS) based in Africa shipped into the country an undetermined quantity of cocaine and shabu on March 23, 2012. A courier by the name of Bing Sye Poh was sent by the group to the Philippines via Air Asia Flight No. AK 1438, Clark Terminal, Pampanga to pick up the luggage/suitcase and transport it to its final destination. Poh was billeted at Crosswinds Asian Hotel in Parañaque area. NBI operatives continued to check his whereabouts."],
            ["case_id" => 133, "user_id" => 10940446, "observation" => "NBI undercover operatives were able to trace the source in Bgy. Samasapi, North Fairview, Quezon City and bought from suspects a .45 caliber pistol on March 2, 2012 and a 9 mm sub-machine gun on March 15, 2012, with magazines and ammunitions. After the initial purchases, NBI operatives conducted a buy-bust operation near their residence on March 27, 2012 resulting to the arrest of the suspects, Orogan and Langco. It is also believed that they were among those responsible for the proliferation of loose firearms in the streets which are being used by the 'riding in tandem' robbery/hold-up gang."],
            ["case_id" => 134, "user_id" => 10940444, "observation" => "On April 19, 2012 suspect MICARES executed an extra judicial confession assisted by his lawyers and admitted the crime. He recounted that, on the midnight of March 22, 2012, he was heavily drunk and went to Doña Juana Subdivision. He was refused entry by the guard at Gate 3 but he managed to sneak in through the gate's small hole and proceeded to the victim's house."],
            ["case_id" => 135, "user_id" => 10940445, "observation" => "The victim's wife Melida sought NBI assistance in arresting suspects. Acting on a request for assistance, NBI operatives conducted sustained surveillance. One of the suspects was spotted on places frequented by suspect William and on April 17, 2012, he was immediately placed under arrest. William resisted and tried to escape but was subdued. He is now detained at the NBI Lucena City District Office."],
            ["case_id" => 136, "user_id" => 10940447, "observation" => "The NBI's campaign against illegal drugs is parallel to the anti-illegal drugs and anti-criminality program to curb criminal activities in Bacolod City and the whole of Negros Occidental, and in consonance, too, with advocacy of the City Councilor Carl Lopez."],
            ["case_id" => 137, "user_id" => 10940448, "observation" => "Khaki and others were also indicted in District of Columbia for smuggling, in violation of United States Code, Section 554; violating the International Emergency Economic Powers Act in violation of title 50 of the United States Code, Section 1705 and conspiracy to commit money laundering in violation of Title 18 of the United States Code, Section 1956."],
            ["case_id" => 138, "user_id" => 10940448, "observation" => "The modus operandi of the group starts by contacting prospective victims through cellular phones and they only personally appear to the victims when they receive the money as payment for the goods on sale."],
            ["case_id" => 139, "user_id" => 10940448, "observation" => "The suspect defraud a firm of more than P19 million about an order and purchase by suspect of twelve (12) Nissan Sentra X-Trail Sports Utility Vehicle (SUV) and two (2) Nissan Sentra Patrol vehicles."],
            ["case_id" => 140, "user_id" => 10940448, "observation" => "The case involves a total amount of Php 17.440 million released by the BSP to HOSLA, for which HOSLA executed in BSP's favor a promissory note and Deed of Assignment over the promissory notes and collateral land titles of HOSLA's borrowers. Thus, he stands accused for CriminalCases Nos. Q-10-165255 to 61, entitled People of the Philippines vs. Garcia et.al., pending before the Quezon City RTC Br. 217."],
            ["case_id" => 141, "user_id" => 10940448, "observation" => "Suspect promised the victims they will be deployed within 1 ½ months after paying the processing fees. But after the lapse of two months, victims failed to receive any visa as well as supposedly processed papers by the Philippine Overseas Employment Administration (POEA)."],
            ["case_id" => 142, "user_id" => 10940448, "observation" => "An informant who is a computer technician, said that he was contacted by a certain Shih-Liang Shia alias Mr. Chen, a Taiwanese, the leader of the syndicate, to install expanded internet connections of his premises located at Nos. 16-10 and 16-12 Grande St., Riverside Subdivision, Bgy. Anunas, Friendship, Angeles City, Pampanga. During the installation, he observed the fully functional workstations manned by Taiwanese and Chinese nationals as call center agents."],
            ["case_id" => 143, "user_id" => 10940448, "observation" => "The suspect's activities are so extensive and gained notoriety when about 600 complainants/victims filed a case of Illegal Recruitment and Estafa against them. Consequently, authorities raided their offices in Manila on February 1, 2012. These cases are pending at the Department of Justice. Record check with NBI files revealed that Batungbakal (Fernando Geronimo) is also facing Illegal Recruitment cases in several RTC Courts in Quezon City. The suspects will be brought to Cebu City for their commitment to Cebu City jail."],
            ["case_id" => 144, "user_id" => 10940448, "observation" => "Earlier, last year the Justice Department (DOJ) resolved the complaints filed by the Bureau against Cacayan and filed cases of violations of Section 5 of RA 9165 and Section 6 of RA 8042 (Illegal Recruitment in Large Scale) before the RTC of Manila and Isabela respectively."],
            ["case_id" => 145, "user_id" => 10940445, "observation" => "In the afternoon of November 7, 2012, the NBI in coordination with its local office and the PNP, accused Robert “Obet” Ponce a.k.a. Norberto Ponce y Peralta a.k.a. Alex Peralta was arrested in Bgy. Naganacan, Cauayan, Isabela, by virtue of a warrant of arrest issued against him. At early dawn today, the NBI team with accused Ponce arrived at the NBI main office in Manila where Ponce was booked and detained."],
            ["case_id" => 146, "user_id" => 10940447, "observation" => "On the night of December 14, 2012, an informant called the NBI and said that he saw a boy resembling the kidnap-victim based on the photos given to informants. The boy was in the company of a man and a woman who entered the Cebuana Lluillier branch inside the Odeon Mall located at the corner of C.M. Recto and Rizal Avenue Sta. Cruz Manila. NBI operatives rushed to the place and they saw the duo in the company of a boy waiting for their turn to be serviced."],
            ["case_id" => 147, "user_id" => 10940446, "observation" => "In the afternoon of February 18.2013, NBI agents accompanied the clients and certain top management personnel for the entrapment of Geroleo. At 3:00 P.M. suspect came with Layco on board a motorcycle. When Geroleo and the client met, the latter gave the marked money representing the cost of the agreed cost of the merchandise purchased. However, Geroleo sensed the unusual presence of the Bureau agents and attempted to escape in their motorcycle. Immediately alert NBI agents prevented their escape."],
            ["case_id" => 148, "user_id" => 10940447, "observation" => "At around 3:00 A.M. of April 15,2013, the PAGCOR black Ford Chrysler carrying the victim was suddenly blocked by a red Ford Lynx Sedan with Plate Number XSV-574 while traversing said road. Three men armed with pistols jumped out of the vehicle and pointed their guns at the PAGCOR driver and ordered him to open the door as one of the gunman boarded the car."],
            ["case_id" => 149, "user_id" => 10940444, "observation" => "The last incident happened on May 6, 2013. The victim’s mother was preparing the family’s breakfast in the kitchen when he took the chance to fondle his daughter’s sex organ and engaged in solo sex."],
            ["case_id" => 150, "user_id" => 10940448, "observation" => "Accused ROCHE had shifted his illegal operation in Baguio City when he conned many victims in Metro Manila and so several cases against him and his cohorts were filed at different Metro Manila courts. Likewise, verification with the POEA revealed that ROCHE, IMPERIAL, EBENG and LEBENG and the HMMII are not licensed nor authorized to recruit overseas workers."],
            ["case_id" => 151, "user_id" => 10940447, "observation" => "In 2000, Espelita obtained a loan of P303,500 for a reconditioned truck from Southeast Asia Motors Corp. (SAMC) in Valencia City, Bukidnon. As security for the loan, Espelita and his wife executed a blank real estate mortgage over a property covered by Original Certificate of Title (OCT) No. AO-1554 registered under the complainant’s deceased father, Jose C. Espelita in favor of Philippine Farmers Bank (PFB)."],
            ["case_id" => 151, "user_id" => 10940447, "observation" => "On May 26, 2013, Cabardo visited Espelita in his residence in Kalilangan, Bukidnon and informed him that OCT No. A-1554 is in their possession. Cabardo then asked the complainant to redeem it for P6,000, the amount allegedly he still owed from the PFB including the so-called “SOP” amount of P3,000."],

            ["case_id" => 152, "user_id" => 10940447, "observation" => "Later that day, suspect was again asking money from the complainant for another project. Sotalbo learned that Valdez was about to withdraw again from suspect’s own account at the said bank on June 10, 2013."],
            ["case_id" => 153, "user_id" => 10940447, "observation" => "Recovered from the suspects were the ransom money amounting to P50,000; a cell phone recovered from the body of Tiano used in communication during the negotiation; two motorcycles, one owned by the victim, Agraviador; .45 caliber; wallet with assorted cards; and other personal belongings."],
            ["case_id" => 154, "user_id" => 10940448, "observation" => "A series of test calls was conducted by Smart representative and was confirmed that ISR activity is being committed at the suspects’ office, East West Placement Center Inc. located at No. 1059 Metropolitan Avenue, Rizz Building, San Antonio Village, Makati City. A certification from Bala shows that Smart Communications Inc. has incurred losses during the service of the said search warrant. Consequently, articles subject of the offense were seized such as computer, SIM boxes, SIM cards, switching equipment and among others."],
            ["case_id" => 155, "user_id" => 10940444, "observation" => "The fataher of the victim said that his daughter arrived home from school in the afternoon of July 22, 2013 and went out to play. But after several hours, she failed to arrive home. This prompted him to seek help from his neighbors and other barangay officials for the whereabouts of his daughter."],
            ["case_id" => 156, "user_id" => 10940448, "observation" => "The complainants doubted Bernardo’s capability to send them abroad as he has no office to show and just holds audition for talents at his house in Hagonoy, Bulacan. Verification made with the Philippine Overseas Employment Administration (POEA) disclosed that Bernardo is not licensed to recruit nor deploy workers/talents abroad. This prompted the victims to seek NBI assistance."],
            ["case_id" => 157, "user_id" => 10940446, "observation" => "Subsequent verification with the Land Transportation Office, East Avenue Diliman Quezon City yielded a information for a certain “JARVIS GUY LOPEZ” with an address at No. 20 Saragoza Street Brgy Doña Imelda, Quezon City. Immediately thereafter, NBI-CTD Operatives conducted a surveillance operation together with another Complainant on the said address. During the surveillance operation, Complainant recognized Accused’s house as No. 20-C Saragoza Street, Brgy. Imelda Quezon City, as the place where she was brought by the Accused."],
            ["case_id" => 158, "user_id" => 10940448, "observation" => "From March 8 to 11, 2014, Dela Concepcion continuously called and texted victims demanding full payment of their processing fees, which suspect will get from them in Laoag City. On the last minute, Dela Concepcion changed the venue of the pay-off and the victims were told to meet her instead at Jollibee T. M. Kalaw, Manila branch at 6 A.M. on March 12, 2014 and hand over their full payment."],
            ["case_id" => 159, "user_id" => 10940446, "observation" => "Accused CEDRIC CUA LEE and SIMEON PALMA RAZ immediately fled from Japitan Beach Resort when they detected the presence of law enforcement officers. On the next day (Saturday), April 26, 2014, Accused left with no choice because of the manhunt, voluntarily surrendered to the operatives of NBI, ISAFP, and PNP in the town of Oras, Eastern Samar after which they were placed under arrest."],
            ["case_id" => 160, "user_id" => 10940447, "observation" => "Upon arrival at the area, Subject Chua was not around. Instead, five (5) plastic containing white crystalline substances, drug paraphernalia, weighing scales and other drug equipment were seen in the area. ALBERT SO, the occupant in the unit was placed under arrest after it was confirmed by NBI chemists that the items in his possession are dangerous drugs. "],
            ["case_id" => 161, "user_id" => 10940446, "observation" => "On May 12, 2014, at around 11:30 a.m., joint team of NBI-ILDO, Philippine Army and Marawi City PNP raided a place in Marawi City commonly called in the area as “LUMBER” located at Unayan St., Lumbaca Madaya, Marawi City. They were able to arrest the owner of the place, Hadji Cader Ali Sarosong, who is skilled with the “know how” in repairing and manufacturing of firearms and explosives."],
            ["case_id" => 162, "user_id" => 10940448, "observation" => "Complainants went to the office of Albaña located at the LPL Business Center, 130 Alfaro St., Salcedo Village, Makati City wherein they were promised by Roberto and his wife, Racquel Albaña to give them jobs as caregivers in Canada after their training in a selected training center and also after they pay him the 'processing fee'. The complainants paid the couple a total of Php 217,000.00."],
            ["case_id" => 163, "user_id" => 10940445, "observation" => "It was reported that the killing was stimulated by the explosion of firecrackers done by Barrera and was then imitated by his neighbor, Go. Barrera's rage was intensified when he received only Php 20.00 and two shirts when he had solicited Christmas gifts from the businessman. The killing was witnessed by Cristina Winterhalter who was standing by the gate of her house."],
            ["case_id" => 164, "user_id" => 10940445, "observation" => "On the night of June 26, 1948, Anzures paid an unexpected visit to the Quezon City home of Velez. Upon his arrival, he stabbed Velez to death and a housemaid who had come to her mistress's assistance. The crime was committed within view of Velez's toddler-daughter Vivian, who was unharmed during the incident."],
            ["case_id" => 165, "user_id" => 10940446, "observation" => "Mario Azcarraga y Relebo is on the National Bureau of Investigation's Most Wanted list. His warrant of arrest was issued by Judge Leticia P. Morales of Regional Trial Court Br. 275, in Las Piñas, Metro Manila, for robbery."],
            ["case_id" => 166, "user_id" => 10940444, "observation" => "The subject has been charged with double murder and direct assault upon an agent of a person in authority & illegal possession of firearms, ammunitions and explosives."],
            ["case_id" => 167, "user_id" => 10940444, "observation" => "The subject began his 'criminal career' in 1987. While he guarded several banks in Quezon City, he also allegedly traded 'inside info' with bank robbers, mostly with the notorious Red Scorpion gang. That year, law enforcers nearly nailed him in an alleged robbery-holdup. The Quezon City police filed charges against him, but the prosecutor's office subsequently dismissed the case."],
            ["case_id" => 168, "user_id" => 10940444, "observation" => "The subject was charged with two counts of statutory rape in the Regional Trial Court Br. 31, in Cabarroguis, Quirino, Quirino."],
            ["case_id" => 169, "user_id" => 10940445, "observation" => "With four younger accomplices, Castigador broke into the arcade in the late hours of August 2nd, 1989. The arcade had just closed and the relief manager and cashier were going through the evening's takings when guns were pointed at their heads. The safe was duly emptied of cash. The manager and cashier, along with two security guards from Sri Lanka, were then forced at gunpoint into the inner cage of the arcade's security vault. At this point, three of the robbers withdrew, but Castigador and teenage accomplice Paul Clinton stayed behind. They tied the hostages up, poured white spirit over them and tossed in lit matches before leaving, locking the door behind them."],
            ["case_id" => 170, "user_id" => 10940447, "observation" => "The subject was charged with kidnap for ransom docketed at Regional Trial Court Br. 119, Pasay City."],
            ["case_id" => 171, "user_id" => 10940444, "observation" => "The subject was the alleged mastermind behind the bloody attack against members of the Special Action Forces in 2006, resulting in the death of three policemen, including an office."],
            ["case_id" => 172, "user_id" => 10940448, "observation" => "The subject was charged with Kidnap for Ransom Case. Estrada's last known address was Matina, Davao City."],
            ["case_id" => 173, "user_id" => 10940447, "observation" => "The subject is very fluent in English and can easily sweet talk his victims, who are usually businessmen. He would order several valuable items with a promise to pay on a certain date. As soon as he gets the goods he will disappear."],
            ["case_id" => 174, "user_id" => 10940446, "observation" => "Aldrin Bonobo Fajardo is on the Philippine National Police's Most Wanted list for robbery."],

            ["case_id" => 176, "user_id" => 10940448, "observation" => "The reward for those who can give information regarding his whereabout is one million pesos."],

            ["case_id" => 179, "user_id" => 10940446, "observation" => "Subject was convicted for killing ex-Msgt Sesbreño on Dec. 23, 1984. A reward of 1 million pesos is offered to those who can give information on his whereabouts."],
            ["case_id" => 180, "user_id" => 10940447, "observation" => "The subject is a suspect in the kidnapping of Jae Keon Yoon, a Korean national, along with Filipino businessman Cesar Belonio and several others on Feb. 2, 2002 at Palimbang, Sultan Kudarat."],
            ["case_id" => 181, "user_id" => 10940445, "observation" => "There were six other cases (Criminal Case nos. 96-1991, 96-1994, 96-1995, 96-1996, 96-1997, and 96-1998) where the accused-appellant was acquitted of the charges of acts of lasciviousness for failure of the prosecution to prove his guilt beyond reasonable doubt."],
            ["case_id" => 182, "user_id" => 10940444, "observation" => "Sheikh Omar is the only Islamic leader in the Philippines who can issue a verdict pertaining to punishment “in the service of Islam”. He is considered as one of the top ideologues of the RSIM which claimed affiliation with the Al Qaeda linked regional groups Jemaah Islamiyah and the Abu Sayyaf Group."],
            ["case_id" => 183, "user_id" => 10940445, "observation" => "The subject was charged with eight counts of rape on April 22, 1997 in separate complaints brought before the Batangas City Regional Trial Court. He was accused of sexually abusing his two nieces (ages 7 and 6 years old) during four different occasions in the months of May, June and December 1996."],

            ["case_id" => 185, "user_id" => 10940445, "observation" => "The subject who is also known as Pogito, is on the Philippine National Police's Most Wanted list for homicide and frustrated murder."],

            ["case_id" => 188, "user_id" => 10940444, "observation" => "Orollo shot Brgy. Captain Arturo Ison while the latter was conducting a meeting at the Barangay Hall at Batasan Hills, Quezon City on January 20, 1997."],

            ["case_id" => 194, "user_id" => 10940446, "observation" => "The subject claims that he is Annabelle's ex-boyfriend Ruben plend guilty for kidnapping and rape of Mrs Huggins."],
            ["case_id" => 195, "user_id" => 10940446, "observation" => "The subject was a Philippine National Police's Most Wanted list for murder, robbery, and kidnapping. Warrants for his arrest were issued by Regional Trial Courts in Isabela, Basilan, Tawi-tawi, Sulu and Pasig City."],
            ["case_id" => 196, "user_id" => 10940445, "observation" => "The subject is on the National Bureau of Investigation's Most Wanted list for the crime of robbery and homicide."],
            ["case_id" => 197, "user_id" => 10940447, "observation" => "PACC's Ike Gutierrez confided to a prominent Upsilonian that Sanchez had released P10 Million to Estrada, P10 Million to Lacson and P10 Million to media to draw the 'heat' away from him. Lacson has attempted to foist fabricated evidence on the case. This was rejected by the UP group which closed ranks and vigilantly insisted on the pursuit of justice; especially the parents of the murder victims, who rallied support for the Alqueza family. Despite recantation of PACC's two witnesses Corcolon and Lavadia who claimed to have been tortured to extract false testimony against Alqueza, vehement denial by third witness Rose Molina of PACC's love triangle theory, and statement by Centeno, driver of Sanchez, who pointed at Sanchez as the first to rape Sarmenta, Estrada and Lacson insisted that 19-year old Alqueza masterminded the crime by paying Lavadia the puny sum of P21,000 to carry out the murder."],

            ["case_id" => 199, "user_id" => 10940448, "observation" => "The subject is on the Philippine National Police's Most Wanted list for the crime of kidnap for ransom."],
            ["case_id" => 200, "user_id" => 10940445, "observation" => "The subject allegedly murdered four employees of Santa Catalina local government while riding the local government's ambulance in May 2002. The victims were on their way back to Santa Catalina after withdrawing money from Land Bank Bayawan branch."],
            ["case_id" => 201, "user_id" => 10940444, "observation" => "The subject was founded to be drunk when he committed the criminal act."],
            ["case_id" => 202, "user_id" => 10940444, "observation" => "Baler’s production cost was pegged at P40 million. Under the joint movie production agreement between VIVA and BIDA, the latter was supposed to shoulder 2/3 of the total production cost which amounts to P26.7 million while the remaining 1/3 was for the account of VIVA."],
            ["case_id" => 203, "user_id" => 10940446, "observation" => "The subject admitted shooting two of the hostages and threatened to kill more.“I shot two Chinese,” he told the station in Tagalog. “I will finish them all if they do not stop.”The commandos struck after the bus driver jumped through a window and ran from the bus screaming, “Everybody is dead!”"],
            ["case_id" => 204, "user_id" => 10940444, "observation" => "Retired General Garcia, through his son Ian Carl, who was then a minor with no visible means of income, also purchased a property in Iloilo for P459,609.00. Likewise in 2004, his wife Clarita or through her children, who were minors with no visible means of income, deposited in several bank accounts and financial instruments P170,010,075.73. "],
            ["case_id" => 205, "user_id" => 10940444, "observation" => "A comparison made by BIR investigators of the gross income or revenues declared by Neri in his ITRs for taxable years 2008 and 2009 as against the income payments he received from various corporations for the same years revealed that he deliberately failed to declare his correct tax base by substantially underdeclaring his income for two (2) consecutive taxable years."],





        );

        // Uncomment the below to run the seeder
        DB::table('case_observations')->insert($case_observations);
    }

}
