<?php

class Case_addressesTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('case_addresses')->truncate();

        $case_addresses = array(
            ["case_id" => 1, "street" => "1234 Mue", "city" => "Marikina", "postal_code" => "9999", "province" => "", "barangay" => "Barangay 1"],
            ["case_id" => 2, "street" => "1234 Turbo", "city" => "Taguig", "postal_code" => "9998", "province" => "", "barangay" => "Barangay 2"],
            ["case_id" => 3, "street" => "1234 CB Mass", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 3"],
            ["case_id" => 4, "street" => "1234 Diva", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 4"],
            ["case_id" => 5, "street" => "1234 Koyote", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 5"],
            ["case_id" => 6, "street" => "1234 GP Basic", "city" => "Surigao", "postal_code" => "9995", "province" => "Surigao", "barangay" => " Barangay6"],
            ["case_id" => 7, "street" => "1234 Touch", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 7"],
            ["case_id" => 8, "street" => "1234 Nine Muses", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 8"],
            ["case_id" => 9, "street" => "1234 Infinite", "city" => "Davao", "postal_code" => "1101", "province" => "Davao", "barangay" => "Barangay 9"],
            ["case_id" => 10, "street" => "1234 Cleo", "city" => "San Juan", "postal_code" => "9994", "province" => "", "barangay" => "Barangay 10"],
            ["case_id" => 11, "street" => "1234 Chakra", "city" => "Cololbon", "postal_code" => "1303", "province" => "Catanduanes", "barangay" => "Barangay 11"],
            ["case_id" => 12, "street" => "1234 Sistar", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 12"],
            ["case_id" => 13, "street" => "1234 Bohemian", "city" => "Bato", "postal_code" => "1404", "province" => "Maguindanao", "barangay" => "Barangay 13"],
            ["case_id" => 14, "street" => "1234 Dalshabet", "city" => "Sinillan", "postal_code" => "2116", "province" => "Tarlac", "barangay" => "Barangay 14"],
            ["case_id" => 15, "street" => "1234 Harasora", "city" => "Taguig", "postal_code" => "9998", "province" => "", "barangay" => "Barangay 15"],
            ["case_id" => 16, "street" => "1234 Bella", "city" => "Taguig", "postal_code" => "9998", "province" => "", "barangay" => "Barangay 16"],
            ["case_id" => 17, "street" => "1234 Block B", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 17"],
            ["case_id" => 18, "street" => "1234 A Pink", "city" => "Caloocan", "postal_code" => "9993", "province" => "", "barangay" => "Barangay 18"],
            ["case_id" => 19, "street" => "1234 Ocean Girls", "city" => "Sirib", "postal_code" => "1505", "province" => "Davao del Sur", "barangay" => "Barangay 19"],
            ["case_id" => 20, "street" => "1234 Hitt", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 20"],
            ["case_id" => 21, "street" => "1234 N-Sonic", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => ""],
            ["case_id" => 22, "street" => "1234 C-Real", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 22"],
            ["case_id" => 23, "street" => "1234 Spica", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 23"],
            ["case_id" => 24, "street" => "1234 Six Bomb", "city" => "Muntinlupa", "postal_code" => "9991", "province" => "", "barangay" => "Barangay 24"],
            ["case_id" => 25, "street" => "1234 Exo", "city" => "Pasay", "postal_code" => "9990", "province" => "", "barangay" => "Barangay 25"],
            ["case_id" => 26, "street" => "1234 Shinee", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 26"],
            ["case_id" => 27, "street" => "1234 Taetiseo", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 27"],
            ["case_id" => 28, "street" => "1234 Hellovenus", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 28"],
            ["case_id" => 29, "street" => "1234 Vixx", "city" => "Calublub", "postal_code" => "1707", "province" => "Batangas", "barangay" => "Barangay 29"],
            ["case_id" => 30, "street" => "1234 Tahiti", "city" => "San Juan", "postal_code" => "9994", "province" => "", "barangay" => "Barangay 30"],
            ["case_id" => 31, "street" => "1234 Skarf", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 31"],
            ["case_id" => 32, "street" => "1234 Sulit", "city" => "Manila", "postal_code" => "9997", "province" => "South Cotabato", "barangay" => "Barangay 32"],
            ["case_id" => 33, "street" => "1234 Offroad", "city" => "Calublub", "postal_code" => "1707", "province" => "Batangas", "barangay" => "Barangay 33"],
            ["case_id" => 34, "street" => "1234 Attack", "city" => "Lantapan", "postal_code" => "1909", "province" => "Bukidnon", "barangay" => "Barangay 34"],
            ["case_id" => 35, "street" => "1234 Jackpot", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 35"],
            ["case_id" => 36, "street" => "1234 Pixie", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 36"],
            ["case_id" => 37, "street" => "1234 Dasoni", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 37"],
            ["case_id" => 38, "street" => "1234 Delight", "city" => "Lantapan", "postal_code" => "1909", "province" => "Bukidnon", "barangay" => "Barangay 38"],
            ["case_id" => 39, "street" => "1234 History", "city" => "Arteche", "postal_code" => "1110", "province" => "Eastern Samar", "barangay" => "Barangay 39"],
            ["case_id" => 40, "street" => "1234 Speed", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 40"],
            ["case_id" => 41, "street" => "1234 Turan", "city" => "Kibawe", "postal_code" => "1909", "province" => "Bukidnon", "barangay" => "Barangay 41"],
            ["case_id" => 42, "street" => "1234 Demion", "city" => "San Francisco", "postal_code" => "2118", "province" => "Bohol", "barangay" => "Barangay 42"],
            ["case_id" => 43, "street" => "1234 Scarlet", "city" => "Bayanga", "postal_code" => "3009", "province" => "Lanao del Sur", "barangay" => "Barangay 43"],
            ["case_id" => 44, "street" => "1234 Bebop", "city" => "Ipilan", "postal_code" => "3006", "province" => "Palawan", "barangay" => "Barangay 44"],
            ["case_id" => 45, "street" => "1234 Sugar", "city" => "San Gabriel", "postal_code" => "2200", "province" => "Camarines Sur", "barangay" => "Barangay 45"],
            ["case_id" => 46, "street" => "1234 Buzz", "city" => "Pasig", "postal_code" => "9991", "province" => "", "barangay" => "Barangay 46"],
            ["case_id" => 47, "street" => "1234 Morning", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 47"],
            ["case_id" => 48, "street" => "1234 Perfume", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 48"],
            ["case_id" => 49, "street" => "1234 Redsox", "city" => "Bacon", "postal_code" => "1606", "province" => "Sorsogon", "barangay" => "Barangay 49"],
            ["case_id" => 50, "street" => "1234 Sugar", "city" => "San Gabriel", "postal_code" => "2200", "province" => "Camarines Sur", "barangay" => "Barangay 50"],
            ["case_id" => 51, "street" => "1234 Norazo", "city" => "San Gabriel", "postal_code" => "2200", "province" => "Camarines Sur", "barangay" => "Barangay 51"],
            ["case_id" => 52, "street" => "1234 Typhoon", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 52"],
            ["case_id" => 53, "street" => "1234 Battle", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 53"],
            ["case_id" => 54, "street" => "1234 Xing", "city" => "Marikina", "postal_code" => "9999", "province" => "", "barangay" => "Barangay 54"],
            ["case_id" => 55, "street" => "1234 Soshi", "city" => "Sinillan", "postal_code" => "2116", "province" => "Tarlac", "barangay" => "Barangay 55"],
            ["case_id" => 56, "street" => "1234 WonderGirls", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 56"],
            ["case_id" => 57, "street" => "1234 Supernova", "city" => "Taguig", "postal_code" => "9998", "province" => "", "barangay" => "Barangay 57"],
            ["case_id" => 58, "street" => "1234 Tritops", "city" => "Pasay", "postal_code" => "9990", "province" => "", "barangay" => "Barangay 58"],
            ["case_id" => 59, "street" => "1234 Shinee", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 59"],
            ["case_id" => 60, "street" => "1234 Untouchable", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 60"],
            ["case_id" => 61, "street" => "1234 Supreme", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 61"],
            ["case_id" => 62, "street" => "1234 Jumper", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 62"],
            ["case_id" => 63, "street" => "1234 T-ara", "city" => "Sulit", "postal_code" => "1808", "province" => "South Cotabato", "barangay" => "63"],
            ["case_id" => 64, "street" => "1234 2ne1", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 64"],
            ["case_id" => 65, "street" => "1234 Beast", "city" => "Batobalani", "postal_code" => "2111", "province" => "Camarines Norte", "barangay" => "Barangay 65"],
            ["case_id" => 66, "street" => "1234 Secret", "city" => "San Pedro", "postal_code" => "2112", "province" => "Antique", "barangay" => "Barangay 66"],
            ["case_id" => 67, "street" => "1234 Jewelry", "city" => "San Miguel", "postal_code" => "2119", "province" => "Bukidnon", "barangay" => "Barangay 67"],
            ["case_id" => 68, "street" => "1234 December", "city" => "Tumcon", "postal_code" => "3001", "province" => "Iloilo", "barangay" => "Barangay 68"],
            ["case_id" => 69, "street" => "1234 Rainbow", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 69"],
            ["case_id" => 70, "street" => "1234 Mighty", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 70"],
            ["case_id" => 71, "street" => "1234 Mouth", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 71"],
            ["case_id" => 72, "street" => "1234 Davichi", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 72"],
            ["case_id" => 73, "street" => "1234 Sunny Hill", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 73"],
            ["case_id" => 74, "street" => "1234 Super Junior", "city" => "Muntinlupa", "postal_code" => "9991", "province" => "", "barangay" => "Barangay 74"],
            ["case_id" => 75, "street" => "1234 Black Pearl", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 75"],
            ["case_id" => 76, "street" => "1234 Five Code", "city" => "Bacon", "postal_code" => "1606", "province" => "Sorsogon", "barangay" => "Barangay 76"],
            ["case_id" => 77, "street" => "1234 Airplane", "city" => "Quezon", "postal_code" => "9996", "province" => "", "barangay" => "Barangay 77"],
            ["case_id" => 78, "street" => "1234 Pixie", "city" => "San Juan", "postal_code" => "9994", "province" => "", "barangay" => "Barangay 78"],
            ["case_id" => 79, "street" => "1234 Rabbit", "city" => "Makati", "postal_code" => "9992", "province" => "", "barangay" => "Barangay 79"],
            ["case_id" => 80, "street" => "1234 Purplay", "city" => "Manila", "postal_code" => "9997", "province" => "", "barangay" => "Barangay 80"],
            //EWPID
            ["case_id" => 81, "street" => "01 Bobby Hill", "city" => "Davao", "postal_code" => "1101", "province" => "Davao", "barangay" => "Barangay 1"],
            ["case_id" => 82, "street" => "02 Wonder Woman", "city" => "Manila", "postal_code" => "1202", "province" => "", "barangay" => "Barangay 2"],
            ["case_id" => 83, "street" => "03 Daria", "city" => "Cololbon", "postal_code" => "1303", "province" => "Catanduanes", "barangay" => "Barangay 3"],
            ["case_id" => 84, "street" => "04 Batman", "city" => "Bato", "postal_code" => "1404", "province" => "Maguindanao", "barangay" => "Barangay 4"],
            ["case_id" => 85, "street" => "05 Superman", "city" => "Sirib", "postal_code" => "1505", "province" => "Davao del Sur", "barangay" => "Barangay 5"],
            ["case_id" => 86, "street" => "06 George of the Jungle", "city" => "Bacon", "postal_code" => "1606", "province" => "Sorsogon", "barangay" => "Barangay 6"],
            ["case_id" => 87, "street" => "07 Spiderman", "city" => "Calublub", "postal_code" => "1707", "province" => "Batangas", "barangay" => "Barangay 7"],
            ["case_id" => 88, "street" => "08 Powerpuff", "city" => "Sulit", "postal_code" => "1808", "province" => "South Cotabato", "barangay" => "Barangay 8"],
            ["case_id" => 89, "street" => "09 Angelica Pickles", "city" => "Lantapan", "postal_code" => "1909", "province" => "Bukidnon", "barangay" => "Barangay 9"],
            ["case_id" => 90, "street" => "10 Felix the Cat", "city" => "Arteche", "postal_code" => "1110", "province" => "Eastern Samar", "barangay" => "Barangay 10"],
            //DID
            ["case_id" => 91, "street" => "11 Boris Badenov", "city" => "Batobalani", "postal_code" => "2111", "province" => "Camarines Norte", "barangay" => "Barangay 11"],
            ["case_id" => 92, "street" => "12 Tom and Jerry", "city" => "San Pedro", "postal_code" => "2112", "province" => "Antique", "barangay" => "Barangay 12"],
            ["case_id" => 93, "street" => "13 Woody Woodpecker", "city" => "Gansing", "postal_code" => "2113", "province" => "Sultan Kudarat", "barangay" => "Barangay 13"],
            ["case_id" => 94, "street" => "14 Alvin and the Chimpmunks", "city" => "San Juan", "postal_code" => "2114", "province" => "Zambales", "barangay" => "Barangay 14"],
            ["case_id" => 95, "street" => "15 Donald Duck", "city" => "Ivisan", "postal_code" => "2115", "province" => "Capiz", "barangay" => "Barangay 15"],
            ["case_id" => 96, "street" => "16 Mighty Mouse", "city" => "Sinillan", "postal_code" => "2116", "province" => "Tarlac", "barangay" => "Barangay 16"],
            ["case_id" => 97, "street" => "17 Yogi Bear", "city" => "Tiaong", "postal_code" => "2117", "province" => "Quezon", "barangay" => "Barangay 17"],
            ["case_id" => 98, "street" => "18 Space Ghost", "city" => "San Francisco", "postal_code" => "2118", "province" => "Bohol", "barangay" => "Barangay 18"],
            ["case_id" => 99, "street" => "19 Bill", "city" => "San Miguel", "postal_code" => "2119", "province" => "Bukidnon", "barangay" => "Barangay 19"],
            ["case_id" => 100, "street" => "20 Arthur", "city" => "San Gabriel", "postal_code" => "2200", "province" => "Camarines Sur", "barangay" => "Barangay 20"],
            //IPRD
            ["case_id" => 101, "street" => "21 Winnie the Pooh", "city" => "Tumcon", "postal_code" => "3001", "province" => "Iloilo", "barangay" => "Barangay 21"],
            ["case_id" => 102, "street" => "22 Ren and Stimpy", "city" => "Kipalbig", "postal_code" => "3002", "province" => "South Cotabato", "barangay" => "Barangay 22"],
            ["case_id" => 103, "street" => "23 Top Cat", "city" => "Siocon", "postal_code" => "3003", "province" => "Zamboanga del Norte", "barangay" => "Barangay 23"],
            ["case_id" => 104, "street" => "24 Heckle and Jeckle", "city" => "Saguing", "postal_code" => "3004", "province" => "North Cotabato", "barangay" => "Barangay 24"],
            ["case_id" => 105, "street" => "25 Josie", "city" => "Tabina", "postal_code" => "3005", "province" => "Zamboanga del Sur", "barangay" => "Barangay 25"],
            ["case_id" => 106, "street" => "26 Space Racer", "city" => "Ipilan", "postal_code" => "3006", "province" => "Palawan", "barangay" => "Barangay 26"],
            ["case_id" => 107, "street" => "27 Tweety Bird", "city" => "Quezon", "postal_code" => "3007", "province" => "", "barangay" => "Barangay 27"],
            ["case_id" => 108, "street" => "28 Underdog", "city" => "Kibawe", "postal_code" => "3008", "province" => "Bukidnon", "barangay" => "Barangay 28"],
            ["case_id" => 109, "street" => "29 Pink Panther", "city" => "Bayanga", "postal_code" => "3009", "province" => "Lanao del Sur", "barangay" => "Barangay 29"],
            ["case_id" => 110, "street" => "30 Gumby", "city" => "Baya", "postal_code" => "3330", "province" => "Maguindanao", "barangay" => "Barangay 30"],
            //RAID
            ["case_id" => 111, "street" => "31 George Jetson", "city" => "Catalban", "postal_code" => "4321", "province" => "Pangasinan", "barangay" => "Barangay 31"],
            ["case_id" => 112, "street" => "32 Betty Boop", "city" => "Bacong", "postal_code" => "4322", "province" => "Negros Oriental", "barangay" => "Barangay32"],
            ["case_id" => 113, "street" => "33 Fat Albert", "city" => "Dayap", "postal_code" => "4323", "province" => "Laguna", "barangay" => "Barangay 33"],
            ["case_id" => 114, "street" => "34 Beavis and Butt-head", "city" => "Pandan", "postal_code" => "4324", "province" => "Catanduanes", "barangay" => "Barangay 34"],
            ["case_id" => 115, "street" => "35 Mr. Magoo", "city" => "Umiray", "postal_code" => "4325", "province" => "Quezon", "barangay" => "Barangay 35"],
            ["case_id" => 116, "street" => "36 Scooby Doo", "city" => "Caminda", "postal_code" => "4326", "province" => "Negros Occiedental", "barangay" => "Barangay 36"],
            ["case_id" => 117, "street" => "37 Porky Pig", "city" => "Maloh", "postal_code" => "4327", "province" => "Negros Oriental", "barangay" => "Barangay 37"],
            ["case_id" => 118, "street" => "38 Daffy Duck", "city" => "Nagbalaye", "postal_code" => "4328", "province" => "Negros Oriental", "barangay" => "Barangay 38"],
            ["case_id" => 119, "street" => "39 Eric Cartman", "city" => "Plaridel", "postal_code" => "4329", "province" => "Negros Occidental", "barangay" => "Barangay 39"],
            ["case_id" => 120, "street" => "40 Spongebob", "city" => "Kauran", "postal_code" => "4300", "province" => "Maguindanao", "barangay" => "Barangay40"],
            //VAWCD
            ["case_id" => 121, "street" => "41 Rocky and Bullwinkle", "city" => "Alae", "postal_code" => "5991", "province" => "Bukidnon", "barangay" => "Barangay 41"],
            ["case_id" => 122, "street" => "42 Wile Coyote", "city" => "Llanera", "postal_code" => "5992", "province" => "Nueva Ecija", "barangay" => "Barangay 42"],
            ["case_id" => 123, "street" => "43 Popeye", "city" => "Canturay", "postal_code" => "5993", "province" => "Negros Occidental", "barangay" => "Barangay 43"],
            ["case_id" => 124, "street" => "44 Grinch", "city" => "Murcia", "postal_code" => "5994", "province" => "Tarlac", "barangay" => "Barangay 44"],
            ["case_id" => 125, "street" => "45 Flintstone", "city" => "Santo Tomas", "postal_code" => "5995", "province" => "Nueva Ecija", "barangay" => "Barangay 45"],
            ["case_id" => 126, "street" => "46 Charlie Brown", "city" => "Talisay", "postal_code" => "5996", "province" => "Quezon", "barangay" => "Barangay 46"],
            ["case_id" => 127, "street" => "47 Simpson", "city" => "Sabang", "postal_code" => "5997", "province" => "Bataan", "barangay" => "Barangay 47"],
            ["case_id" => 128, "street" => "48 Mickey Mouse", "city" => "Baquero", "postal_code" => "5998", "province" => "Tarlac", "barangay" => "Barangay 48"],
            ["case_id" => 129, "street" => "49 Homer", "city" => "Bulata", "postal_code" => "5999", "province" => "Negros Occiedental", "barangay" => "Barangay 49"],
            ["case_id" => 130, "street" => "50 Bugs Bunny", "city" => "Panitan", "postal_code" => "5099", "province" => "Capiz", "barangay" => "Barangay 50"],
//*********************************************************************************************************************************************************************************
            ["case_id" => 131, "street" => "Arakan", "city" => "Cotabato", "postal_code" => "7839", "province" => "North Cotabato", "barangay" => "Alicia"],
            ["case_id" => 132, "street" => "Harrison", "city" => "Pasay", "postal_code" => "2193", "province" => "", "barangay" => "Amihan"],
            ["case_id" => 133, "street" => "North Fairview", "city" => "Quezon", "postal_code" => "4102", "province" => "", "barangay" => "Apoliono"],
            ["case_id" => 134, "street" => "Pearl", "city" => "Pasig", "postal_code" => "3162", "province" => "", "barangay" => "DOona Juana"],
            ["case_id" => 135, "street" => "Dupay", "city" => "Lucena", "postal_code" => "5102", "province" => "Lucena", "barangay" => "Ilayang"],
            ["case_id" => 136, "street" => "Palong", "city" => "Bacolod", "postal_code" => "7162", "province" => "Bacolor", "barangay" => "Baesa"],
            ["case_id" => 137, "street" => "Ermita", "city" => "Manila", "postal_code" => "1231", "province" => "", "barangay" => "Bagbag"],
            ["case_id" => 138, "street" => "Rizal", "city" => "Manila", "postal_code" => "1331", "province" => "", "barangay" => "Bagong Lipunan"],
            ["case_id" => 139, "street" => "Hakot", "city" => "Quezon", "postal_code" => "2134", "province" => "", "barangay" => "Bagong Pag-asa"],
            ["case_id" => 140, "street" => "Magiting", "city" => "Quezon", "postal_code" => "4123", "province" => "", "barangay" => "Bagong Silangan"],
            ["case_id" => 141, "street" => "Taft", "city" => "Manila", "postal_code" => "1234", "province" => "", "barangay" => "Bagumbayan"],
            ["case_id" => 142, "street" => "Florentino", "city" => "Angeles", "postal_code" => "6166", "province" => "Angeles", "barangay" => "Bagumbuhay"],
            ["case_id" => 143, "street" => "M. De Santos", "city" => "Cebu", "postal_code" => "8173", "province" => "Cebu", "barangay" => "Bahay Toro"],
            ["case_id" => 144, "street" => "A. Soriano", "city" => "Isabela", "postal_code" => "3301", "province" => "Isabela", "barangay" => "Balingasa"],
            ["case_id" => 145, "street" => "Fidel Reyes", "city" => "Isabela", "postal_code" => "3301", "province" => "Isabela", "barangay" => "Balongbato"],
            ["case_id" => 146, "street" => "Raja Matanda", "city" => "Manila", "postal_code" => "1231", "province" => "", "barangay" => "Bayanihan"],
            ["case_id" => 147, "street" => "M.V. Delos Santos", "city" => "Makati", "postal_code" => "2131", "province" => "", "barangay" => "Blue Ridge"],
            ["case_id" => 148, "street" => "Legarda", "city" => "Manila", "postal_code" => "1233", "province" => "", "barangay" => "BOtocan"],
            ["case_id" => 149, "street" => "F. Torres", "city" => "Pangasinan", "postal_code" => "3347", "province" => "Pangasinan", "barangay" => "Bungad"],
            ["case_id" => 150, "street" => "Alfonso Mendoza", "city" => "Baguio", "postal_code" => "3990", "province" => "Baguio", "barangay" => "Camp Aguinaldo"],
            ["case_id" => 151, "street" => "Juan Luna", "city" => "Bukidnon", "postal_code" => "5661", "province" => "Bukidnon", "barangay" => "Capri"],
            ["case_id" => 152, "street" => "ENgracia Reyes", "city" => "Baguio", "postal_code" => "3991", "province" => "Baguio", "barangay" => "Central"],
            ["case_id" => 153, "street" => "GM. Tolentino", "city" => "Cebu", "postal_code" => "8172", "province" => "Cebu", "barangay" => "Culiat"],
            ["case_id" => 154, "street" => "Antonio Delgado", "city" => "Makati", "postal_code" => "2131", "province" => "", "barangay" => "Damar"],
            ["case_id" => 155, "street" => "Felipe Agoncillo", "city" => "Quezon", "postal_code" => "4131", "province" => "", "barangay" => "Damayan"],
            ["case_id" => 156, "street" => "Natividad Almeda", "city" => "Malolos", "postal_code" => "4998", "province" => "Bulacan", "barangay" => "Del Monte"],
            ["case_id" => 157, "street" => "Norberto Ty", "city" => "Quezon", "postal_code" => "4123", "province" => "", "barangay" => "Dioquino Zobel"],
            ["case_id" => 158, "street" => "R. Cristobal", "city" => "Batangas", "postal_code" => "5598", "province" => "Batangas", "barangay" => "Don Manuel"],
            ["case_id" => 159, "street" => "Angel Linao", "city" => "Samar", "postal_code" => "7790", "province" => "Samar", "barangay" => "Dona Aurora"],
            ["case_id" => 160, "street" => "Adriatico", "city" => "Manila", "postal_code" => "1321", "province" => "", "barangay" => "Dona Imelda"],
            ["case_id" => 161, "street" => "Burke", "city" => "Marawi", "postal_code" => "9928", "province" => "Marawi", "barangay" => "Dona Josefa"],
            ["case_id" => 162, "street" => "F. Dalupan", "city" => "Makati", "postal_code" => "2134", "province" => "", "barangay" => "Duyan-duyan"],
            ["case_id" => 163, "street" => "Luis Ma. Guerrero", "city" => "Paranaque", "postal_code" => "2997", "province" => "", "barangay" => "East Kamias"],
            ["case_id" => 164, "street" => "Sta. Teresita", "city" => "Quezon", "postal_code" => "4121", "province" => "", "barangay" => "Escopa"],
            ["case_id" => 165, "street" => "Pilar Hidalgo", "city" => "Las Pinas", "postal_code" => "1741", "province" => "", "barangay" => "Talon Dos"],
            ["case_id" => 166, "street" => "ML. Carreon", "city" => "Paranaque", "postal_code" => "2134", "province" => "", "barangay" => "Kalusugan"],
            ["case_id" => 167, "street" => "F. Cayco", "city" => "Quezon", "postal_code" => "4121", "province" => "", "barangay" => "Katipunan"],
            ["case_id" => 168, "street" => "F.T. Benitez", "city" => "Quirino", "postal_code" => "7440", "province" => "Quirino", "barangay" => "Kristong Hari"],
            ["case_id" => 169, "street" => "S. Loyola", "city" => "United Kingdom", "postal_code" => "", "province" => "", "barangay" => ""],
            ["case_id" => 170, "street" => "Jhocson", "city" => "Pasay", "postal_code" => "2378", "province" => "", "barangay" => "Krus na Ligas"],
            ["case_id" => 171, "street" => "Gonzalo Puyat", "city" => "Pangasinan", "postal_code" => "5115", "province" => "Pangasinan", "barangay" => "Laging Handa"],
            ["case_id" => 172, "street" => "Sales", "city" => "Davao", "postal_code" => "9552", "province" => "Davao", "barangay" => "Lourdes"],
            ["case_id" => 173, "street" => "General", "city" => "Calamba", "postal_code" => "4152", "province" => "Laguna", "barangay" => "Loyola Heights"],
            ["case_id" => 174, "street" => "Real", "city" => "Manila", "postal_code" => "1221", "province" => "", "barangay" => "Maharlika"],
            ["case_id" => 175, "street" => "Quintin Paredes", "city" => "Bacoor", "postal_code" => "3114", "province" => "Cavite", "barangay" => "Malaya"],
            ["case_id" => 176, "street" => "Ongpin", "city" => "Sto. Tomas", "postal_code" => "5112", "province" => "Batangas", "barangay" => "Mangga"],
            ["case_id" => 177, "street" => "Arlegui", "city" => "Tarlac", "postal_code" => "6619", "province" => "Tarlac", "barangay" => "Manresa"],
            ["case_id" => 178, "street" => "Tomas Pinpin", "city" => "Pasig", "postal_code" => "2778", "province" => "", "barangay" => "Mariana"],
            ["case_id" => 179, "street" => "Gernale", "city" => "Antique", "postal_code" => "6601", "province" => "Antique", "barangay" => "Mariblo"],
            ["case_id" => 180, "street" => "Nakpil", "city" => "Sultan Kudarat", "postal_code" => "9989", "province" => "Sultan Kudarat", "barangay" => "Marilag"],
            ["case_id" => 181, "street" => "Pablo Ocampo", "city" => "Makati", "postal_code" => "2311", "province" => "", "barangay" => "Masagana"],
            ["case_id" => 182, "street" => "A. Maceda", "city" => "South Cotabato", "postal_code" => "9667", "province" => "Cotabato", "barangay" => "Masambong"],
            ["case_id" => 183, "street" => "Vasquez", "city" => "Batangas", "postal_code" => "5133", "province" => "Batangas", "barangay" => "Matandang Balara"],
            ["case_id" => 184, "street" => "Fugoso", "city" => "Quezon", "postal_code" => "4112", "province" => "", "barangay" => "Milagrosa"],
            ["case_id" => 185, "street" => "Roxas", "city" => "Pangasinan", "postal_code" => "6117", "province" => "Pangasinan", "barangay" => "Amoranto"],
            ["case_id" => 186, "street" => "Lacson", "city" => "Pasay", "postal_code" => "2267", "province" => "", "barangay" => "Nayong Kanluran"],
            ["case_id" => 187, "street" => "Quirino", "city" => "Quezon", "postal_code" => "4111", "province" => "", "barangay" => "New Era"],
            ["case_id" => 188, "street" => "Magsaysay", "city" => "Quezon", "postal_code" => "4115", "province" => "", "barangay" => "Obrero"],
            ["case_id" => 189, "street" => "Washington", "city" => "Valenzuela", "postal_code" => "3390", "province" => "", "barangay" => "Old Capitol"],
            ["case_id" => 190, "street" => "Wright", "city" => "Laguna", "postal_code" => "4482", "province" => "Laguna", "barangay" => "Paang Bundok"],
            ["case_id" => 191, "street" => "Zubaran", "city" => "Cainta", "postal_code" => "3367", "province" => "Rizal", "barangay" => "Paligsahan"],
            ["case_id" => 192, "street" => "Calle Union", "city" => "Valenzuela", "postal_code" => "3391", "province" => "", "barangay" => "Paltok"],
            ["case_id" => 193, "street" => "Vermont", "city" => "Manila", "postal_code" => "1211", "province" => "", "barangay" => "Pansol"],
            ["case_id" => 194, "street" => "Columbia", "city" => "Manila", "postal_code" => "1122", "province" => "", "barangay" => "Paraiso"],
            ["case_id" => 195, "street" => "Dewey", "city" => "Pasig", "postal_code" => "2779", "province" => "", "barangay" => "Pasong Putik"],
            ["case_id" => 196, "street" => "Forbes", "city" => "Manila", "postal_code" => "1213", "province" => "", "barangay" => "Pasong Tamo"],
            ["case_id" => 197, "street" => "Santa Mesa", "city" => "Manila", "postal_code" => "1212", "province" => "", "barangay" => "Payatas"],
            ["case_id" => 198, "street" => "Arnaiz", "city" => "Bocaue", "postal_code" => "3887", "province" => "Bulacan", "barangay" => "Phil-am"],
            ["case_id" => 199, "street" => "Laong Laan", "city" => "Angeles", "postal_code" => "5581", "province" => "Pampanga", "barangay" => "Pinagkaisahan"],
            ["case_id" => 200, "street" => "Mexico", "city" => "Dumaguete", "postal_code" => "7231", "province" => "Dumaguete", "barangay" => "Pinyahan"],
            ["case_id" => 201, "street" => "South Market", "city" => "Iligan", "postal_code" => "4980", "province" => "Iligan", "barangay" => "Olivarez"],
            ["case_id" => 202, "street" => "Tramo", "city" => "Manila", "postal_code" => "1231", "province" => "", "barangay" => "Karangyaan"],
            ["case_id" => 203, "street" => "Nichols Road", "city" => "Manila", "postal_code" => "1112", "province" => "", "barangay" => "Kamuning"],
            ["case_id" => 204, "street" => "Calzada de Pasay", "city" => "Iloilo", "postal_code" => "5812", "province" => "Iloilo", "barangay" => "Kalusugan"],
            ["case_id" => 205, "street" => "Eugenio Lopez", "city" => "Quezon", "postal_code" => "4117", "province" => "", "barangay" => "Project 6"],
        );

        // Uncomment the below to run the seeder
        DB::table('case_addresses')->insert($case_addresses);
    }

}