<?php

class Complaint_subjectsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('complaint_subjects')->truncate();

        $complaint_subjects = array(
            ["complaint_id" => 1, "client_id" => 231],
            ["complaint_id" => 2, "client_id" => 232],
            ["complaint_id" => 3, "client_id" => 104],
            ["complaint_id" => 4, "client_id" => 233],
            ["complaint_id" => 4, "client_id" => 234],
            ["complaint_id" => 5, "client_id" => 235],
            ["complaint_id" => 6, "client_id" => 236],
            ["complaint_id" => 6, "client_id" => 237],
            //no subject for 7 because suicide
            ["complaint_id" => 8, "client_id" => 238],
            ["complaint_id" => 9, "client_id" => 239],
            ["complaint_id" => 10, "client_id" => 240],
            ["complaint_id" => 10, "client_id" => 241],
            ["complaint_id" => 10, "client_id" => 242],
            ["complaint_id" => 11, "client_id" => 243],
            ["complaint_id" => 12, "client_id" => 244],
            ["complaint_id" => 12, "client_id" => 245],
            ["complaint_id" => 12, "client_id" => 246],
            ["complaint_id" => 13, "client_id" => 247],
            ["complaint_id" => 14, "client_id" => 248],
            ["complaint_id" => 14, "client_id" => 249],
            ["complaint_id" => 15, "client_id" => 250],
            ["complaint_id" => 16, "client_id" => 251],
            ["complaint_id" => 16, "client_id" => 252],
            ["complaint_id" => 17, "client_id" => 253],
            ["complaint_id" => 18, "client_id" => 254],
            ["complaint_id" => 19, "client_id" => 255],
            ["complaint_id" => 20, "client_id" => 256],
            ["complaint_id" => 21, "client_id" => 257],
            ["complaint_id" => 22, "client_id" => 258],
            ["complaint_id" => 23, "client_id" => 259],
            ["complaint_id" => 24, "client_id" => 260],
            ["complaint_id" => 24, "client_id" => 261],
            ["complaint_id" => 24, "client_id" => 262],
            ["complaint_id" => 24, "client_id" => 263],
            ["complaint_id" => 24, "client_id" => 264],
            //no subject for 25 because suicide
            ["complaint_id" => 26, "client_id" => 265],
            ["complaint_id" => 27, "client_id" => 266],
            ["complaint_id" => 27, "client_id" => 267],
            ["complaint_id" => 27, "client_id" => 268],
            ["complaint_id" => 28, "client_id" => 269],
            ["complaint_id" => 28, "client_id" => 270],
            ["complaint_id" => 29, "client_id" => 271],
            ["complaint_id" => 30, "client_id" => 272],
            ["complaint_id" => 30, "client_id" => 273],
            ["complaint_id" => 31, "client_id" => 274],
            ["complaint_id" => 32, "client_id" => 275],
            ["complaint_id" => 32, "client_id" => 276],
            ["complaint_id" => 33, "client_id" => 277],
            ["complaint_id" => 34, "client_id" => 278],
            ["complaint_id" => 35, "client_id" => 279],
            ["complaint_id" => 36, "client_id" => 280],
            ["complaint_id" => 37, "client_id" => 281],
            ["complaint_id" => 37, "client_id" => 282],
            ["complaint_id" => 38, "client_id" => 283],
            ["complaint_id" => 39, "client_id" => 284],
            ["complaint_id" => 40, "client_id" => 285],
            ["complaint_id" => 41, "client_id" => 286],
            ["complaint_id" => 42, "client_id" => 287],
            ["complaint_id" => 43, "client_id" => 288],
            ["complaint_id" => 44, "client_id" => 288],
            ["complaint_id" => 45, "client_id" => 289],
            ["complaint_id" => 46, "client_id" => 290],
            ["complaint_id" => 47, "client_id" => 291],
            ["complaint_id" => 48, "client_id" => 292],
            ["complaint_id" => 49, "client_id" => 293],
            ["complaint_id" => 50, "client_id" => 289],
            ["complaint_id" => 51, "client_id" => 289],
            ["complaint_id" => 52, "client_id" => 261],
            ["complaint_id" => 52, "client_id" => 262],
            ["complaint_id" => 52, "client_id" => 263],
            ["complaint_id" => 53, "client_id" => 264],
            ["complaint_id" => 53, "client_id" => 263],
            ["complaint_id" => 53, "client_id" => 262],
            ["complaint_id" => 54, "client_id" => 294],
            ["complaint_id" => 55, "client_id" => 295],
            ["complaint_id" => 56, "client_id" => 284],
            ["complaint_id" => 57, "client_id" => 232],
            ["complaint_id" => 58, "client_id" => 232],
            ["complaint_id" => 59, "client_id" => 262],
            ["complaint_id" => 60, "client_id" => 262],
            ["complaint_id" => 61, "client_id" => 426],
            ["complaint_id" => 62, "client_id" => 427],
            ["complaint_id" => 63, "client_id" => 429],
            ["complaint_id" => 64, "client_id" => 431],
            ["complaint_id" => 65, "client_id" => 433],
            ["complaint_id" => 66, "client_id" => 435],
            ["complaint_id" => 67, "client_id" => 412],
            ["complaint_id" => 68, "client_id" => 414],
            ["complaint_id" => 69, "client_id" => 416],
            ["complaint_id" => 70, "client_id" => 418],
            ["complaint_id" => 71, "client_id" => 284],
            ["complaint_id" => 72, "client_id" => 420],
            ["complaint_id" => 73, "client_id" => 283],
            ["complaint_id" => 74, "client_id" => 260],
            ["complaint_id" => 74, "client_id" => 261],
            ["complaint_id" => 75, "client_id" => 265],
            ["complaint_id" => 76, "client_id" => 422],
            ["complaint_id" => 77, "client_id" => 269],
            ["complaint_id" => 78, "client_id" => 272],
            ["complaint_id" => 78, "client_id" => 273],
            ["complaint_id" => 79, "client_id" => 246],
            ["complaint_id" => 80, "client_id" => 247],
            
            ["complaint_id" => 81, "client_id" => 296],
            ["complaint_id" => 82, "client_id" => 296],
            ["complaint_id" => 83, "client_id" => 297],
            ["complaint_id" => 84, "client_id" => 297],
            ["complaint_id" => 85, "client_id" => 298],
            ["complaint_id" => 86, "client_id" => 299],
            ["complaint_id" => 87, "client_id" => 300],
            ["complaint_id" => 88, "client_id" => 301],
            ["complaint_id" => 89, "client_id" => 302],
            ["complaint_id" => 90, "client_id" => 303],
            ["complaint_id" => 91, "client_id" => 304],
            ["complaint_id" => 92, "client_id" => 305],
            ["complaint_id" => 93, "client_id" => 306],
            ["complaint_id" => 94, "client_id" => 307],
            //no subject for 95 because suicide
            ["complaint_id" => 96, "client_id" => 309],
            ["complaint_id" => 97, "client_id" => 310],
            ["complaint_id" => 98, "client_id" => 311],
            ["complaint_id" => 99, "client_id" => 312],
            ["complaint_id" => 100, "client_id" => 313],
            ["complaint_id" => 101, "client_id" => 314],
            ["complaint_id" => 102, "client_id" => 315],
            ["complaint_id" => 103, "client_id" => 316],
            ["complaint_id" => 104, "client_id" => 317],
            ["complaint_id" => 105, "client_id" => 318],
            ["complaint_id" => 106, "client_id" => 319],
            ["complaint_id" => 107, "client_id" => 320],
            ["complaint_id" => 108, "client_id" => 321],
            ["complaint_id" => 109, "client_id" => 322],
            ["complaint_id" => 110, "client_id" => 323],
            ["complaint_id" => 111, "client_id" => 324],
            ["complaint_id" => 112, "client_id" => 325],
            ["complaint_id" => 113, "client_id" => 326],
            ["complaint_id" => 114, "client_id" => 327],
            ["complaint_id" => 115, "client_id" => 328],
            ["complaint_id" => 116, "client_id" => 329],
            ["complaint_id" => 117, "client_id" => 330],
            ["complaint_id" => 118, "client_id" => 331],
            ["complaint_id" => 119, "client_id" => 332],
            ["complaint_id" => 120, "client_id" => 333],
            ["complaint_id" => 121, "client_id" => 334],
            ["complaint_id" => 122, "client_id" => 335],
            ["complaint_id" => 123, "client_id" => 336],
            ["complaint_id" => 124, "client_id" => 337],
            ["complaint_id" => 125, "client_id" => 338],
            ["complaint_id" => 126, "client_id" => 339],
            ["complaint_id" => 127, "client_id" => 340],
            ["complaint_id" => 128, "client_id" => 341],
            ["complaint_id" => 129, "client_id" => 342],
            ["complaint_id" => 130, "client_id" => 343],


            ["complaint_id" => 131, "client_id" => 436],
            ["complaint_id" => 131, "client_id" => 437],
            ["complaint_id" => 131, "client_id" => 438],
            ["complaint_id" => 131, "client_id" => 439],

            ["complaint_id" => 132, "client_id" => 440],

            ["complaint_id" => 133, "client_id" => 441],
            ["complaint_id" => 133, "client_id" => 442],

            ["complaint_id" => 134, "client_id" => 443],

            ["complaint_id" => 135, "client_id" => 444],
            ["complaint_id" => 135, "client_id" => 445],

            ["complaint_id" => 136, "client_id" => 446],
            ["complaint_id" => 137, "client_id" => 447],
            ["complaint_id" => 138, "client_id" => 448],
            ["complaint_id" => 139, "client_id" => 449],
            ["complaint_id" => 140, "client_id" => 450],

            ["complaint_id" => 141, "client_id" => 451],
            ["complaint_id" => 141, "client_id" => 452],

            ["complaint_id" => 142, "client_id" => 453],
            ["complaint_id" => 143, "client_id" => 454],
            ["complaint_id" => 143, "client_id" => 455],
            ["complaint_id" => 143, "client_id" => 456],
            ["complaint_id" => 143, "client_id" => 457],

            ["complaint_id" => 144, "client_id" => 458],
            ["complaint_id" => 145, "client_id" => 459],

            ["complaint_id" => 146, "client_id" => 460],
            ["complaint_id" => 146, "client_id" => 461],

            ["complaint_id" => 147, "client_id" => 462],
            ["complaint_id" => 147, "client_id" => 463],

            ["complaint_id" => 148, "client_id" => 464],
            ["complaint_id" => 148, "client_id" => 465],
            ["complaint_id" => 148, "client_id" => 466],
            ["complaint_id" => 148, "client_id" => 467],

            ["complaint_id" => 149, "client_id" => 468],

            ["complaint_id" => 150, "client_id" => 469],
            ["complaint_id" => 150, "client_id" => 470],
            ["complaint_id" => 150, "client_id" => 471],
            ["complaint_id" => 150, "client_id" => 472],

            ["complaint_id" => 151, "client_id" => 473],
            ["complaint_id" => 152, "client_id" => 474],
            ["complaint_id" => 153, "client_id" => 475],

            ["complaint_id" => 154, "client_id" => 476],
            ["complaint_id" => 154, "client_id" => 477],
            ["complaint_id" => 154, "client_id" => 478],

            ["complaint_id" => 155, "client_id" => 479],
            ["complaint_id" => 155, "client_id" => 480],

            ["complaint_id" => 156, "client_id" => 481],
            ["complaint_id" => 156, "client_id" => 482],
            ["complaint_id" => 156, "client_id" => 483],
            ["complaint_id" => 156, "client_id" => 484],

            ["complaint_id" => 157, "client_id" => 485],
            ["complaint_id" => 158, "client_id" => 486],

            ["complaint_id" => 159, "client_id" => 487],
            ["complaint_id" => 159, "client_id" => 488],

            ["complaint_id" => 160, "client_id" => 489],
            ["complaint_id" => 161, "client_id" => 490],
            

            //SUBJECT FROM WIKIPILIPINAS ******************************************************************************************


            ["complaint_id" => 162, "client_id" => 561],
            ["complaint_id" => 163, "client_id" => 562],
            ["complaint_id" => 164, "client_id" => 563],
            ["complaint_id" => 165, "client_id" => 564],
            ["complaint_id" => 166, "client_id" => 565],
            ["complaint_id" => 167, "client_id" => 566],
            ["complaint_id" => 168, "client_id" => 567],
            ["complaint_id" => 169, "client_id" => 568],
            ["complaint_id" => 170, "client_id" => 569],
            ["complaint_id" => 171, "client_id" => 570],
            ["complaint_id" => 172, "client_id" => 571],

            ["complaint_id" => 173, "client_id" => 572],
            ["complaint_id" => 173, "client_id" => 573],
         
            ["complaint_id" => 174, "client_id" => 574],
            ["complaint_id" => 175, "client_id" => 575],
            ["complaint_id" => 176, "client_id" => 576],
            ["complaint_id" => 177, "client_id" => 577],
            ["complaint_id" => 178, "client_id" => 578],
            ["complaint_id" => 179, "client_id" => 579],
            ["complaint_id" => 180, "client_id" => 580],
            ["complaint_id" => 181, "client_id" => 581],
            ["complaint_id" => 182, "client_id" => 582],
            ["complaint_id" => 183, "client_id" => 583],
            ["complaint_id" => 184, "client_id" => 584],
            ["complaint_id" => 185, "client_id" => 585],
            ["complaint_id" => 186, "client_id" => 586],
            ["complaint_id" => 187, "client_id" => 587],
            ["complaint_id" => 188, "client_id" => 588],
            ["complaint_id" => 189, "client_id" => 589],
            ["complaint_id" => 190, "client_id" => 590],
            ["complaint_id" => 191, "client_id" => 591],
            ["complaint_id" => 192, "client_id" => 592],
            ["complaint_id" => 193, "client_id" => 593],
            ["complaint_id" => 194, "client_id" => 594],
            ["complaint_id" => 195, "client_id" => 595],
            ["complaint_id" => 196, "client_id" => 596],
            ["complaint_id" => 197, "client_id" => 597],
            ["complaint_id" => 198, "client_id" => 598],
            ["complaint_id" => 199, "client_id" => 599],
            ["complaint_id" => 200, "client_id" => 600],
            ["complaint_id" => 201, "client_id" => 601],


//***********************************************************************************************************************************************

            //SUBJECT FROM DOJ MAJOR CASES

            ["complaint_id" => 202, "client_id" => 683],
            ["complaint_id" => 202, "client_id" => 684],
            ["complaint_id" => 202, "client_id" => 685],
            ["complaint_id" => 202, "client_id" => 686],
            ["complaint_id" => 202, "client_id" => 687],

            ["complaint_id" => 203, "client_id" => 688],

            ["complaint_id" => 204, "client_id" => 689],
            ["complaint_id" => 204, "client_id" => 690],

            ["complaint_id" => 205, "client_id" => 691],
        );

        // Uncomment the below to run the seeder
        DB::table('complaint_subjects')->insert($complaint_subjects);
    }

}
