<?php

class Complaint_type_tagsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('complaint_type_tags')->truncate();

        $complaint_type_tags = array(
            ["complaint_id" => 1, "type_id" => "11", "type" => "Theft"],
            ["complaint_id" => 2, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 2, "type_id" => "94", "type" => "Grave threats"],
            ["complaint_id" => 3, "type_id" => "20", "type" => "Uncategorized"],
            ["complaint_id" => 4, "type_id" => "15", "type" => "Prostitution"],
            ["complaint_id" => 5, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 6, "type_id" => "7", "type" => "Homicide"],
            ["complaint_id" => 7, "type_id" => "78", "type" => "Suicide"],
            ["complaint_id" => 8, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 8, "type_id" => "84", "type" => "Serious physical injuries"],
            ["complaint_id" => 9, "type_id" => "76", "type" => "Parricide"],
            ["complaint_id" => 9, "type_id" => "80", "type" => "Infanticide"],
            ["complaint_id" => 10, "type_id" => "49", "type" => "Gambling and Betting"],
            ["complaint_id" => 11, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 12, "type_id" => "47", "type" => "Counterfeiting"],
            ["complaint_id" => 13, "type_id" => "112", "type" => "Abduction"],
            ["complaint_id" => 14, "type_id" => "19", "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 15, "type_id" => "19", "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 16, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 17, "type_id" => "7", "type" => "Homicide"],
            ["complaint_id" => 18, "type_id" => "19", "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 19, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 20, "type_id" => "7", "type" => "Homicide"],
            ["complaint_id" => 21, "type_id" => "19", "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 22, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 23, "type_id" => "7", "type" => "Homicide"],
            ["complaint_id" => 24, "type_id" => "7", "type" => "Homicide"],
            ["complaint_id" => 24, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 25, "type_id" => "78", "type" => "Suicide"],
            ["complaint_id" => 25, "type_id" => "16", "type" => "Vandalism"],
            ["complaint_id" => 26, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 27, "type_id" => "15", "type" => "Prostitution"],
            ["complaint_id" => 28, "type_id" => "19", "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 29, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 30, "type_id" => "47", "type" => "Counterfeiting"],
            ["complaint_id" => 31, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 32, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 33, "type_id" => "9", "type" => "Falsification"],
            ["complaint_id" => 34, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 35, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 35, "type_id" => "19", "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 36, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 37, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 37, "type_id" => "100", "type" => "Brigandage"],
            ["complaint_id" => 38, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 39, "type_id" => "104", "type" => "Arson"],
            ["complaint_id" => 40, "type_id" => "100", "type" => "Brigandage"],
            ["complaint_id" => 41, "type_id" => "83", "type" => "Mutilation"],
            ["complaint_id" => 42, "type_id" => "84", "type" => "Serious physical injuries"],
            ["complaint_id" => 43, "type_id" => "112", "type" => "Abduction"],
            ["complaint_id" => 44, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 45, "type_id" => "87", "type" => "Slavery"],
            ["complaint_id" => 46, "type_id" => "90", "type" => "Abandonment of helpless persons"],
            ["complaint_id" => 47, "type_id" => "15", "type" => "Prostitution"],
            ["complaint_id" => 48, "type_id" => "92", "type" => "Trespassing"],
            ["complaint_id" => 49, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 50, "type_id" => "75", "type" => "Abuses against chastity"],
            ["complaint_id" => 51, "type_id" => "87", "type" => "Slavery"],
            ["complaint_id" => 52, "type_id" => "100", "type" => "Brigandage"],
            ["complaint_id" => 53, "type_id" => "100", "type" => "Brigandage"],
            ["complaint_id" => 54, "type_id" => "11", "type" => "Theft"],
            ["complaint_id" => 55, "type_id" => "102", "type" => "Swindling"],
            ["complaint_id" => 56, "type_id" => "104", "type" => "Arson"],
            ["complaint_id" => 57, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 58, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 59, "type_id" => "59", "type" => "Bribery"],
            ["complaint_id" => 60, "type_id" => "112", "type" => "Abduction"],
            ["complaint_id" => 61, "type_id" => "81", "type" => "Abortion"],
            ["complaint_id" => 62, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 63, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 64, "type_id" => "11", "type" => "Theft"],
            ["complaint_id" => 65, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 66, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 67, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 68, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 69, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 70, "type_id" => "115", "type" => "Libel"],
            ["complaint_id" => 71, "type_id" => "104", "type" => "Arson"],
            ["complaint_id" => 72, "type_id" => "116", "type" => "Slander"],
            ["complaint_id" => 73, "type_id" => "115", "type" => "Libel"],
            ["complaint_id" => 74, "type_id" => "100", "type" => "Brigandage"],
            ["complaint_id" => 74, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 75, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 76, "type_id" => "107", "type" => "Adultery"],
            ["complaint_id" => 77, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 77, "type_id" => "19", "type" => "Possession of Dangerous Drugs For Sale"],
            ["complaint_id" => 78, "type_id" => "47", "type" => "Counterfeiting"],
            ["complaint_id" => 79, "type_id" => "47", "type" => "Counterfeiting"],
            ["complaint_id" => 80, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 81, "type_id" => "98", "type" => "Forgery"],
            ["complaint_id" => 82, "type_id" => "49", "type" => "Gambling and Betting"],
            ["complaint_id" => 82, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 83, "type_id" => "85", "type" => "Sexual Abuse"],
            ["complaint_id" => 84, "type_id" => "50", "type" => "Grave Scandal"],
            ["complaint_id" => 84, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 85, "type_id" => "43", "type" => "Public Disorder"],
            ["complaint_id" => 86, "type_id" => "40", "type" => "Direct Assault"],
            ["complaint_id" => 87, "type_id" => "98", "type" => "Forgery"],
            ["complaint_id" => 88, "type_id" => "59", "type" => "Bribery"],
            ["complaint_id" => 89, "type_id" => "61", "type" => "Prohibited Transaction"],
            ["complaint_id" => 90, "type_id" => "65", "type" => "Infidelity"],
            ["complaint_id" => 91, "type_id" => "67", "type" => "Disobedience"],
            ["complaint_id" => 92, "type_id" => "66", "type" => "Revelation of Secret"],
            ["complaint_id" => 93, "type_id" => "69", "type" => "Maltreatment of Prisoner"],
            ["complaint_id" => 93, "type_id" => "85", "type" => "Sexual Abuse"],
            ["complaint_id" => 94, "type_id" => "73", "type" => "Usurpation"],
            ["complaint_id" => 95, "type_id" => "78", "type" => "Suicide"],
            ["complaint_id" => 96, "type_id" => "81", "type" => "Abortion"],
            ["complaint_id" => 97, "type_id" => "80", "type" => "Infanticide"],
            ["complaint_id" => 98, "type_id" => "10", "type" => "Serious Illegal Detention"],
            ["complaint_id" => 98, "type_id" => "121", "type" => "Plunder"],
            ["complaint_id" => 99, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 100, "type_id" => "87", "type" => "Slavery"],
            ["complaint_id" => 101, "type_id" => "18", "type" => "Drunk Driving"],
            ["complaint_id" => 102, "type_id" => "19", "type" => "Possession of Dangerous Drugs"],
            ["complaint_id" => 102, "type_id" => "78", "type" => "Suicide"],
            ["complaint_id" => 103, "type_id" => "16", "type" => "Vandalism"],
            ["complaint_id" => 104, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 105, "type_id" => "21", "type" => "Treason"],
            ["complaint_id" => 106, "type_id" => "22", "type" => "Espionage"],
            ["complaint_id" => 107, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 108, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 108, "type_id" => "85", "type" => "Sexual Abuse"],
            ["complaint_id" => 109, "type_id" => "17", "type" => "Domestic Violence"],
            ["complaint_id" => 110, "type_id" => "31", "type" => "Petty Theft"],
            ["complaint_id" => 111, "type_id" => "26", "type" => "Arbitrary Detention"],
            ["complaint_id" => 112, "type_id" => "28", "type" => "Expulsion"],
            ["complaint_id" => 113, "type_id" => "29", "type" => "Violation of Domicile"],
            ["complaint_id" => 114, "type_id" => "30", "type" => "Prohibition, interruption, and dissolution of peaceful meetings"],
            ["complaint_id" => 115, "type_id" => "32", "type" => "Rebellion"],
            ["complaint_id" => 115, "type_id" => "67", "type" => "Disobedience"],
            ["complaint_id" => 116, "type_id" => "34", "type" => "Disloyalty"],
            ["complaint_id" => 117, "type_id" => "35", "type" => "Disturbance of Proceedings"],
            ["complaint_id" => 118, "type_id" => "38", "type" => "Illegal Assemblies"],
            ["complaint_id" => 119, "type_id" => "40", "type" => "Direct Assault"],
            ["complaint_id" => 119, "type_id" => "87", "type" => "Slavery"],
            ["complaint_id" => 120, "type_id" => "40", "type" => "Direct Assault"],
            ["complaint_id" => 121, "type_id" => "43", "type" => "Public Disorder"],
            ["complaint_id" => 122, "type_id" => "98", "type" => "Forgery"],
            ["complaint_id" => 123, "type_id" => "9", "type" => "Falsification"],
            ["complaint_id" => 123, "type_id" => "98", "type" => "Forgery"],
            ["complaint_id" => 124, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 125, "type_id" => "52", "type" => "Dereliction of Duty"],
            ["complaint_id" => 126, "type_id" => "59", "type" => "Bribery"],
            ["complaint_id" => 127, "type_id" => "61", "type" => "Prohibited Transaction"],
            ["complaint_id" => 127, "type_id" => "19", "type" => "Possession of Dangerous Drugs"],
            ["complaint_id" => 128, "type_id" => "65", "type" => "Infidelity"],
            ["complaint_id" => 129, "type_id" => "67", "type" => "Disobedience"],
            ["complaint_id" => 130, "type_id" => "98", "type" => "Forgery"],

//*********************************************************************************************************************************************************************************            
            
            ["complaint_id" => 131, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 132, "type_id" => "14", "type" => "Illegal Possession of Dangerous Drugs"],
            ["complaint_id" => 133, "type_id" => "2", "type" => "Illegal Possession of Firearms"],
            
            ["complaint_id" => 134, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 134, "type_id" => "5", "type" => "Murder"],
            
            ["complaint_id" => 135, "type_id" => "5", "type" => "Murder"],  
            ["complaint_id" => 136, "type_id" => "14", "type" => "Illegal Possession of Dangerous Drugs"],
            ["complaint_id" => 137, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 138, "type_id" => "8", "type" => "Estafa"],
            ["complaint_id" => 139, "type_id" => "8", "type" => "Estafa"],
            ["complaint_id" => 140, "type_id" => "8", "type" => "Estafa"],

            ["complaint_id" => 141, "type_id" => "13", "type" => "Illegal Recruitment"],
            ["complaint_id" => 141, "type_id" => "8", "type" => "Estafa"],

            ["complaint_id" => 142, "type_id" => "6", "type" => "Fraud"],
            
            ["complaint_id" => 143, "type_id" => "9", "type" => "Falsification"],
            ["complaint_id" => 143, "type_id" => "8", "type" => "Estafa"],
            ["complaint_id" => 143, "type_id" => "13", "type" => "Illegal Recruitment"],
            
            ["complaint_id" => 144, "type_id" => "13", "type" => "Illegal Recruitment"],
            ["complaint_id" => 145, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 146, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 147, "type_id" => "11", "type" => "Theft"],
            ["complaint_id" => 148, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 149, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 150, "type_id" => "6", "type" => "Fraud"],
            ["complaint_id" => 151, "type_id" => "8", "type" => "Estafa"],
            ["complaint_id" => 152, "type_id" => "8", "type" => "Estafa"],
            ["complaint_id" => 153, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 154, "type_id" => "6", "type" => "Fraud"],
            
            ["complaint_id" => 155, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 155, "type_id" => "5", "type" => "Murder"],
            
            ["complaint_id" => 156, "type_id" => "13", "type" => "Illegal Recruitment"],

            ["complaint_id" => 157, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 157, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 157, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 157, "type_id" => "10", "type" => "Serious Illegal Detention"],

            ["complaint_id" => 158, "type_id" => "13", "type" => "Illegal Recruitment"],

            ["complaint_id" => 159, "type_id" => "10", "type" => "Serious Illegal Detention"],
            ["complaint_id" => 159, "type_id" => "96", "type" => "Grave coercions"],

            ["complaint_id" => 160, "type_id" => "14", "type" => "Illegal Possession of Dangerous Drugs"],
            ["complaint_id" => 161, "type_id" => "2", "type" => "Illegal Possession of Firearms"],
            ["complaint_id" => 162, "type_id" => "13", "type" => "Illegal Recruitment"],
            ["complaint_id" => 163, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 164, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 165, "type_id" => "4", "type" => "Robbery"],

            ["complaint_id" => 166, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 166, "type_id" => "40", "type" => "Direct Assault"],
            ["complaint_id" => 166, "type_id" => "1", "type" => "Illegal Possession of Firearms, Ammunitions and Explosives"],

            ["complaint_id" => 167, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 167, "type_id" => "22", "type" => "Espionage"],
            
            ["complaint_id" => 168, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 169, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 170, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 171, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 172, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 173, "type_id" => "8", "type" => "Estafa"],
            ["complaint_id" => 174, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 175, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 176, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 177, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 178, "type_id" => "4", "type" => "Robbery"],

            ["complaint_id" => 179, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 179, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 179, "type_id" => "5", "type" => "Murder"],

            ["complaint_id" => 180, "type_id" => "12", "type" => "Kidnapping"],
            
            ["complaint_id" => 181, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 181, "type_id" => "120", "type" => "Child Abuse"],
            
            ["complaint_id" => 182, "type_id" => "5", "type" => "Murder"],
            
            ["complaint_id" => 183, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 183, "type_id" => "120", "type" => "Child Abuse"],
            
            ["complaint_id" => 184, "type_id" => "121", "type" => "Plunder"],

            ["complaint_id" => 185, "type_id" => "7", "type" => "Homicide"],
            ["complaint_id" => 185, "type_id" => "5", "type" => "Murder"],

            ["complaint_id" => 186, "type_id" => "12", "type" => "Kidnapping"],

            ["complaint_id" => 187, "type_id" => "94", "type" => "Grave threats"],
            ["complaint_id" => 187, "type_id" => "11", "type" => "Theft"],

            ["complaint_id" => 188, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 189, "type_id" => "12", "type" => "Kidnapping"],

            ["complaint_id" => 190, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 190, "type_id" => "7", "type" => "Homicide"],

            ["complaint_id" => 191, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 192, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 193, "type_id" => "4", "type" => "Robbery"],

            ["complaint_id" => 194, "type_id" => "12", "type" => "Kidnapping"],
            ["complaint_id" => 194, "type_id" => "3", "type" => "Rape"],

            ["complaint_id" => 195, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 195, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 195, "type_id" => "12", "type" => "Kidnapping"],

            ["complaint_id" => 196, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 196, "type_id" => "7", "type" => "Homicide"],

            ["complaint_id" => 197, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 198, "type_id" => "13", "type" => "Illegal Recruitment"],
            ["complaint_id" => 199, "type_id" => "12", "type" => "Kidnapping"],

            ["complaint_id" => 200, "type_id" => "4", "type" => "Robbery"],
            ["complaint_id" => 200, "type_id" => "7", "type" => "Homicide"],

            ["complaint_id" => 201, "type_id" => "3", "type" => "Rape"],
            ["complaint_id" => 201, "type_id" => "120", "type" => "Child Abuse"],
            
            ["complaint_id" => 202, "type_id" => "122", "type" => "Malversation of Public Funds"],
            ["complaint_id" => 203, "type_id" => "5", "type" => "Murder"],
            ["complaint_id" => 204, "type_id" => "123", "type" => "Tax Evasion"],
            ["complaint_id" => 205, "type_id" => "123", "type" => "Tax Evasion"],
        );

        // Uncomment the below to run the seeder
        DB::table('complaint_type_tags')->insert($complaint_type_tags);
    }

}
