<?php

class Evidence_documentsTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('evidence_documents')->truncate();

        $evidence_documents = array(
            ["user_id" => 10930216, "case_id" => 1, "details" => "Theft", "owner" => "Matteo Guidicelli",
                "title" => "Justin Bieber - Theft at High School in Marikina", "date_received" => "2014-01-26", "file_name" => "1.doc", "origin_id" => 1],
            ["user_id" => 10930216, "case_id" => 2, "details" => "Rape", "owner" => "Jay Contreras",
                "title" => "Maria Aguilar - Woman Claims to be Raped by Musician Chris Brown", "date_received" => "2014-02-12", "file_name" => "2.doc", "origin_id" => 2],
            ["user_id" => 10930216, "case_id" => 3, "details" => "Public Scandal", "owner" => "Jonathan Obrero",
                "title" => "Logan Alpay - Drunk Guy Orders Bulalo in a Bakery Shop and Started a Scandal", "date_received" => "2014-12-13", "file_name" => "3.doc", "origin_id" => 3],
            ["user_id" => 10930216, "case_id" => 4, "details" => "Prostitution", "owner" => "Willie So",
                "title" => "Kris Aquino & Claire Baclayan - Waitresses charged with misdemeanor prostitution", "date_received" => "2009-03-12", "file_name" => "4.doc", "origin_id" => 4],
            ["user_id" => 10930216, "case_id" => 5, "details" => "Murder", "owner" => "Uma Sumbingco",
                "title" => "Mike Jones - Engineer Stabbed by Garbage Collector", "date_received" => "2013-04-23", "file_name" => "5.doc", "origin_id" => 5],
            ["user_id" => 10930216, "case_id" => 6, "details" => "Shootout", "owner" => "Raven Bojos",
                "title" => "2 Engineers and 1 Principal Shot Dead in Surigao", "date_received" => "2013-01-15", "file_name" => "6.doc", "origin_id" => 6],
            ["user_id" => 10930216, "case_id" => 7, "details" => "Suicide", "owner" => "Domingo Arita",
                "title" => "Raymond Cadang - College Student from FEU Leapt from 25th Floor of His Condominium", "date_received" => "2013-01-26", "file_name" => "7.doc", "origin_id" => 7],
            ["user_id" => 10930216, "case_id" => 8, "details" => "Murder", "owner" => "Pierce Jonota",
                "title" => "Assistant Lecturer from DLSU found dead at Agno Gate with stabs in the head", "date_received" => "2013-02-07", "file_name" => "8.doc", "origin_id" => 8],
            ["user_id" => 10930216, "case_id" => 9, "details" => "Cannibalism", "owner" => "Rod Strunk",
                "title" => "Kristina Gacutan - Mother Ate Her 2 Children", "date_received" => "2013-03-06", "file_name" => "9.doc", "origin_id" => 9],
            ["user_id" => 10930216, "case_id" => 10, "details" => "Illegal Gambling", "owner" => "Recca Madoka",
                "title" => "3 Americans Allegedly Participated in Illegal Gambling in San Juan City", "date_received" => "2013-02-20", "file_name" => "10.doc", "origin_id" => 10],
            ["user_id" => 10930216, "case_id" => 11, "details" => "Terrorism", "owner" => "Adolf Hitler",
                "title" => "Bus Conductor from Leyte Planted Atomic Bomb On Bus", "date_received" => "2013-02-20", "file_name" => "11.doc", "origin_id" => 11],
            ["user_id" => 10930216, "case_id" => 12, "details" => "Counterfeiting", "owner" => "Atom Araullo",
                "title" => "Chistopher Sese, Gong Wai See, Karlo Martinez - 2 Businessmen and 1 Househusband Found Guilty of Counterfeiting Coins", "date_received" => "2013-04-01", "file_name" => "12.doc", "origin_id" => 12],
            ["user_id" => 10930216, "case_id" => 13, "details" => "Abduction", "owner" => "Zee Ambrosio",
                "title" => "Businessman From China Abducted 5 Children", "date_received" => "2013-04-10", "file_name" => "13.doc", "origin_id" => 13],
            ["user_id" => 10930216, "case_id" => 14, "details" => "Illegal Drugs", "owner" => "Juni Silva",
                "title" => "2 Drug Dealers Found Dealing Marijuana in Benguet", "date_received" => "2013-05-03", "file_name" => "14.doc", "origin_id" => 14],
            ["user_id" => 10930216, "case_id" => 15, "details" => "Illegal Drugs", "owner" => "Joey Ty",
                "title" => "Top Drug Lord Spotted in Taguig", "date_received" => "2013-05-23", "file_name" => "15.doc", "origin_id" => 15],
            ["user_id" => 10930216, "case_id" => 16, "details" => "Money Laundering", "owner" => "Wilhelm Hung",
                "title" => "Serendra - Serendra Developers Convicted Of Laundering Thousands of Dollars", "date_received" => "2013-06-10", "file_name" => "16.doc", "origin_id" => 16],
            ["user_id" => 10930216, "case_id" => 17, "details" => "Stray Bullet", "owner" => "Jose Maria Villacorta",
                "title" => "Gym Instructor Hit By A Stray Bullet in the Head While Jogging in the Morning", "date_received" => "2013-06-17", "file_name" => "17.doc", "origin_id" => 17],
            ["user_id" => 10930216, "case_id" => 18, "details" => "Illegal Drugs", "owner" => "Kali Kariman",
                "title" => "Drug Pusher Found Dead In Caloocan City After Trying To Sell Illegal Drugs", "date_received" => "2013-07-08", "file_name" => "18.doc", "origin_id" => 18],
            ["user_id" => 10930216, "case_id" => 19, "details" => "Rape", "owner" => "Jun Sabayton",
                "title" => "Boyfriend Forced Girlfriend To Have Sex With Her", "date_received" => "2013-07-27", "file_name" => "19.doc", "origin_id" => 19],
            ["user_id" => 10930216, "case_id" => 20, "details" => "Accidental Shooting", "owner" => "Mikasa Ackerman",
                "title" => "Veronica Co - Woman Accidentally Fires His Gun at His Three Friends During at a Shooting Range", "date_received" => "2013-08-12", "file_name" => "20.doc", "origin_id" => 20],
            ["user_id" => 10930216, "case_id" => 21, "details" => "Illegal Drugs", "owner" => "Eren Jaeger",
                "title" => "Sylvia Ang - Top Druglord in Zamboanga Strikes Again After Being Released From Jail", "date_received" => "2013-08-29", "file_name" => "21.doc", "origin_id" => 21],
            ["user_id" => 10930216, "case_id" => 22, "details" => "Inflicing Physical Injuries", "owner" => "Habab Baluda",
                "title" => "Mariz Tamboa - Paramedic Stabbed By a Woman While Taking A Leak", "date_received" => "2013-09-11", "file_name" => "22.doc", "origin_id" => 22],
            ["user_id" => 10930216, "case_id" => 23, "details" => "Drunk Driving", "owner" => "Rreuno Velasco",
                "title" => "Monica Velasco - Female DUI of Alcohol Shot A Bypasser Jogging on the Roadside", "date_received" => "2013-09-22", "file_name" => "23.doc", "origin_id" => 23],
            ["user_id" => 10930216, "case_id" => 24, "details" => "Robbery", "owner" => "Martin Quinahan",
                "title" => "5 Suspects Robbed Security Bank in Alabang", "date_received" => "2013-09-23", "file_name" => "24.doc", "origin_id" => 24],
            ["user_id" => 10930216, "case_id" => 25, "details" => "Suicide", "owner" => "Jim Paredes",
                "title" => "Jack Baloala - Architect Commited Suicide In Pasay City", "date_received" => "2013-10-23", "file_name" => "25.doc", "origin_id" => 25],
            ["user_id" => 10930216, "case_id" => 26, "details" => "Rape", "owner" => "Georges St. Pierre",
                "title" => "Richmond Collins - American Accountant Raped Filipina Co-Worker", "date_received" => "2013-11-03", "file_name" => "26.doc", "origin_id" => 26],
            ["user_id" => 10930216, "case_id" => 27, "details" => "Prostitution", "owner" => "Dim Dumaual",
                "title" => "Tyrone Tecson, Eun Hyuk Park, & Bert Lee - DLSU Professors Reported To Be Prostitutes Giving Service To Clients In Pubs At Pedro Gil", "date_received" => "2013-11-23", "file_name" => "27.doc", "origin_id" => 27],
            ["user_id" => 10930216, "case_id" => 28, "details" => "Illegal Drug Dealing", "owner" => "Herbert Bautista",
                "title" => "Sungyeol Choi & Myungsoo Choi - 2 Korean Students Caught Dealing Illegal Drugs In Quezon City", "date_received" => "2013-12-01", "file_name" => "28.doc", "origin_id" => 28],
            ["user_id" => 10930216, "case_id" => 29, "details" => "Rape", "owner" => "Matthew McDonald",
                "title" => "Gary Michael Waters - Uncle Rapes Her Niece On Her Birthday", "date_received" => "2013-12-18", "file_name" => "29.doc", "origin_id" => 29],
            ["user_id" => 10930216, "case_id" => 30, "details" => "Counterfeiting", "owner" => "Biboy Ortiz",
                "title" => "Johnson Smith & Simon Davis - African-American Businessmen Providing Shops Fake Cellular Phones and Mobile Phone Equipment", "date_received" => "2013-12-28", "file_name" => "30.doc", "origin_id" => 30],
            ["user_id" => 10930216, "case_id" => 31, "details" => "Murder", "owner" => "Scott Brooks",
                "title" => "Gino Haparam - DLSU Student Shot Dead Outside EGI Apartment in Manila", "date_received" => "2013-01-02", "file_name" => "31.doc", "origin_id" => 31],
            ["user_id" => 10930216, "case_id" => 32, "details" => "Fraud", "owner" => "Gumba Sotto",
                "title" => "Mark Anthony Collins & Jacob Reed - Butcher and Fireman indicted on fraud charges", "date_received" => "2013-04-18", "file_name" => "32.doc", "origin_id" => 32],
            ["user_id" => 10930216, "case_id" => 33, "details" => "Fraud", "owner" => "Jobert Sucaldito",
                "title" => "Matthew Morgan - American Fireman Accused Of Using A Contractor's License And Fraudaulent Use Of Funds", "date_received" => "2014-01-13", "file_name" => "33.doc", "origin_id" => 33],
            ["user_id" => 10930216, "case_id" => 34, "details" => "Fraud", "owner" => "Luke Walton",
                "title" => "Liam Morgan - American Manager To Be Sentencet In Court To 12 Years For Defrauding Filipino Businessman", "date_received" => "2014-02-04", "file_name" => "34.doc", "origin_id" => 34],
            ["user_id" => 10930216, "case_id" => 35, "details" => "Fraud", "owner" => "Kier Legaspi",
                "title" => "Jackson Kelly - Attempted Fraud on Gift Cards", "date_received" => "2014-03-05", "file_name" => "35.doc", "origin_id" => 35],
            ["user_id" => 10930216, "case_id" => 36, "details" => "Fraud", "owner" => "Ramone Parica",
                "title" => "Ryan Dylan Wood - Mastermind of a multi-billion dollar fraud", "date_received" => "2014-01-28", "file_name" => "36.doc", "origin_id" => 36],
            ["user_id" => 10930216, "case_id" => 37, "details" => "Robbery", "owner" => "Lanus Crassus",
                "title" => "2 Masked Men Robbed RCBC in Quezon City", "date_received" => "2014-03-18", "file_name" => "37.doc", "origin_id" => 37],
            ["user_id" => 10930216, "case_id" => 38, "details" => "Road Rage Shooting", "owner" => "Bill Laimbeer",
                "title" => "Landon Jordan - Australian Politician Charged With Multiple Counts Of Range Shooting Resulting To Multiple Deaths", "date_received" => "2013-05-29", "file_name" => "38.doc", "origin_id" => 38],
            ["user_id" => 10930216, "case_id" => 39, "details" => "Arson", "owner" => "Jack Nicholson",
                "title" => "Jack Marshall - Australian Politician Sets Elementary School Teacher's House On fire", "date_received" => "2013-02-02", "file_name" => "39.doc", "origin_id" => 39],
            ["user_id" => 10930216, "case_id" => 40, "details" => "Robbery", "owner" => "Boom Gonzalez",
                "title" => "Connor Charles Hunter - Australian Pilot Accused of Robbing an IT Professional in a supermarket in Sta. Mesa", "date_received" => "2013-07-13", "file_name" => "40.doc", "origin_id" => 40],
            ["user_id" => 10930216, "case_id" => 41, "details" => "Female Mutilation", "owner" => "Jinggo Madamba",
                "title" => "Lay Zhang - Female Mutilation of San Beda Student, Clarice Ona", "date_received" => "2013-04-24", "file_name" => "41.doc", "origin_id" => 41],
            ["user_id" => 10930216, "case_id" => 42, "details" => "Battered Wife", "owner" => "Kevin Durant",
                "title" => "Yi Wu - Battered His Wife, Hanna Wu", "date_received" => "2013-01-16", "file_name" => "42.doc", "origin_id" => 42],
            ["user_id" => 10930216, "case_id" => 43, "details" => "Kidnapping", "owner" => "Serge Ibaka",
                "title" => "Ming Chiu - Chinese Plumber Kidnapped And Enslaved 10-Year Old Boy", "date_received" => "2013-01-26", "file_name" => "43.doc", "origin_id" => 43],
            ["user_id" => 10930216, "case_id" => 44, "details" => "Rape", "owner" => "Ming Yao",
                "title" => "Ming Chiu - Chinese Plumber Raped a Business Student", "date_received" => "2013-02-07", "file_name" => "44.doc", "origin_id" => 44],
            ["user_id" => 10930216, "case_id" => 45, "details" => "Child Abduction", "owner" => "Rick Fox",
                "title" => "Bing Ng - Abducted Jasper Hans Chua", "date_received" => "2012-02-20", "file_name" => "45.doc", "origin_id" => 45],
            ["user_id" => 10930216, "case_id" => 46, "details" => "Abandonment of a Helpless Person", "owner" => "Derek Fisher",
                "title" => "Chuan Tsui - Disregarded A Man Being Attacked", "date_received" => "2013-03-05", "file_name" => "46.doc", "origin_id" => 46],
            ["user_id" => 10930216, "case_id" => 47, "details" => "Illegal Drug Possession", "owner" => "Rob Thomas",
                "title" => "Minami Takahashi - Seen In Possession of Illegal Drugs inside a Hotel in Pedro Gil", "date_received" => "2013-03-30", "file_name" => "47.doc", "origin_id" => 47],
            ["user_id" => 10930216, "case_id" => 48, "details" => "Trespassing", "owner" => "Johnny Abarrientos",
                "title" => "Atsuko Maeda - AKB48 Frontman Trespassed A Private Property In Quezon City", "date_received" => "2013-03-20", "file_name" => "48.doc", "origin_id" => 48],
            ["user_id" => 10930216, "case_id" => 49, "details" => "Medical Malpractice", "owner" => "Michael Bibby",
                "title" => "Sakura Yamamoto - Japan-based nurse injected an illegal drug to a patient", "date_received" => "2013-04-01", "file_name" => "49.doc", "origin_id" => 49],
            ["user_id" => 10930216, "case_id" => 50, "details" => "Child Abuse", "owner" => "Simon Atkins",
                "title" => "Bing Ng - Child Abused and Threatened a Filipino-Amrican Child", "date_received" => "2013-04-01", "file_name" => "50.doc", "origin_id" => 50],
            ["user_id" => 10930216, "case_id" => 51, "details" => "Slavery", "owner" => "Beau Belga",
                "title" => "Bing Ng - Enslaved his Son, Bo Ng at Home", "date_received" => "2013-05-22", "file_name" => "51.doc", "origin_id" => 51],
            ["user_id" => 10930216, "case_id" => 52, "details" => "Brigandage", "owner" => "Jayson Castro",
                "title" => "Batsi Gang - Brigandage In SM Sta. Mesa", "date_received" => "2013-06-12", "file_name" => "52.doc", "origin_id" => 52],
            ["user_id" => 10930216, "case_id" => 53, "details" => "Brigandage", "owner" => "Mark Caguioa",
                "title" => "Batsi Gang - Robbery Of Rafael Lazo", "date_received" => "2013-06-17", "file_name" => "53.doc", "origin_id" => 53],
            ["user_id" => 10930216, "case_id" => 54, "details" => "Theft", "owner" => "June Mar Fajardo",
                "title" => "A Vietnamese Woman Stole An Antique Jar From Richard Rabago, a Businessman", "date_received" => "2013-05-23", "file_name" => "54.doc", "origin_id" => 54],
            ["user_id" => 10930216, "case_id" => 55, "details" => "Swindling", "owner" => "Marko Moraga",
                "title" => "Watanabe Mayu - Swindled P150M from Actor Vice Ganda", "date_received" => "2013-07-28", "file_name" => "55.doc", "origin_id" => 55],
            ["user_id" => 10930216, "case_id" => 56, "details" => "Arson", "owner" => "Dick Joaquin",
                "title" => "Jack Marshall - Arson Attacks On Parked Cars, Scorched Buildings, and Public Disturbance In The City", "date_received" => "2013-08-11", "file_name" => "56.doc", "origin_id" => 56],
            ["user_id" => 10930216, "case_id" => 57, "details" => "Rape", "owner" => "Migo Elisan",
                "title" => "Chris Brown - Suspected Father of Stephanie Germanotta, A Woman He Raped", "date_received" => "2013-08-30", "file_name" => "57.doc", "origin_id" => 57],
            ["user_id" => 10930216, "case_id" => 58, "details" => "Rape", "owner" => "Mark Heussaff",
                "title" => "Chris Brown - Raped Filipina Actress Anne Curtis-Smith", "date_received" => "2013-09-10", "file_name" => "58.doc", "origin_id" => 58],
            ["user_id" => 10930216, "case_id" => 59, "details" => "Bribery", "owner" => "Ogie Alcasid",
                "title" => "Christian Tiangco - Bribed Boy Abunda P10M To Reveal Showbiz Scoops", "date_received" => "2013-09-21", "file_name" => "59.doc", "origin_id" => 59],
            ["user_id" => 10930216, "case_id" => 60, "details" => "Kidnapping", "owner" => "Rally Coronacion",
                "title" => "Ming Li Chiu - Abducted Children For Human Trafficking", "date_received" => "2013-10-12", "file_name" => "60.doc", "origin_id" => 60],
            ["user_id" => 10930216, "case_id" => 61, "details" => "Abortion", "owner" => "Bon Bernales",
                "title" => "Sabel Sadural - Aborted Her Baby and Shared It On Social Media", "date_received" => "2013-10-15", "file_name" => "61.doc", "origin_id" => 61],
            ["user_id" => 10930216, "case_id" => 62, "details" => "Infanticide", "owner" => "Rajko Toriman",
                "title" => "Anton Saley - Killed His Own Son After Cricket Practice", "date_received" => "2013-10-12", "file_name" => "62.doc", "origin_id" => 62],
            ["user_id" => 10930216, "case_id" => 63, "details" => "Rape", "owner" => "Thomas Cruz",
                "title" => "Yamato Akitsuki - Japanese Exchange Student Raped His Professor", "date_received" => "2013-06-04", "file_name" => "63.doc", "origin_id" => 63],
            ["user_id" => 10930216, "case_id" => 64, "details" => "Theft", "owner" => "Ricardo Panganiban",
                "title" => "Karla Talaba - Nurse from Makati Memorial Center stole radioactive cobalt-60", "date_received" => "2008-12-15", "file_name" => "64.doc", "origin_id" => 64],
            ["user_id" => 10930216, "case_id" => 65, "details" => "Parricide", "owner" => "Michael Millanes",
                "title" => "Justin Tomawis - Killed His Father While Driving Him To School", "date_received" => "2013-06-10", "file_name" => "65.doc", "origin_id" => 65],
            ["user_id" => 10930216, "case_id" => 66, "details" => "Murder", "owner" => "Ernie Escayde",
                "title" => "Albert Agonoy - Pushed co-welder off the roof after a heated argument", "date_received" => "2013-06-10", "file_name" => "66.doc", "origin_id" => 66],
            ["user_id" => 10930216, "case_id" => 67, "details" => "Murder", "owner" => "Ramil de Jesus",
                "title" => "Aldrich Cabello - Murder of His Girlfriend Mica Reyes Inside The Car", "date_received" => "2008-12-15", "file_name" => "67.doc", "origin_id" => 67],
            ["user_id" => 10930216, "case_id" => 68, "details" => "Murder", "owner" => "Jejomar Binay",
                "title" => "Julio Macaraeg - Murder of Own Son, MJ Macaraeg In Exchange For Marijuana", "date_received" => "2008-12-15", "file_name" => "68.doc", "origin_id" => 68],
            ["user_id" => 10930216, "case_id" => 69, "details" => "Robbery", "owner" => "Juliano Panganiban",
                "title" => "Sebastian Hastings - Robbed A Bingo Hall And Inflicted Physical Injuries On A CEU Nursing Student", "date_received" => "2013-07-27", "file_name" => "69.doc", "origin_id" => 69],
            ["user_id" => 10930216, "case_id" => 70, "details" => "Libel", "owner" => "Lou Chua",
                "title" => "Anthony Manalo - False Accusation Against Jim Dwyer", "date_received" => "2013-04-01", "file_name" => "70.doc", "origin_id" => 70],
            ["user_id" => 10930216, "case_id" => 71, "details" => "Adultery", "owner" => "John Paul Fernandez",
                "title" => "Jack Marshall - Had An Affair With Another Woman And Set An Abandoned Building On Fire", "date_received" => "2009-07-27", "file_name" => "71.doc", "origin_id" => 71],
            ["user_id" => 10930216, "case_id" => 72, "details" => "Slander", "owner" => "Jomari Yllana",
                "title" => "Allan Cardona - Corruption", "date_received" => "2013-04-01", "file_name" => "72.doc", "origin_id" => 72],
            ["user_id" => 10930216, "case_id" => 73, "details" => "Defamation & Malicious Prosecution", "owner" => "Ricardo Panganiban",
                "title" => "Landon Jordan - Australian Politician Sued $60M In A Maternity Ward Scuffle", "date_received" => "2013-08-10", "file_name" => "73.doc", "origin_id" => 73],
            ["user_id" => 10930216, "case_id" => 74, "details" => "Robbery", "owner" => "Ricardo Panganiban",
                "title" => "Paulo Arcilla & Samson Sangui - Attempted Robbery Of Card Numbers", "date_received" => "2013-08-10", "file_name" => "74.doc", "origin_id" => 74],
            ["user_id" => 10930216, "case_id" => 75, "details" => "Rape", "owner" => "Ricardo Panganiban",
                "title" => "Richmond Collins - American Raped Korean Student Krystal Jung Inside A Boarding House In Malate", "date_received" => "2013-08-10", "file_name" => "75.doc", "origin_id" => 75],
            ["user_id" => 10930216, "case_id" => 76, "details" => "Adultery", "owner" => "Enzo Ortiz",
                "title" => "Lance Kurtis Alipio - Cheated On His Wife By Raping His Niece", "date_received" => "2013-09-13", "file_name" => "76.doc", "origin_id" => 76],
            ["user_id" => 10930216, "case_id" => 77, "details" => "Murder", "owner" => "Jomal Linao",
                "title" => "Sungyeol Choi - Deals Drugs to High School Students", "date_received" => "2010-01-13", "file_name" => "77.doc", "origin_id" => 77],
            ["user_id" => 10930216, "case_id" => 78, "details" => "Counterfeiting", "owner" => "Gus Abelgas",
                "title" => "Counterfeit iPhones being sold in Greenhills Shopping Center", "date_received" => "2010-12-30", "file_name" => "78.doc", "origin_id" => 78],
            ["user_id" => 10930216, "case_id" => 79, "details" => "Counterfeiting", "owner" => "Noli De Castro",
                "title" => "Gong Wai See - Printing Of Fake Dollar Bills", "date_received" => "2010-12-03", "file_name" => "79.doc", "origin_id" => 79],
            ["user_id" => 10930216, "case_id" => 80, "details" => "Kidnapping", "owner" => "Julius Babao",
                "title" => "Xiong Chua - Chinese Businessman Kidnapped A 7-Year Old Girl", "date_received" => "2009-12-23", "file_name" => "80.doc", "origin_id" => 80],
            ["user_id" => 10930216, "case_id" => 81, "details" => "Forged Signature", "owner" => "Ricardo Panganiban",
                "title" => "Bea Puzon - Forged Signature", "date_received" => "2008-12-15", "file_name" => "81.doc", "origin_id" => 81],
            ["user_id" => 10930216, "case_id" => 82, "details" => "Street Gambling", "owner" => "Ramon Sto. Domingo",
                "title" => "Bernice Bassig - Street Gambling", "date_received" => "2008-12-05", "file_name" => "82.doc", "origin_id" => 82],
            ["user_id" => 10930216, "case_id" => 83, "details" => "Sexual Abuse", "owner" => "Rodolfo Fuentes",
                "title" => "Natasha Ocampo - Sexually Abused Teenager", "date_received" => "2008-12-15", "file_name" => "83.doc", "origin_id" => 83],
            ["user_id" => 10930216, "case_id" => 84, "details" => "Grave Scandal", "owner" => "Onemig Bondoc",
                "title" => "Katherine Pascual - Grave Scandal", "date_received" => "2010-12-16", "file_name" => "84.doc", "origin_id" => 84],
            ["user_id" => 10930216, "case_id" => 85, "details" => "Public Disorder", "owner" => "Nonnatus Rojas",
                "title" => "Timi Gatdula - Public Disorder", "date_received" => "2012-12-20", "file_name" => "85.doc", "origin_id" => 85],
            ["user_id" => 10930216, "case_id" => 86, "details" => "Direct Assault", "owner" => "Cedric Lee",
                "title" => "Mia Serra - Direct Assault", "date_received" => "2011-12-16", "file_name" => "86.doc", "origin_id" => 86],
            ["user_id" => 10930216, "case_id" => 87, "details" => "Forgery", "owner" => "Ramiro Rey",
                "title" => "Elayssa Feryas - Forgery", "date_received" => "2011-12-20", "file_name" => "87.doc", "origin_id" => 87],
            ["user_id" => 10930216, "case_id" => 88, "details" => "Bribery", "owner" => "James Calleja",
                "title" => "Pamela Mendiola - Bribery", "date_received" => "2011-12-18", "file_name" => "88.doc", "origin_id" => 88],
            ["user_id" => 10930216, "case_id" => 89, "details" => "Prohibited Transaction Case", "owner" => "James Tosoc",
                "title" => "Judith Pasay - Prohibited Transaction Case", "date_received" => "2011-12-22", "file_name" => "89.doc", "origin_id" => 89],
            ["user_id" => 10930216, "case_id" => 90, "details" => "Infidelity", "owner" => "Santino Gajo",
                "title" => "Mikaella Makati - Infidelity Case", "date_received" => "2013-12-25", "file_name" => "90.doc", "origin_id" => 90],
            ["user_id" => 10930216, "case_id" => 91, "details" => "Disobedience", "owner" => "Johnny Rocket",
                "title" => "Junelle Recto - Disobedience", "date_received" => "2008-12-05", "file_name" => "91.doc", "origin_id" => 91],
            ["user_id" => 10930216, "case_id" => 92, "details" => "Unidentified Case", "owner" => "Ramon Villacorta",
                "title" => "Jesebel Osmena - Unidentified Case", "date_received" => "2011-11-13", "file_name" => "92.doc", "origin_id" => 92],
            ["user_id" => 10930216, "case_id" => 93, "details" => "Maltreatment", "owner" => "Magtanggol Gatdula",
                "title" => "SPO1 Michael Enriquez - Maltreatment in the PNP", "date_received" => "2012-12-25", "file_name" => "93.doc", "origin_id" => 93],
            ["user_id" => 10930216, "case_id" => 94, "details" => "Usurpation", "owner" => "Leomar Pedron",
                "title" => "Usurpation - Corazon Aquino", "date_received" => "2012-12-24", "file_name" => "94.doc", "origin_id" => 94],
            ["user_id" => 10930216, "case_id" => 95, "details" => "Suicide", "owner" => "Tomas Quinahan",
                "title" => "James Martinez - Commited Suicide", "date_received" => "2012-12-30", "file_name" => "95.doc", "origin_id" => 95],
            ["user_id" => 10930216, "case_id" => 96, "details" => "Abortion", "owner" => "Juan Ballesteros",
                "title" => "Lucila Criselda - Abortion", "date_received" => "2012-12-26", "file_name" => "96.doc", "origin_id" => 96],
            ["user_id" => 10930216, "case_id" => 97, "details" => "Infanticide", "owner" => "Julio Climaco",
                "title" => "Fernando Amorsolo - Infanticide", "date_received" => "2013-12-30", "file_name" => "97.doc", "origin_id" => 97],
            ["user_id" => 10930216, "case_id" => 98, "details" => "Illegal Detention", "owner" => "Allan Cornejo",
                "title" => "Janet Lim Napoles - Pork Barrel Queen", "date_received" => "2013-12-30", "file_name" => "98.doc", "origin_id" => 98],
            ["user_id" => 10930216, "case_id" => 99, "details" => "Kidnapping", "owner" => "Zimmer Ranz",
                "title" => "Darwin Daroy - Kidnapping ", "date_received" => "2014-01-05", "file_name" => "99.doc", "origin_id" => 99],
            ["user_id" => 10930216, "case_id" => 100, "details" => "Slavery", "owner" => "Cesar Milan",
                "title" => "Enrico Roco - Slavery", "date_received" => "2014-01-07", "file_name" => "100.doc", "origin_id" => 100],
            ["user_id" => 10930216, "case_id" => 101, "details" => "Drunk Driving", "owner" => "Ernesto Tauyan",
                "title" => "Jonathan Ochoa - DUI of Alcohol", "date_received" => "2009-05-05", "file_name" => "101.doc", "origin_id" => 101],
            ["user_id" => 10930216, "case_id" => 102, "details" => "Drug Possession", "owner" => "Jimboy Garcia",
                "title" => "Ernesto Villamin - Illegal Possession of Drugs", "date_received" => "2009-05-04", "file_name" => "102.doc", "origin_id" => 102],
            ["user_id" => 10930216, "case_id" => 103, "details" => "Vandalism", "owner" => "Jonathan Canete",
                "title" => "Armando Villena - Vandalism", "date_received" => "2010-05-05", "file_name" => "103.doc", "origin_id" => 103],
            ["user_id" => 10930216, "case_id" => 104, "details" => "Robbery", "owner" => "Michael Noble",
                "title" => "Carlo Sta. Ana & Patrick Hubalde - Robbery", "date_received" => "2010-05-05", "file_name" => "104.doc", "origin_id" => 104],
            ["user_id" => 10930216, "case_id" => 105, "details" => "Treason", "owner" => "Vic Sotto",
                "title" => "Algeirn Cupido - Treason", "date_received" => "2013-11-01", "file_name" => "105.doc", "origin_id" => 105],
            ["user_id" => 10930216, "case_id" => 106, "details" => "Espionage", "owner" => "Mark Galarpe",
                "title" => "Joey Gutierrez - Espionage", "date_received" => "2012-05-13", "file_name" => "106.doc", "origin_id" => 106],
            ["user_id" => 10930216, "case_id" => 107, "details" => "Robbery", "owner" => "Marvin Schaer",
                "title" => "Andy Kanto - Robbery", "date_received" => "2012-05-18", "file_name" => "107.doc", "origin_id" => 107],
            ["user_id" => 10930216, "case_id" => 108, "details" => "Rape", "owner" => "Earl Flores",
                "title" => "Kevin Macatangay - Rape", "date_received" => "2013-05-20", "file_name" => "108.doc", "origin_id" => 108],
            ["user_id" => 10930216, "case_id" => 109, "details" => "Domestic Violence", "owner" => "Jem Sedayao",
                "title" => "Juan Abadicio - Domestic Violence", "date_received" => "2013-05-25", "file_name" => "109.doc", "origin_id" => 109],
            ["user_id" => 10930216, "case_id" => 110, "details" => "Petty Theft", "owner" => "Justin Miranda",
                "title" => "Abo Acleb - Petty Theft", "date_received" => "2013-05-30", "file_name" => "110.doc", "origin_id" => 110],
            ["user_id" => 10930216, "case_id" => 111, "details" => "Arbitrary Detention", "owner" => "Inigo Jimenez",
                "title" => "Carlito Alupido - Arbitrary Detention", "date_received" => "2010-02-03", "file_name" => "111.doc", "origin_id" => 111],
            ["user_id" => 10930216, "case_id" => 112, "details" => "Expulsion", "owner" => "Michael Lee",
                "title" => "Samuel Aglipay - Expulsion", "date_received" => "2010-02-03", "file_name" => "112.doc", "origin_id" => 112],
            ["user_id" => 10930216, "case_id" => 113, "details" => "Violation of Domicile", "owner" => "Nigel Bojos",
                "title" => "Ricardo Aglido - Violation of Domicile", "date_received" => "2010-02-09", "file_name" => "113.doc", "origin_id" => 113],
            ["user_id" => 10930216, "case_id" => 114, "details" => "Prohibition, Interruption, and Dissolution of Peaceful Meetings", "owner" => "Angelo Dayot",
                "title" => "Benigno Afrilami - Multiple Offensed During Peaceful Meetings", "date_received" => "2011-02-15", "file_name" => "114.doc", "origin_id" => 114],
            ["user_id" => 10930216, "case_id" => 115, "details" => "Rebellion", "owner" => "Vince Salles",
                "title" => "Daniel Bercasio - Rebellion", "date_received" => "2011-02-18", "file_name" => "115.doc", "origin_id" => 115],
            ["user_id" => 10930216, "case_id" => 116, "details" => "Disloyalty", "owner" => "Gabriel Domingo",
                "title" => "Eclestio Borromeo - Disloyalty", "date_received" => "2013-02-18", "file_name" => "116.doc", "origin_id" => 116],
            ["user_id" => 10930216, "case_id" => 117, "details" => "Disturbance of Proceedings", "owner" => "Alex Carcaso",
                "title" => "Mark Bermudez - Disturbance of Proceedings", "date_received" => "2013-02-20", "file_name" => "117.doc", "origin_id" => 117],
            ["user_id" => 10930216, "case_id" => 118, "details" => "Illegal Assemblies", "owner" => "Jerome Bermudez",
                "title" => "Dave Bermillo - Illegal Assemblies", "date_received" => "2013-02-22", "file_name" => "118.doc", "origin_id" => 118],
            ["user_id" => 10930216, "case_id" => 119, "details" => "Direct Assault", "owner" => "Andres Bonifacio",
                "title" => "Annete Cruz - Direct Assault", "date_received" => "2014-02-27", "file_name" => "119.doc", "origin_id" => 119],
            ["user_id" => 10930216, "case_id" => 120, "details" => "Direct Assault", "owner" => "Jose Rizal",
                "title" => "Angela Criselda - Direct Assault", "date_received" => "2014-02-29", "file_name" => "120.doc", "origin_id" => 120],
            ["user_id" => 10930216, "case_id" => 121, "details" => "Public Disorder", "owner" => "Rujie De Veyra",
                "title" => "Aubrey Catindig - Public Disorder", "date_received" => "2009-10-03", "file_name" => "121.doc", "origin_id" => 121],
            ["user_id" => 10930216, "case_id" => 122, "details" => "Forgery", "owner" => "Dindin Agustin",
                "title" => "Miley Cauricio - Forgery", "date_received" => "2009-10-03", "file_name" => "122.doc", "origin_id" => 122],
            ["user_id" => 10930216, "case_id" => 123, "details" => "Falsification", "owner" => "Jun Vergara",
                "title" => "Ashley Dagonoy - Falsification of Documents ", "date_received" => "2010-10-04", "file_name" => "123.doc", "origin_id" => 123],
            ["user_id" => 10930216, "case_id" => 124, "details" => "Fraud", "owner" => "Dom Brucal",
                "title" => "Nicole Dalig - Electronic Card Fraud", "date_received" => "2010-10-07", "file_name" => "124.doc", "origin_id" => 124],
            ["user_id" => 10930216, "case_id" => 125, "details" => "Dereliction of Duty", "owner" => "Joma Pantango",
                "title" => "Trixie Duterte - Dereliction of Duty", "date_received" => "2014-01-07", "file_name" => "125.doc", "origin_id" => 125],
            ["user_id" => 10930216, "case_id" => 126, "details" => "Bribery", "owner" => "Clarence Goyokpin",
                "title" => "Rosanna Fernando - Bribery", "date_received" => "2011-10-15", "file_name" => "126.doc", "origin_id" => 126],
            ["user_id" => 10930216, "case_id" => 127, "details" => "Prohibited Transaction", "owner" => "Johnny Bravo",
                "title" => "Rosanne Fuentes - Prohibited Transaction", "date_received" => "2012-10-16", "file_name" => "127.doc", "origin_id" => 127],
            ["user_id" => 10930216, "case_id" => 128, "details" => "Infidelity", "owner" => "Uma Sundiaco",
                "title" => "Reggie Faminial - Infidelity", "date_received" => "2012-10-22", "file_name" => "128.doc", "origin_id" => 128],
            ["user_id" => 10930216, "case_id" => 129, "details" => "Disobedience", "owner" => "Goran Morato",
                "title" => "Lauren Marinias - Disobedience", "date_received" => "2012-10-23", "file_name" => "129.doc", "origin_id" => 129],
            ["user_id" => 10930216, "case_id" => 130, "details" => "Forgery", "owner" => "Michael Miniano",
                "title" => "Lovely Bueno & Leslie Antonio - Forgery", "date_received" => "2013-11-01", "file_name" => "130.doc", "origin_id" => 130],
//*********************************************************************************************************************************************************
            //131
            ["user_id" => 10930447, "case_id" => 136, "details" => "Bank document records", "owner" => "Andrew Aldrich",
                "title" => "King 'Ike' Bautista - Illegal Possession of Dangerous Drugs Case", "date_received" => "2012-05-23", "file_name" => "111.doc", "origin_id" => 136],
            //132
            ["user_id" => 10930448, "case_id" => 137, "details" => "Enclosed copy of 'indictment' and 'warrant of arrest' issued by the United States District of Columbia", "owner" => "Anibal Alfaro",
                "title" => "Parviz Khaki - Fraud Case", "date_received" => "2012-05-23", "file_name" => "111.doc", "origin_id" => 137],
            //133
            ["user_id" => 10930448, "case_id" => 139, "details" => "Car registration copies", "owner" => "Aron Alvarez",
                "title" => "Valerie Santiago Von Such - Estafa Case", "date_received" => "2008-05-15", "file_name" => "111.doc", "origin_id" => 139],
            //134
            ["user_id" => 10930448, "case_id" => 140, "details" => "Falsified commercial documents", "owner" => "Barry Andres",
                "title" => "Patricio D. Notada - Estafa Case", "date_received" => "2012-03-15", "file_name" => "111.doc", "origin_id" => 140],
            //135
            ["user_id" => 10930448, "case_id" => 140, "details" => "Promissory note", "owner" => "Barry Andres",
                "title" => "Patricio D. Notada - Estafa Case", "date_received" => "2012-03-15", "file_name" => "111.doc", "origin_id" => 140],
            //136
            ["user_id" => 10930448, "case_id" => 140, "details" => "Deed of assignment", "owner" => "Barry Andres",
                "title" => "Patricio D. Notada - Estafa Case", "date_received" => "2012-03-15", "file_name" => "111.doc", "origin_id" => 140],
            //137
            ["user_id" => 10930448, "case_id" => 140, "details" => "Collateral land titles", "owner" => "Barry Andres",
                "title" => "Patricio D. Notada - Estafa Case", "date_received" => "2012-03-15", "file_name" => "111.doc", "origin_id" => 140],
            //138
            ["user_id" => 10930448, "case_id" => 141, "details" => "Placement and processing fee receipt", "owner" => "Benito Anthony",
                "title" => "Juliet Red Rempis - Illegal Recruitment and Estafa Case", "date_received" => "2012-07-06", "file_name" => "111.doc", "origin_id" => 141],
            //139
            ["user_id" => 10930448, "case_id" => 141, "details" => "POEA verification of unlicensed recruitment of the suspect", "owner" => "Benito Anthony",
                "title" => "Juliet Red Rempis - Illegal Recruitment and Estafa Case", "date_received" => "2012-07-06", "file_name" => "111.doc", "origin_id" => 141],
            //140
            ["user_id" => 10930448, "case_id" => 142, "details" => "Investigative-intervention letter request", "owner" => "Bernie Aranda",
                "title" => "Huang Li Sin - Fraud Case", "date_received" => "2012-07-05", "file_name" => "111.doc", "origin_id" => 142],
            //141
            ["user_id" => 10930448, "case_id" => 142, "details" => "Intelligence report of MJIB", "owner" => "Bernie Aranda",
                "title" => "Huang Li Sin - Fraud Case", "date_received" => "2012-07-05", "file_name" => "111.doc", "origin_id" => 142],
            //142
            ["user_id" => 10930448, "case_id" => 143, "details" => "Falsified income tax receipts", "owner" => "Billy Arellano",
                "title" => "Fernando Del Rosario Geronimo - Falsification Case", "date_received" => "2012-08-17", "file_name" => "111.doc", "origin_id" => 143],
            //143
            ["user_id" => 10930448, "case_id" => 143, "details" => "Falsified DTI permit", "owner" => "Billy Arellano",
                "title" => "Fernando Del Rosario Geronimo - Falsification Case", "date_received" => "2012-08-17", "file_name" => "111.doc", "origin_id" => 143],
            //144
            ["user_id" => 10930448, "case_id" => 143, "details" => "Falsified bank account certification", "owner" => "Billy Arellano",
                "title" => "Fernando Del Rosario Geronimo - Falsification Case", "date_received" => "2012-08-17", "file_name" => "111.doc", "origin_id" => 143],
            //145
            ["user_id" => 10930448, "case_id" => 143, "details" => "Falsified land titles", "owner" => "Billy Arellano",
                "title" => "Fernando Del Rosario Geronimo - Falsification Case", "date_received" => "2012-08-17", "file_name" => "111.doc", "origin_id" => 143],
            //146
            ["user_id" => 10930448, "case_id" => 143, "details" => "Visa Application", "owner" => "Billy Arellano",
                "title" => "Fernando Del Rosario Geronimo - Falsification Case", "date_received" => "2012-08-17", "file_name" => "111.doc", "origin_id" => 143],
            //147
            ["user_id" => 10930447, "case_id" => 146, "details" => "Letter of complaint", "owner" => "Bruce Atkins",
                "title" => "Ronel 'Bryan Antos' Santiago - Kidnapping Case", "date_received" => "2012-12-14", "file_name" => "111.doc", "origin_id" => 146],
            //148
            ["user_id" => 10930447, "case_id" => 146, "details" => "Tracking number receipt from Cebuanna Lluillier", "owner" => "Bruce Atkins",
                "title" => "Ronel 'Bryan Antos' Santiago - Kidnapping Case", "date_received" => "2012-12-14", "file_name" => "111.doc", "origin_id" => 146],
            //149
            ["user_id" => 10930448, "case_id" => 150, "details" => "OFW requirement documents", "owner" => "Chong Barba",
                "title" => "Humanitarian Migrant Management International Inc. - Fraud Case", "date_received" => "2013-05-28", "file_name" => "111.doc", "origin_id" => 150],
            //150
            ["user_id" => 10930448, "case_id" => 150, "details" => "Applicant visa documents", "owner" => "Chong Barba",
                "title" => "Humanitarian Migrant Management International Inc. - Fraud Case", "date_received" => "2013-05-28", "file_name" => "111.doc", "origin_id" => 150],
            //151
            ["user_id" => 10930447, "case_id" => 151, "details" => "Official Receipt", "owner" => "Clifton Baron",
                "title" => "Alfredo Alejo Cabardo Jr. - Estafa Case", "date_received" => "2013-06-11", "file_name" => "111.doc", "origin_id" => 151],
            //152
            ["user_id" => 10930447, "case_id" => 151, "details" => "Certificate of Registration", "owner" => "Clifton Baron",
                "title" => "Alfredo Alejo Cabardo Jr. - Estafa Case", "date_received" => "2013-06-11", "file_name" => "111.doc", "origin_id" => 151],
            //153
            ["user_id" => 10930447, "case_id" => 151, "details" => "Plastic envelop with land titles", "owner" => "Clifton Baron",
                "title" => "Alfredo Alejo Cabardo Jr. - Estafa Case", "date_received" => "2013-06-11", "file_name" => "111.doc", "origin_id" => 151],
            //154
            ["user_id" => 10930447, "case_id" => 152, "details" => "Bank certificate", "owner" => "Dallas Bauer",
                "title" => "Rowell Valdez - Estafa Case", "date_received" => "2013-06-13", "file_name" => "111.doc", "origin_id" => 152],
            //155
            ["user_id" => 10930447, "case_id" => 152, "details" => "Fake Transcript of Records and Diploma from University of Cordillera", "owner" => "Dallas Bauer",
                "title" => "Rowell Valdez - Estafa Case", "date_received" => "2013-06-13", "file_name" => "111.doc", "origin_id" => 152],
            //156               
            ["user_id" => 10930448, "case_id" => 156, "details" => "Employment contract", "owner" => "Donte Bernard",
                "title" => "Marcial Ronquillo Bernardo - Illegal Recruitment Case", "date_received" => "2013-07-29", "file_name" => "111.doc", "origin_id" => 156],
            //157
            ["user_id" => 10930448, "case_id" => 156, "details" => "Scheduled payments", "owner" => "Donte Bernard",
                "title" => "Marcial Ronquillo Bernardo - Illegal Recruitment Case", "date_received" => "2013-07-29", "file_name" => "111.doc", "origin_id" => 156],
            //158
            ["user_id" => 10930448, "case_id" => 162, "details" => "Processing fee documents", "owner" => "Gerry Brandon",
                "title" => "Roberto A. Albana - Illegal Recruitment Case", "date_received" => "1995-08-10", "file_name" => "111.doc", "origin_id" => 162],
            //159
            ["user_id" => 10930448, "case_id" => 162, "details" => "Processing fee receipts", "owner" => "Gerry Brandon",
                "title" => "Roberto A. Albana - Illegal Recruitment Case", "date_received" => "1995-08-10", "file_name" => "111.doc", "origin_id" => 162],
            //160
            ["user_id" => 10930445, "case_id" => 163, "details" => "witness statement from Cristina Winterhalter", "owner" => "Harris Briseno",
                "title" => "Rodolfo Alcalde - Murder Case", "date_received" => "1990-02-11", "file_name" => "111.doc", "origin_id" => 163],
            //161
            ["user_id" => 10930446, "case_id" => 165, "details" => "List of valuables obtained by the subject", "owner" => "Irvin Buford",
                "title" => "Mario Azcarraga y Relebo - Robbery Case", "date_received" => "1997-08-20", "file_name" => "111.doc", "origin_id" => 165],
            //162
            ["user_id" => 10930444, "case_id" => 167, "details" => "Past criminal case documents", "owner" => "Jerrold Cabral",
                "title" => "Amado Bucala - Murder Case", "date_received" => "1999-07-20", "file_name" => "111.doc", "origin_id" => 167],
            //163
            ["user_id" => 10930447, "case_id" => 170, "details" => "receipts", "owner" => "Jim Calderon",
                "title" => "Neil 'Jojo' Cutad - Kidnapping Case", "date_received" => "2001-04-27", "file_name" => "111.doc", "origin_id" => 170],
            //164
            ["user_id" => 10930444, "case_id" => 171, "details" => "Letter of complaint", "owner" => "Johnathan Camacho",
                "title" => "Corey Dickpus - Murder Case", "date_received" => "1994-07-21", "file_name" => "111.doc", "origin_id" => 171],
            //165
            ["user_id" => 10930444, "case_id" => 171, "details" => "Tracking number receipt from LBC", "owner" => "Johnathan Camacho",
                "title" => "Corey Dickpus - Murder Case", "date_received" => "1994-07-21", "file_name" => "111.doc", "origin_id" => 171],
            //166
            ["user_id" => 10930447, "case_id" => 173, "details" => "Bank Certificate", "owner" => "Jonathan Canales",
                "title" => "Tony De Leon and Ernie Velasco - Estafa Case", "date_received" => "2003-07-22", "file_name" => "111.doc", "origin_id" => 173],
            //167
            ["user_id" => 10930447, "case_id" => 173, "details" => "Fake Transcript of Records and Diploma", "owner" => "Jonathan Canales",
                "title" => "Tony De Leon and Ernie Velasco - Estafa Case", "date_received" => "2003-07-22", "file_name" => "111.doc", "origin_id" => 173],
            //168
            ["user_id" => 10930446, "case_id" => 174, "details" => "List of valuables obtained by the subject", "owner" => "Josiah Caraballo",
                "title" => "Aldrin Bonobo Fajardo - Robbery Case", "date_received" => "2002-04-01", "file_name" => "111.doc", "origin_id" => 174],
            //169
            ["user_id" => 10930216, "case_id" => 177, "details" => "List of valuables obtained by the subject", "owner" => "Keneth Caro",
                "title" => "Rolando Gobiana - Robbery Case", "date_received" => "1993-03-21", "file_name" => "111.doc", "origin_id" => 177],
            //170
            ["user_id" => 10930446, "case_id" => 179, "details" => "List of valuables obtained by the subject", "owner" => "Laverne Castro",
                "title" => "Eduardo 'Boy Muslim' Iran - Robbery, Holdup, Kidnapping and Murder Case", "date_received" => "1984-12-29", "file_name" => "111.doc", "origin_id" => 179],
            //171
            ["user_id" => 10930444, "case_id" => 184, "details" => "Document of amassed ill-gotten wealth", "owner" => "Santos Dasilva",
                "title" => "Joel P. Marcelo - Plunder Case", "date_received" => "1997-11-12", "file_name" => "111.doc", "origin_id" => 184],
            //172
            ["user_id" => 10930444, "case_id" => 184, "details" => "PDAF documents", "owner" => "Santos Dasilva",
                "title" => "Joel P. Marcelo - Plunder Case", "date_received" => "1997-11-12", "file_name" => "111.doc", "origin_id" => 184],
            //173
            ["user_id" => 10930444, "case_id" => 184, "details" => "Official Receipt", "owner" => "Santos Dasilva",
                "title" => "Joel P. Marcelo - Plunder Case", "date_received" => "1997-11-12", "file_name" => "111.doc", "origin_id" => 184],
            //174
            ["user_id" => 10930220, "case_id" => 189, "details" => "Letter of complaint", "owner" => "Thaddeus Diaz",
                "title" => "Felizardo Pagulayan - Kidnapping Case", "date_received" => "1994-12-12", "file_name" => "111.doc", "origin_id" => 189],
            //175
            ["user_id" => 10930220, "case_id" => 193, "details" => "Eyewitness testimony", "owner" => "Ulysses Doran",
                "title" => "Alice Rosero - Robbery Case", "date_received" => "1996-03-21", "file_name" => "111.doc", "origin_id" => 193],
            //176
            ["user_id" => 10930446, "case_id" => 195, "details" => "Eyewitness testimony", "owner" => "Young Durant",
                "title" => "Fraser Salamon a.k.a Fraser and Abu Jarin - Robbery, Murder, and Kidnapping Case", "date_received" => "1998-05-26", "file_name" => "111.doc", "origin_id" => 195],
            //177
            ["user_id" => 10930446, "case_id" => 195, "details" => "Testimony of accomplices", "owner" => "Young Durant",
                "title" => "Fraser Salamon a.k.a Fraser and Abu Jarin - Robbery, Murder, and Kidnapping Case", "date_received" => "1998-05-26", "file_name" => "111.doc", "origin_id" => 195],
            //178
            ["user_id" => 10930447, "case_id" => 197, "details" => "DNA results of the bathroom", "owner" => "Kevin Gomez",
                "title" => "Antonio Sanchez - Rape Case", "date_received" => "1993-05-12", "file_name" => "111.doc", "origin_id" => 197],
            //179
            ["user_id" => 10930448, "case_id" => 199, "details" => "Eyewitness testimony", "owner" => "John Santos",
                "title" => "Mario Valerio - Kidnapping Case", "date_received" => "2003-09-11", "file_name" => "111.doc", "origin_id" => 199],
            //180
            ["user_id" => 10930448, "case_id" => 199, "details" => "Testimony of accomplices", "owner" => "John Santos",
                "title" => "Mario Valerio - Kidnapping Case", "date_received" => "2003-09-11", "file_name" => "111.doc", "origin_id" => 199],
            //181
            ["user_id" => 10930445, "case_id" => 200, "details" => "Eyewitness testimony", "owner" => "Kelvin Pineda",
                "title" => "Raul Villar a.k.a Ka Drilon - Robbery with Homicide Case", "date_received" => "2002-12-03", "file_name" => "111.doc", "origin_id" => 200],
            //182
            ["user_id" => 10930445, "case_id" => 200, "details" => "Testimony of accomplices", "owner" => "Kelvin Pineda",
                "title" => "Raul Villar a.k.a Ka Drilon - Robbery with Homicide Case", "date_received" => "2002-12-03", "file_name" => "111.doc", "origin_id" => 200],
            //183
            ["user_id" => 10930444, "case_id" => 201, "details" => "DNA results of the bathroom", "owner" => "Simon Albaniel",
                "title" => "Eddie Zamora a.k.a Eddie Boy - Rape Case", "date_received" => "1996-05-11", "file_name" => "111.doc", "origin_id" => 201],
            //184
            ["user_id" => 10930444, "case_id" => 202, "details" => "VIVA and BIDA productions documents", "owner" => "Francis Amores",
                "title" => "Efrain Genuino - Malversation of Public Funds Case", "date_received" => "2011-10-06", "file_name" => "111.doc", "origin_id" => 202],
            //185
            ["user_id" => 10930444, "case_id" => 202, "details" => "Joint movie production agreement", "owner" => "Francis Amores",
                "title" => "Efrain Genuino - Malversation of Public Funds Case", "date_received" => "2011-10-06", "file_name" => "111.doc", "origin_id" => 202],
            //186
            ["user_id" => 10930444, "case_id" => 204, "details" => "Bank accounts of the subject and his family members", "owner" => "Lindon Ruiz",
                "title" => "Carlos F. Garcia - Tax Evasion Case", "date_received" => "2011-03-10", "file_name" => "111.doc", "origin_id" => 204],
            //187
            ["user_id" => 10930444, "case_id" => 205, "details" => "Financial transaction documents from the Senate Committee on Finance (SCF)", "owner" => "Carlo Simeon",
                "title" => "Romulo Luminarias Neri - Tax Evasion Case", "date_received" => "2010-11-04", "file_name" => "111.doc", "origin_id" => 205],
            //188
            ["user_id" => 10930444, "case_id" => 205, "details" => "Income tax return for the year 2008 and 2009", "owner" => "Carlo Simeon",
                "title" => "Romulo Luminarias Neri - Tax Evasion Case", "date_received" => "2010-11-04", "file_name" => "111.doc", "origin_id" => 205],
        );

        // Uncomment the below to run the seeder
        DB::table('evidence_documents')->insert($evidence_documents);
    }

}
