<?php

class UsersTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('users')->truncate();

        $users = array(
            ["id" => 10930195, "last_name" => "Yu", "first_name" => "Allan",
                "middle_name" => "Go", "birthdate" => "1960-09-22", "date_hired" => "1989-01-02",
                "job_title" => "Chief", "division" => "AFAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930196, "last_name" => "Zaplan", "first_name" => "Racquel",
                "middle_name" => "Gaw", "birthdate" => "1990-02-10", "date_hired" => "2012-06-28",
                "job_title" => "Secretary", "division" => "AFAD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Annulled", "file_picture" => "10930192.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930197, "last_name" => "Gaw", "first_name" => "Lewin",
                "middle_name" => "Yu", "birthdate" => "1966-12-05", "date_hired" => "1988-05-30",
                "job_title" => "Chief", "division" => "AGD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930198, "last_name" => "Sy", "first_name" => "Nancy",
                "middle_name" => "Kim", "birthdate" => "1979-10-10", "date_hired" => "1999-08-01",
                "job_title" => "Secretary", "division" => "AGD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930198.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930199, "last_name" => "Sy", "first_name" => "Johnny",
                "middle_name" => "Lee", "birthdate" => "1947-04-05", "date_hired" => "1970-09-30",
                "job_title" => "Chief", "division" => "AHTRAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930110, "last_name" => "Sy", "first_name" => "Nancy",
                "middle_name" => "Kim", "birthdate" => "1979-10-10", "date_hired" => "1994-08-21",
                "job_title" => "Secretary", "division" => "AHTRAD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930198.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930111, "last_name" => "Ching", "first_name" => "Demetrio",
                "middle_name" => "Sy", "birthdate" => "1943-05-10", "date_hired" => "1998-09-04",
                "job_title" => "Chief", "division" => "AOCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930112, "last_name" => "Corpuz", "first_name" => "Teresa",
                "middle_name" => "Kim", "birthdate" => "1955-07-22", "date_hired" => "1991-05-02",
                "job_title" => "Secretary", "division" => "AOCD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930198.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930113, "last_name" => "Alvarez", "first_name" => "Richard",
                "middle_name" => "Lee", "birthdate" => "1947-04-05", "date_hired" => "1970-09-30",
                "job_title" => "Chief", "division" => "CCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Annulled", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930114, "last_name" => "Lapuz", "first_name" => "Mely",
                "middle_name" => "Martinez", "birthdate" => "1979-10-10", "date_hired" => "1994-08-21",
                "job_title" => "Secretary", "division" => "CCD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930192.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930115, "last_name" => "Chua", "first_name" => "Rafael",
                "middle_name" => "Lee", "birthdate" => "1968-12-03", "date_hired" => "2000-07-24",
                "job_title" => "Chief", "division" => "DID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930116, "last_name" => "Lim", "first_name" => "Suzette",
                "middle_name" => "Galarpe", "birthdate" => "1958-11-06", "date_hired" => "1995-09-22",
                "job_title" => "Secretary", "division" => "DID", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930192.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930117, "last_name" => "Sy", "first_name" => "Terry",
                "middle_name" => "Pineda", "birthdate" => "1956-10-07", "date_hired" => "1997-04-30",
                "job_title" => "Chief", "division" => "EWPID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930118, "last_name" => "Patron", "first_name" => "Tiffany",
                "middle_name" => "Sy", "birthdate" => "1980-08-05", "date_hired" => "2005-11-18",
                "job_title" => "Secretary", "division" => "EWPID", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930118.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930119, "last_name" => "Mendoza", "first_name" => "Marvin",
                "middle_name" => "Sipin", "birthdate" => "1947-01-18", "date_hired" => "1995-07-12",
                "job_title" => "Chief", "division" => "IPRD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Annulled", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930120, "last_name" => "Abesamis", "first_name" => "Melanie",
                "middle_name" => "Ancheta", "birthdate" => "1980-08-05", "date_hired" => "2006-11-24",
                "job_title" => "Secretary", "division" => "IPRD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930118.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930121, "last_name" => "Espenesin", "first_name" => "Sixto",
                "middle_name" => "Untalan", "birthdate" => "1950-03-15", "date_hired" => "1990-06-15",
                "job_title" => "Chief", "division" => "RAID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930122, "last_name" => "Arcilla", "first_name" => "Stephanie",
                "middle_name" => "Dy", "birthdate" => "1985-12-07", "date_hired" => "2003-08-12",
                "job_title" => "Secretary", "division" => "RAID", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png", "status" => "Active", "rank" => ""],
            ["id" => 10930123, "last_name" => "Cruz", "first_name" => "Glen",
                "middle_name" => "Schaer", "birthdate" => "1951-07-18", "date_hired" => "1990-07-10",
                "job_title" => "Chief", "division" => "VACWD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930124, "last_name" => "Tangkeko", "first_name" => "Victoria",
                "middle_name" => "Magpantay", "birthdate" => "1960-04-19", "date_hired" => "2000-02-18",
                "job_title" => "Secretary", "division" => "VACWD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930118.jpg", "status" => "Active", "rank" => ""],
            //**AFAD**//
            ["id" => 10916644, "last_name" => "Bahaghari", "first_name" => "Christopher",
                "middle_name" => "Manalo", "birthdate" => "1973-01-26", "date_hired" => "1999-09-10",
                "job_title" => "Agent", "division" => "AFAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10916645, "last_name" => "Batanes", "first_name" => "Taylor",
                "middle_name" => "Andres", "birthdate" => "1970-10-29", "date_hired" => "2004-10-11",
                "job_title" => "Agent", "division" => "AFAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            //**AGD**//
            ["id" => 10916646, "last_name" => "Cabanag", "first_name" => "Stephen James",
                "middle_name" => "Cacal", "birthdate" => "1969-10-22", "date_hired" => "2001-12-19",
                "job_title" => "Agent", "division" => "AGD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10916647, "last_name" => "Cacal", "first_name" => "Ralph Vincent",
                "middle_name" => "Antonio", "birthdate" => "1980-10-30", "date_hired" => "2005-08-01",
                "job_title" => "Agent", "division" => "AGD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            //**AHTRAD**//
            ["id" => 10916648, "last_name" => "Alba", "first_name" => "Bayani",
                "middle_name" => "Castillo", "birthdate" => "1969-07-22", "date_hired" => "1995-04-05",
                "job_title" => "Agent", "division" => "AHTRAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10916649, "last_name" => "Cacal", "first_name" => "Roberto",
                "middle_name" => "Climacosa", "birthdate" => "1971-06-30", "date_hired" => "1998-08-24",
                "job_title" => "Agent", "division" => "AHTRAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            //**AOCD**//
            ["id" => 10916650, "last_name" => "Antonio", "first_name" => "Josefino",
                "middle_name" => "Santos", "birthdate" => "1974-10-21", "date_hired" => "2007-08-05",
                "job_title" => "Agent", "division" => "AOCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10916651, "last_name" => "Flores", "first_name" => "Roberto",
                "middle_name" => "Cacab", "birthdate" => "1970-11-02", "date_hired" => "2000-10-24",
                "job_title" => "Agent", "division" => "AOCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            //**CCD**//
            ["id" => 10916652, "last_name" => "Briones", "first_name" => "Wilbert",
                "middle_name" => "Cadlaon", "birthdate" => "1964-10-22", "date_hired" => "1998-09-14",
                "job_title" => "Agent", "division" => "CCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10916653, "last_name" => "Manio", "first_name" => "Percy",
                "middle_name" => "Balboa", "birthdate" => "1965-09-10", "date_hired" => "1999-03-09",
                "job_title" => "Agent", "division" => "CCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Annulled", "file_picture" => "10916644.jpg", "status" => "Active", "rank" => ""],
            // FLD CHIEF   ******************************************************************************
            ["id" => 10930193, "last_name" => "Daganzo", "first_name" => "Daniel",
                "middle_name" => "Zaraspe", "birthdate" => "1949-10-15", "date_hired" => "2010-03-09",
                "job_title" => "Chief", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Divorced", "file_picture" => "10930193.jpg", "status" => "Active", "rank" => "Head Agent"],
            //FLD EXECUTIVE OFFICER ******************************************************************************
            ["id" => 10930316, "last_name" => "Rosales", "first_name" => "Arnold",
                "middle_name" => "Robles", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930316.jpg", "status" => "Active", "rank" => "Supervising Agent"],
            // FLD SECRETARY  ******************************************************************************
            ["id" => 10930192, "last_name" => "Bautista", "first_name" => "Teresa",
                "middle_name" => "Formoso", "birthdate" => "1993-08-01", "date_hired" => "2013-04-18",
                "job_title" => "Secretary", "division" => "FLD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930192.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930218, "last_name" => "Yumol", "first_name" => "Cora",
                "middle_name" => "Gajo", "birthdate" => "1975-01-23", "date_hired" => "1990-05-15",
                "job_title" => "Secretary", "division" => "FLD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930218.jpg", "status" => "Active", "rank" => ""],
            // ADDED FLD AGENTS 10930444 - 10940453 ******************************************************************************
            //5 Agents, 2 XO, 1 Chief, 1 Secretary  ******************************************************************************
            //10 FLD Agents
            ["id" => 10930216, "last_name" => "Martinez", "first_name" => "Wilhelm Paul",
                "middle_name" => "Bautista", "birthdate" => "1993-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930216.jpg", "status" => "Active", "rank" => "Special Investigator 4"],
            ["id" => 10930217, "last_name" => "Espenesin", "first_name" => "Enrico",
                "middle_name" => "Gajo", "birthdate" => "1976-01-23", "date_hired" => "1990-05-15",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => "Agent 3"],
            ["id" => 10930219, "last_name" => "Patrimonio", "first_name" => "Christopher",
                "middle_name" => "Antonio", "birthdate" => "1974-01-23", "date_hired" => "1990-05-15",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930219.jpg", "status" => "Active", "rank" => "Agent 3"],
            ["id" => 10930220, "last_name" => "Lee", "first_name" => "Gabe",
                "middle_name" => "Santos", "birthdate" => "1973-01-23", "date_hired" => "1990-05-15",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930220.jpg", "status" => "Active", "rank" => "Agent 2"],
            ["id" => 10930221, "last_name" => "Fuego", "first_name" => "Albert",
                "middle_name" => "Torres", "birthdate" => "1972-01-23", "date_hired" => "1990-05-15",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930221.jpg", "status" => "Active", "rank" => "Agent 2"],
            ["id" => 10930444, "last_name" => "Rivera", "first_name" => "Maximo",
                "middle_name" => "Termulo", "birthdate" => "1971-02-11", "date_hired" => "1997-11-10",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930444.jpg", "status" => "Active", "rank" => "Agent 1"],
            ["id" => 10930445, "last_name" => "Santos", "first_name" => "Jeffrey",
                "middle_name" => "Pandig", "birthdate" => "1965-12-23", "date_hired" => "1990-01-23",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930445.jpg", "status" => "Active", "rank" => "Senior Agent"],
            ["id" => 10930446, "last_name" => "Manahan", "first_name" => "James",
                "middle_name" => "Marquez", "birthdate" => "1980-05-21", "date_hired" => "2006-10-30",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930446.jpg", "status" => "Active", "rank" => "Special Investigator 3"],
            ["id" => 10930447, "last_name" => "Sy", "first_name" => "Aldrin",
                "middle_name" => "Revilla", "birthdate" => "1983-04-21", "date_hired" => "2004-01-25",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930447.jpg", "status" => "Active", "rank" => "Special Investigator 2"],
            ["id" => 10930448, "last_name" => "Ritualo", "first_name" => "Chester",
                "middle_name" => "Laon", "birthdate" => "1973-10-11", "date_hired" => "2001-10-15",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930448.jpg", "status" => "Active", "rank" => "Special Investigator 1"],
            //DID Agent
            ["id" => 10930201, "last_name" => "Martinez", "first_name" => "Brandon",
                "middle_name" => "Bautista", "birthdate" => "1993-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "DID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930202, "last_name" => "Untalan", "first_name" => "Cyruz",
                "middle_name" => "Bautista", "birthdate" => "1991-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "DID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930203, "last_name" => "Santos", "first_name" => "Mark",
                "middle_name" => "Bautista", "birthdate" => "1992-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "DID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            //EWPID Agent
            ["id" => 10930204, "last_name" => "Pascual", "first_name" => "Juancho",
                "middle_name" => "Bautista", "birthdate" => "1990-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "EWPID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930205, "last_name" => "Chua", "first_name" => "Lou",
                "middle_name" => "Bautista", "birthdate" => "1989-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "EWPID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930206, "last_name" => "Garcia", "first_name" => "Ken",
                "middle_name" => "Bautista", "birthdate" => "1994-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "EWPID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            //IPRD Agent
            ["id" => 10930207, "last_name" => "Cruz", "first_name" => "Patrick",
                "middle_name" => "Bautista", "birthdate" => "1986-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "IPRD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930208, "last_name" => "Ortiz", "first_name" => "Lorenzo",
                "middle_name" => "Bautista", "birthdate" => "1985-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "IPRD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930209, "last_name" => "Go", "first_name" => "Poochie",
                "middle_name" => "Bautista", "birthdate" => "1984-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "IPRD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930217.jpg", "status" => "Active", "rank" => ""],
            //RAID Agent
            ["id" => 10930210, "last_name" => "Galarpe", "first_name" => "Mark",
                "middle_name" => "Bautista", "birthdate" => "1981-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "RAID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930210.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930211, "last_name" => "Ty", "first_name" => "Joey",
                "middle_name" => "Bautista", "birthdate" => "1982-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "RAID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930210.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930212, "last_name" => "Fuentes", "first_name" => "Chino",
                "middle_name" => "Bautista", "birthdate" => "1983-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "RAID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930210.jpg", "status" => "Active", "rank" => ""],
            //VAWCD Agent
            ["id" => 10930213, "last_name" => "Go", "first_name" => "Shoti",
                "middle_name" => "Bautista", "birthdate" => "1985-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "VAWCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930210.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930214, "last_name" => "Schaer", "first_name" => "Marvin",
                "middle_name" => "Bautista", "birthdate" => "1986-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "VAWCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930210.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930215, "last_name" => "Robles", "first_name" => "Earl",
                "middle_name" => "Bautista", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "VAWCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930210.jpg", "status" => "Active", "rank" => ""],
            //Executive_Officer 1 PER DIVISION
            ["id" => 10930311, "last_name" => "Lagdameyo", "first_name" => "Raul",
                "middle_name" => "Albores", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "AFAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930312, "last_name" => "Thompson", "first_name" => "Emile",
                "middle_name" => "Gore", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "AGD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930313, "last_name" => "Tejada", "first_name" => "Sean",
                "middle_name" => "Hamido", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "AHTRAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930314, "last_name" => "Kartillo", "first_name" => "Elaijon",
                "middle_name" => "Fames", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "AOCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930315, "last_name" => "Dominguez", "first_name" => "Janzen",
                "middle_name" => "Harte", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "CCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930317, "last_name" => "Miranda", "first_name" => "Robert",
                "middle_name" => "Almazan", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "EWPID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930318, "last_name" => "Alcaraz", "first_name" => "Keo",
                "middle_name" => "Santos", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "IPRD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930319, "last_name" => "Santiago", "first_name" => "Ricardo",
                "middle_name" => "Bernardo", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "RAID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930320, "last_name" => "Ledesma", "first_name" => "Ivan",
                "middle_name" => "Philip", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "VAWCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
            ["id" => 10930321, "last_name" => "Zapanta", "first_name" => "Carl",
                "middle_name" => "So", "birthdate" => "1987-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Executive_Officer", "division" => "DID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930311.jpg", "status" => "Active", "rank" => ""],
        );

        // Uncomment the below to run the seeder
        DB::table('users')->insert($users);
    }

}
