<?php

class UsersTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('users')->truncate();

        $users = array(
            ["id" => "10930191", "last_name" => "Martinez", "first_name" => "Wilhelm Paul",
                "middle_name" => "Bautista", "birthdate" => "1993-02-26", "date_hired" => "2014-02-10",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930191.png"],
            ["id" => "10930192", "last_name" => "Kau", "first_name" => "Janine",
                "middle_name" => "Formoso", "birthdate" => "1993-08-01", "date_hired" => "2013-04-18",
                "job_title" => "Secretary", "division" => "FLD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930193", "last_name" => "Untalan", "first_name" => "Kier Hassel",
                "middle_name" => "Zaraspe", "birthdate" => "1949-10-15", "date_hired" => "2010-03-09",
                "job_title" => "Chief", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Divorced", "file_picture" => "10930191.png"],
            ["id" => "10930194", "last_name" => "Espenesin", "first_name" => "Enrico",
                "middle_name" => "Gajo", "birthdate" => "1969-01-23", "date_hired" => "1990-05-15",
                "job_title" => "Agent", "division" => "FLD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930191.png"],
            ["id" => "10930195", "last_name" => "Yu", "first_name" => "Allan",
                "middle_name" => "Go", "birthdate" => "1960-09-22", "date_hired" => "1989-01-02",
                "job_title" => "Chief", "division" => "AFAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930196", "last_name" => "Zaplan", "first_name" => "Racquel",
                "middle_name" => "Gaw", "birthdate" => "1990-02-10", "date_hired" => "2012-06-28",
                "job_title" => "Secretary", "division" => "AFAD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Annulled", "file_picture" => "10930191.png"],
            ["id" => "10930197", "last_name" => "Gaw", "first_name" => "Lewin",
                "middle_name" => "Yu", "birthdate" => "1966-12-05", "date_hired" => "1988-05-30",
                "job_title" => "Chief", "division" => "AGD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930198", "last_name" => "Sy", "first_name" => "Nancy",
                "middle_name" => "Kim", "birthdate" => "1979-10-10", "date_hired" => "1999-08-01",
                "job_title" => "Secretary", "division" => "AGD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930199", "last_name" => "Sy", "first_name" => "Johnny",
                "middle_name" => "Lee", "birthdate" => "1947-04-05", "date_hired" => "1970-09-30",
                "job_title" => "Chief", "division" => "AHTRAD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Widowed", "file_picture" => "10930191.png"],
            ["id" => "10930110", "last_name" => "Sy", "first_name" => "Nancy",
                "middle_name" => "Kim", "birthdate" => "1979-10-10", "date_hired" => "1994-08-21",
                "job_title" => "Secretary", "division" => "AHTRAD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930111", "last_name" => "Ching", "first_name" => "Demetrio",
                "middle_name" => "Sy", "birthdate" => "1943-05-10", "date_hired" => "1998-09-04",
                "job_title" => "Chief", "division" => "AOCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930112", "last_name" => "Corpuz", "first_name" => "Teresa",
                "middle_name" => "Kim", "birthdate" => "1955-07-22", "date_hired" => "1991-05-02",
                "job_title" => "Secretary", "division" => "AOCD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930191.png"],
            ["id" => "10930113", "last_name" => "Alvarez", "first_name" => "Richard",
                "middle_name" => "Lee", "birthdate" => "1947-04-05", "date_hired" => "1970-09-30",
                "job_title" => "Chief", "division" => "CCD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Annulled", "file_picture" => "10930191.png"],
            ["id" => "10930114", "last_name" => "Lapuz", "first_name" => "Mely",
                "middle_name" => "Martinez", "birthdate" => "1979-10-10", "date_hired" => "1994-08-21",
                "job_title" => "Secretary", "division" => "CCD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930115", "last_name" => "Chua", "first_name" => "Rafael",
                "middle_name" => "Lee", "birthdate" => "1968-12-03", "date_hired" => "2000-07-24",
                "job_title" => "Chief", "division" => "DID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930191.png"],
            ["id" => "10930116", "last_name" => "Lim", "first_name" => "Suzette",
                "middle_name" => "Galarpe", "birthdate" => "1958-11-06", "date_hired" => "1995-09-22",
                "job_title" => "Secretary", "division" => "DID", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930117", "last_name" => "Sy", "first_name" => "Terry",
                "middle_name" => "Pineda", "birthdate" => "1956-10-07", "date_hired" => "1997-04-30",
                "job_title" => "Chief", "division" => "EWPID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930191.png"],
            ["id" => "10930118", "last_name" => "Patron", "first_name" => "Tiffany",
                "middle_name" => "Sy", "birthdate" => "1980-08-05", "date_hired" => "2005-11-18",
                "job_title" => "Secretary", "division" => "EWPID", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930119", "last_name" => "Mendoza", "first_name" => "Marvin",
                "middle_name" => "Sipin", "birthdate" => "1947-01-18", "date_hired" => "1995-07-12",
                "job_title" => "Chief", "division" => "IPRD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Annulled", "file_picture" => "10930191.png"],
            ["id" => "10930120", "last_name" => "Abesamis", "first_name" => "Melanie",
                "middle_name" => "Ancheta", "birthdate" => "1980-08-05", "date_hired" => "2006-11-24",
                "job_title" => "Secretary", "division" => "IPRD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930121", "last_name" => "Espenesin", "first_name" => "Sixto",
                "middle_name" => "Untalan", "birthdate" => "1950-03-15", "date_hired" => "1990-06-15",
                "job_title" => "Chief", "division" => "RAID", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930191.png"],
            ["id" => "10930122", "last_name" => "Arcilla", "first_name" => "Stephanie",
                "middle_name" => "Dy", "birthdate" => "1985-12-07", "date_hired" => "2003-08-12",
                "job_title" => "Secretary", "division" => "RAID", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Single", "file_picture" => "10930191.png"],
            ["id" => "10930123", "last_name" => "Cruz", "first_name" => "Glen",
                "middle_name" => "Schaer", "birthdate" => "1951-07-18", "date_hired" => "1990-07-10",
                "job_title" => "Chief", "division" => "VACWD", "sex" => "Male", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930191.png"],
            ["id" => "10930124", "last_name" => "Tangkeko", "first_name" => "Victoria",
                "middle_name" => "Magpantay", "birthdate" => "1960-04-19", "date_hired" => "2000-02-18",
                "job_title" => "Secretary", "division" => "VACWD", "sex" => "Female", "password" => Hash::make("pawie2062"),
                "civil_status" => "Married", "file_picture" => "10930191.png"],
        );

        // Uncomment the below to run the seeder
        DB::table('users')->insert($users);
    }

}
